// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package stream

import (
	"context"
	"umineko_city_of_books/internal/dto"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Enabled provides a mock function for the type MockService
func (_mock *MockService) Enabled() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Enabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockService_Enabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enabled'
type MockService_Enabled_Call struct {
	*mock.Call
}

// Enabled is a helper method to define mock.On call
func (_e *MockService_Expecter) Enabled() *MockService_Enabled_Call {
	return &MockService_Enabled_Call{Call: _e.mock.On("Enabled")}
}

func (_c *MockService_Enabled_Call) Run(run func()) *MockService_Enabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Enabled_Call) Return(b bool) *MockService_Enabled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockService_Enabled_Call) RunAndReturn(run func() bool) *MockService_Enabled_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockService
func (_mock *MockService) Get(ctx context.Context, streamID uuid.UUID) (*dto.LiveStreamResponse, error) {
	ret := _mock.Called(ctx, streamID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *dto.LiveStreamResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.LiveStreamResponse, error)); ok {
		return returnFunc(ctx, streamID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.LiveStreamResponse); ok {
		r0 = returnFunc(ctx, streamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.LiveStreamResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, streamID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - streamID uuid.UUID
func (_e *MockService_Expecter) Get(ctx interface{}, streamID interface{}) *MockService_Get_Call {
	return &MockService_Get_Call{Call: _e.mock.On("Get", ctx, streamID)}
}

func (_c *MockService_Get_Call) Run(run func(ctx context.Context, streamID uuid.UUID)) *MockService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Get_Call) Return(liveStreamResponse *dto.LiveStreamResponse, err error) *MockService_Get_Call {
	_c.Call.Return(liveStreamResponse, err)
	return _c
}

func (_c *MockService_Get_Call) RunAndReturn(run func(ctx context.Context, streamID uuid.UUID) (*dto.LiveStreamResponse, error)) *MockService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// HandleWebhook provides a mock function for the type MockService
func (_mock *MockService) HandleWebhook(ctx context.Context, authHeader string, body []byte) (bool, error) {
	ret := _mock.Called(ctx, authHeader, body)

	if len(ret) == 0 {
		panic("no return value specified for HandleWebhook")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) (bool, error)); ok {
		return returnFunc(ctx, authHeader, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) bool); ok {
		r0 = returnFunc(ctx, authHeader, body)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = returnFunc(ctx, authHeader, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_HandleWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleWebhook'
type MockService_HandleWebhook_Call struct {
	*mock.Call
}

// HandleWebhook is a helper method to define mock.On call
//   - ctx context.Context
//   - authHeader string
//   - body []byte
func (_e *MockService_Expecter) HandleWebhook(ctx interface{}, authHeader interface{}, body interface{}) *MockService_HandleWebhook_Call {
	return &MockService_HandleWebhook_Call{Call: _e.mock.On("HandleWebhook", ctx, authHeader, body)}
}

func (_c *MockService_HandleWebhook_Call) Run(run func(ctx context.Context, authHeader string, body []byte)) *MockService_HandleWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_HandleWebhook_Call) Return(handled bool, err error) *MockService_HandleWebhook_Call {
	_c.Call.Return(handled, err)
	return _c
}

func (_c *MockService_HandleWebhook_Call) RunAndReturn(run func(ctx context.Context, authHeader string, body []byte) (bool, error)) *MockService_HandleWebhook_Call {
	_c.Call.Return(run)
	return _c
}

// ListLive provides a mock function for the type MockService
func (_mock *MockService) ListLive(ctx context.Context) ([]dto.LiveStreamResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListLive")
	}

	var r0 []dto.LiveStreamResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]dto.LiveStreamResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []dto.LiveStreamResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.LiveStreamResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListLive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLive'
type MockService_ListLive_Call struct {
	*mock.Call
}

// ListLive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ListLive(ctx interface{}) *MockService_ListLive_Call {
	return &MockService_ListLive_Call{Call: _e.mock.On("ListLive", ctx)}
}

func (_c *MockService_ListLive_Call) Run(run func(ctx context.Context)) *MockService_ListLive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_ListLive_Call) Return(liveStreamResponses []dto.LiveStreamResponse, err error) *MockService_ListLive_Call {
	_c.Call.Return(liveStreamResponses, err)
	return _c
}

func (_c *MockService_ListLive_Call) RunAndReturn(run func(ctx context.Context) ([]dto.LiveStreamResponse, error)) *MockService_ListLive_Call {
	_c.Call.Return(run)
	return _c
}

// MintViewerToken provides a mock function for the type MockService
func (_mock *MockService) MintViewerToken(ctx context.Context, streamID uuid.UUID) (string, string, error) {
	ret := _mock.Called(ctx, streamID)

	if len(ret) == 0 {
		panic("no return value specified for MintViewerToken")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, string, error)); ok {
		return returnFunc(ctx, streamID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = returnFunc(ctx, streamID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) string); ok {
		r1 = returnFunc(ctx, streamID)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = returnFunc(ctx, streamID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_MintViewerToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MintViewerToken'
type MockService_MintViewerToken_Call struct {
	*mock.Call
}

// MintViewerToken is a helper method to define mock.On call
//   - ctx context.Context
//   - streamID uuid.UUID
func (_e *MockService_Expecter) MintViewerToken(ctx interface{}, streamID interface{}) *MockService_MintViewerToken_Call {
	return &MockService_MintViewerToken_Call{Call: _e.mock.On("MintViewerToken", ctx, streamID)}
}

func (_c *MockService_MintViewerToken_Call) Run(run func(ctx context.Context, streamID uuid.UUID)) *MockService_MintViewerToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_MintViewerToken_Call) Return(token string, url string, err error) *MockService_MintViewerToken_Call {
	_c.Call.Return(token, url, err)
	return _c
}

func (_c *MockService_MintViewerToken_Call) RunAndReturn(run func(ctx context.Context, streamID uuid.UUID) (string, string, error)) *MockService_MintViewerToken_Call {
	_c.Call.Return(run)
	return _c
}

// MyStream provides a mock function for the type MockService
func (_mock *MockService) MyStream(ctx context.Context, userID uuid.UUID) (*dto.StreamOwnerResponse, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MyStream")
	}

	var r0 *dto.StreamOwnerResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*dto.StreamOwnerResponse, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *dto.StreamOwnerResponse); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.StreamOwnerResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_MyStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MyStream'
type MockService_MyStream_Call struct {
	*mock.Call
}

// MyStream is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockService_Expecter) MyStream(ctx interface{}, userID interface{}) *MockService_MyStream_Call {
	return &MockService_MyStream_Call{Call: _e.mock.On("MyStream", ctx, userID)}
}

func (_c *MockService_MyStream_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockService_MyStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_MyStream_Call) Return(streamOwnerResponse *dto.StreamOwnerResponse, err error) *MockService_MyStream_Call {
	_c.Call.Return(streamOwnerResponse, err)
	return _c
}

func (_c *MockService_MyStream_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*dto.StreamOwnerResponse, error)) *MockService_MyStream_Call {
	_c.Call.Return(run)
	return _c
}

// ReconcileOnce provides a mock function for the type MockService
func (_mock *MockService) ReconcileOnce(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReconcileOnce")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ReconcileOnce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReconcileOnce'
type MockService_ReconcileOnce_Call struct {
	*mock.Call
}

// ReconcileOnce is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ReconcileOnce(ctx interface{}) *MockService_ReconcileOnce_Call {
	return &MockService_ReconcileOnce_Call{Call: _e.mock.On("ReconcileOnce", ctx)}
}

func (_c *MockService_ReconcileOnce_Call) Run(run func(ctx context.Context)) *MockService_ReconcileOnce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_ReconcileOnce_Call) Return(n int, err error) *MockService_ReconcileOnce_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockService_ReconcileOnce_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *MockService_ReconcileOnce_Call {
	_c.Call.Return(run)
	return _c
}

// StartStream provides a mock function for the type MockService
func (_mock *MockService) StartStream(ctx context.Context, userID uuid.UUID, title string) (*dto.StreamOwnerResponse, error) {
	ret := _mock.Called(ctx, userID, title)

	if len(ret) == 0 {
		panic("no return value specified for StartStream")
	}

	var r0 *dto.StreamOwnerResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*dto.StreamOwnerResponse, error)); ok {
		return returnFunc(ctx, userID, title)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *dto.StreamOwnerResponse); ok {
		r0 = returnFunc(ctx, userID, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.StreamOwnerResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, userID, title)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_StartStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartStream'
type MockService_StartStream_Call struct {
	*mock.Call
}

// StartStream is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - title string
func (_e *MockService_Expecter) StartStream(ctx interface{}, userID interface{}, title interface{}) *MockService_StartStream_Call {
	return &MockService_StartStream_Call{Call: _e.mock.On("StartStream", ctx, userID, title)}
}

func (_c *MockService_StartStream_Call) Run(run func(ctx context.Context, userID uuid.UUID, title string)) *MockService_StartStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_StartStream_Call) Return(streamOwnerResponse *dto.StreamOwnerResponse, err error) *MockService_StartStream_Call {
	_c.Call.Return(streamOwnerResponse, err)
	return _c
}

func (_c *MockService_StartStream_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, title string) (*dto.StreamOwnerResponse, error)) *MockService_StartStream_Call {
	_c.Call.Return(run)
	return _c
}

// StopStream provides a mock function for the type MockService
func (_mock *MockService) StopStream(ctx context.Context, userID uuid.UUID, streamID uuid.UUID) error {
	ret := _mock.Called(ctx, userID, streamID)

	if len(ret) == 0 {
		panic("no return value specified for StopStream")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID, streamID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_StopStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopStream'
type MockService_StopStream_Call struct {
	*mock.Call
}

// StopStream is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - streamID uuid.UUID
func (_e *MockService_Expecter) StopStream(ctx interface{}, userID interface{}, streamID interface{}) *MockService_StopStream_Call {
	return &MockService_StopStream_Call{Call: _e.mock.On("StopStream", ctx, userID, streamID)}
}

func (_c *MockService_StopStream_Call) Run(run func(ctx context.Context, userID uuid.UUID, streamID uuid.UUID)) *MockService_StopStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_StopStream_Call) Return(err error) *MockService_StopStream_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_StopStream_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, streamID uuid.UUID) error) *MockService_StopStream_Call {
	_c.Call.Return(run)
	return _c
}
