// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package giphy

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Enabled provides a mock function for the type MockService
func (_mock *MockService) Enabled() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Enabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockService_Enabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enabled'
type MockService_Enabled_Call struct {
	*mock.Call
}

// Enabled is a helper method to define mock.On call
func (_e *MockService_Expecter) Enabled() *MockService_Enabled_Call {
	return &MockService_Enabled_Call{Call: _e.mock.On("Enabled")}
}

func (_c *MockService_Enabled_Call) Run(run func()) *MockService_Enabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Enabled_Call) Return(b bool) *MockService_Enabled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockService_Enabled_Call) RunAndReturn(run func() bool) *MockService_Enabled_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockService
func (_mock *MockService) Search(ctx context.Context, q string, offset int, limit int) (*Response, error) {
	ret := _mock.Called(ctx, q, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) (*Response, error)); ok {
		return returnFunc(ctx, q, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) *Response); ok {
		r0 = returnFunc(ctx, q, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, q, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockService_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - q string
//   - offset int
//   - limit int
func (_e *MockService_Expecter) Search(ctx interface{}, q interface{}, offset interface{}, limit interface{}) *MockService_Search_Call {
	return &MockService_Search_Call{Call: _e.mock.On("Search", ctx, q, offset, limit)}
}

func (_c *MockService_Search_Call) Run(run func(ctx context.Context, q string, offset int, limit int)) *MockService_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_Search_Call) Return(response *Response, err error) *MockService_Search_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockService_Search_Call) RunAndReturn(run func(ctx context.Context, q string, offset int, limit int) (*Response, error)) *MockService_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Trending provides a mock function for the type MockService
func (_mock *MockService) Trending(ctx context.Context, offset int, limit int) (*Response, error) {
	ret := _mock.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for Trending")
	}

	var r0 *Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (*Response, error)); ok {
		return returnFunc(ctx, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) *Response); ok {
		r0 = returnFunc(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Trending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Trending'
type MockService_Trending_Call struct {
	*mock.Call
}

// Trending is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
func (_e *MockService_Expecter) Trending(ctx interface{}, offset interface{}, limit interface{}) *MockService_Trending_Call {
	return &MockService_Trending_Call{Call: _e.mock.On("Trending", ctx, offset, limit)}
}

func (_c *MockService_Trending_Call) Run(run func(ctx context.Context, offset int, limit int)) *MockService_Trending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Trending_Call) Return(response *Response, err error) *MockService_Trending_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockService_Trending_Call) RunAndReturn(run func(ctx context.Context, offset int, limit int) (*Response, error)) *MockService_Trending_Call {
	_c.Call.Return(run)
	return _c
}
