// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package media

import (
	"context"
	"io"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// newMockuploadSvc creates a new instance of mockuploadSvc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockuploadSvc(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockuploadSvc {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockuploadSvc{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockuploadSvc is an autogenerated mock type for the uploadSvc type
type mockuploadSvc struct {
	mock.Mock
}

type mockuploadSvc_Expecter struct {
	mock *mock.Mock
}

func (_m *mockuploadSvc) EXPECT() *mockuploadSvc_Expecter {
	return &mockuploadSvc_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type mockuploadSvc
func (_mock *mockuploadSvc) Delete(urlPaths ...string) {
	if len(urlPaths) > 0 {
		_mock.Called(urlPaths)
	} else {
		_mock.Called()
	}

	return
}

// mockuploadSvc_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockuploadSvc_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - urlPaths ...string
func (_e *mockuploadSvc_Expecter) Delete(urlPaths ...any) *mockuploadSvc_Delete_Call {
	return &mockuploadSvc_Delete_Call{Call: _e.mock.On("Delete",
		append([]any{}, urlPaths...)...)}
}

func (_c *mockuploadSvc_Delete_Call) Run(run func(urlPaths ...string)) *mockuploadSvc_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		var variadicArgs []string
		if len(args) > 0 {
			variadicArgs = args[0].([]string)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *mockuploadSvc_Delete_Call) Return() *mockuploadSvc_Delete_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockuploadSvc_Delete_Call) RunAndReturn(run func(urlPaths ...string)) *mockuploadSvc_Delete_Call {
	_c.Run(run)
	return _c
}

// Discard provides a mock function for the type mockuploadSvc
func (_mock *mockuploadSvc) Discard(localPath string) {
	_mock.Called(localPath)
	return
}

// mockuploadSvc_Discard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Discard'
type mockuploadSvc_Discard_Call struct {
	*mock.Call
}

// Discard is a helper method to define mock.On call
//   - localPath string
func (_e *mockuploadSvc_Expecter) Discard(localPath any) *mockuploadSvc_Discard_Call {
	return &mockuploadSvc_Discard_Call{Call: _e.mock.On("Discard", localPath)}
}

func (_c *mockuploadSvc_Discard_Call) Run(run func(localPath string)) *mockuploadSvc_Discard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockuploadSvc_Discard_Call) Return() *mockuploadSvc_Discard_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockuploadSvc_Discard_Call) RunAndReturn(run func(localPath string)) *mockuploadSvc_Discard_Call {
	_c.Run(run)
	return _c
}

// SaveAudio provides a mock function for the type mockuploadSvc
func (_mock *mockuploadSvc) SaveAudio(ctx context.Context, subDir string, id uuid.UUID, fileSize int64, maxSize int64, reader io.Reader) (string, error) {
	ret := _mock.Called(ctx, subDir, id, fileSize, maxSize, reader)

	if len(ret) == 0 {
		panic("no return value specified for SaveAudio")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, int64, int64, io.Reader) (string, error)); ok {
		return returnFunc(ctx, subDir, id, fileSize, maxSize, reader)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, int64, int64, io.Reader) string); ok {
		r0 = returnFunc(ctx, subDir, id, fileSize, maxSize, reader)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uuid.UUID, int64, int64, io.Reader) error); ok {
		r1 = returnFunc(ctx, subDir, id, fileSize, maxSize, reader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuploadSvc_SaveAudio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAudio'
type mockuploadSvc_SaveAudio_Call struct {
	*mock.Call
}

// SaveAudio is a helper method to define mock.On call
//   - ctx context.Context
//   - subDir string
//   - id uuid.UUID
//   - fileSize int64
//   - maxSize int64
//   - reader io.Reader
func (_e *mockuploadSvc_Expecter) SaveAudio(ctx any, subDir any, id any, fileSize any, maxSize any, reader any) *mockuploadSvc_SaveAudio_Call {
	return &mockuploadSvc_SaveAudio_Call{Call: _e.mock.On("SaveAudio", ctx, subDir, id, fileSize, maxSize, reader)}
}

func (_c *mockuploadSvc_SaveAudio_Call) Run(run func(ctx context.Context, subDir string, id uuid.UUID, fileSize int64, maxSize int64, reader io.Reader)) *mockuploadSvc_SaveAudio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 io.Reader
		if args[5] != nil {
			arg5 = args[5].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *mockuploadSvc_SaveAudio_Call) Return(s string, err error) *mockuploadSvc_SaveAudio_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockuploadSvc_SaveAudio_Call) RunAndReturn(run func(ctx context.Context, subDir string, id uuid.UUID, fileSize int64, maxSize int64, reader io.Reader) (string, error)) *mockuploadSvc_SaveAudio_Call {
	_c.Call.Return(run)
	return _c
}

// SaveImage provides a mock function for the type mockuploadSvc
func (_mock *mockuploadSvc) SaveImage(ctx context.Context, subDir string, id uuid.UUID, fileSize int64, maxSize int64, reader io.Reader) (string, error) {
	ret := _mock.Called(ctx, subDir, id, fileSize, maxSize, reader)

	if len(ret) == 0 {
		panic("no return value specified for SaveImage")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, int64, int64, io.Reader) (string, error)); ok {
		return returnFunc(ctx, subDir, id, fileSize, maxSize, reader)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, int64, int64, io.Reader) string); ok {
		r0 = returnFunc(ctx, subDir, id, fileSize, maxSize, reader)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uuid.UUID, int64, int64, io.Reader) error); ok {
		r1 = returnFunc(ctx, subDir, id, fileSize, maxSize, reader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuploadSvc_SaveImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveImage'
type mockuploadSvc_SaveImage_Call struct {
	*mock.Call
}

// SaveImage is a helper method to define mock.On call
//   - ctx context.Context
//   - subDir string
//   - id uuid.UUID
//   - fileSize int64
//   - maxSize int64
//   - reader io.Reader
func (_e *mockuploadSvc_Expecter) SaveImage(ctx any, subDir any, id any, fileSize any, maxSize any, reader any) *mockuploadSvc_SaveImage_Call {
	return &mockuploadSvc_SaveImage_Call{Call: _e.mock.On("SaveImage", ctx, subDir, id, fileSize, maxSize, reader)}
}

func (_c *mockuploadSvc_SaveImage_Call) Run(run func(ctx context.Context, subDir string, id uuid.UUID, fileSize int64, maxSize int64, reader io.Reader)) *mockuploadSvc_SaveImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 io.Reader
		if args[5] != nil {
			arg5 = args[5].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *mockuploadSvc_SaveImage_Call) Return(s string, err error) *mockuploadSvc_SaveImage_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockuploadSvc_SaveImage_Call) RunAndReturn(run func(ctx context.Context, subDir string, id uuid.UUID, fileSize int64, maxSize int64, reader io.Reader) (string, error)) *mockuploadSvc_SaveImage_Call {
	_c.Call.Return(run)
	return _c
}

// StageMedia provides a mock function for the type mockuploadSvc
func (_mock *mockuploadSvc) StageMedia(ctx context.Context, mediaType string, subDir string, id uuid.UUID, fileSize int64, maxSize int64, reader io.Reader) (string, error) {
	ret := _mock.Called(ctx, mediaType, subDir, id, fileSize, maxSize, reader)

	if len(ret) == 0 {
		panic("no return value specified for StageMedia")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, uuid.UUID, int64, int64, io.Reader) (string, error)); ok {
		return returnFunc(ctx, mediaType, subDir, id, fileSize, maxSize, reader)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, uuid.UUID, int64, int64, io.Reader) string); ok {
		r0 = returnFunc(ctx, mediaType, subDir, id, fileSize, maxSize, reader)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, uuid.UUID, int64, int64, io.Reader) error); ok {
		r1 = returnFunc(ctx, mediaType, subDir, id, fileSize, maxSize, reader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuploadSvc_StageMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StageMedia'
type mockuploadSvc_StageMedia_Call struct {
	*mock.Call
}

// StageMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - mediaType string
//   - subDir string
//   - id uuid.UUID
//   - fileSize int64
//   - maxSize int64
//   - reader io.Reader
func (_e *mockuploadSvc_Expecter) StageMedia(ctx any, mediaType any, subDir any, id any, fileSize any, maxSize any, reader any) *mockuploadSvc_StageMedia_Call {
	return &mockuploadSvc_StageMedia_Call{Call: _e.mock.On("StageMedia", ctx, mediaType, subDir, id, fileSize, maxSize, reader)}
}

func (_c *mockuploadSvc_StageMedia_Call) Run(run func(ctx context.Context, mediaType string, subDir string, id uuid.UUID, fileSize int64, maxSize int64, reader io.Reader)) *mockuploadSvc_StageMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 int64
		if args[5] != nil {
			arg5 = args[5].(int64)
		}
		var arg6 io.Reader
		if args[6] != nil {
			arg6 = args[6].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *mockuploadSvc_StageMedia_Call) Return(s string, err error) *mockuploadSvc_StageMedia_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockuploadSvc_StageMedia_Call) RunAndReturn(run func(ctx context.Context, mediaType string, subDir string, id uuid.UUID, fileSize int64, maxSize int64, reader io.Reader) (string, error)) *mockuploadSvc_StageMedia_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function for the type mockuploadSvc
func (_mock *mockuploadSvc) Store(ctx context.Context, subDir string, localPath string) (string, error) {
	ret := _mock.Called(ctx, subDir, localPath)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, subDir, localPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, subDir, localPath)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, subDir, localPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuploadSvc_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type mockuploadSvc_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - subDir string
//   - localPath string
func (_e *mockuploadSvc_Expecter) Store(ctx any, subDir any, localPath any) *mockuploadSvc_Store_Call {
	return &mockuploadSvc_Store_Call{Call: _e.mock.On("Store", ctx, subDir, localPath)}
}

func (_c *mockuploadSvc_Store_Call) Run(run func(ctx context.Context, subDir string, localPath string)) *mockuploadSvc_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockuploadSvc_Store_Call) Return(s string, err error) *mockuploadSvc_Store_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockuploadSvc_Store_Call) RunAndReturn(run func(ctx context.Context, subDir string, localPath string) (string, error)) *mockuploadSvc_Store_Call {
	_c.Call.Return(run)
	return _c
}
