services:
  umineko-city-of-books:
    image: ghcr.io/victoriquemoe/umineko_city_of_books:latest
    container_name: umineko-city-of-books
    restart: unless-stopped
    ports:
      - "4323:4323"
    environment:
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./truths.db:/app/truths.db
