// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package engine

import (
	"context"
	"io"
	"iter"
	"umineko_city_of_books/internal/config"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEngine creates a new instance of MockEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEngine(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEngine {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockEngine is an autogenerated mock type for the Engine type
type MockEngine struct {
	mock.Mock
}

type MockEngine_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEngine) EXPECT() *MockEngine_Expecter {
	return &MockEngine_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockEngine
func (_mock *MockEngine) Delete(ctx context.Context, locations ...string) error {
	var tmpRet mock.Arguments
	if len(locations) > 0 {
		tmpRet = _mock.Called(ctx, locations)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = returnFunc(ctx, locations...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEngine_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockEngine_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - locations ...string
func (_e *MockEngine_Expecter) Delete(ctx any, locations ...any) *MockEngine_Delete_Call {
	return &MockEngine_Delete_Call{Call: _e.mock.On("Delete",
		append([]any{ctx}, locations...)...)}
}

func (_c *MockEngine_Delete_Call) Run(run func(ctx context.Context, locations ...string)) *MockEngine_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockEngine_Delete_Call) Return(err error) *MockEngine_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEngine_Delete_Call) RunAndReturn(run func(ctx context.Context, locations ...string) error) *MockEngine_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Enabled provides a mock function for the type MockEngine
func (_mock *MockEngine) Enabled() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Enabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockEngine_Enabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enabled'
type MockEngine_Enabled_Call struct {
	*mock.Call
}

// Enabled is a helper method to define mock.On call
func (_e *MockEngine_Expecter) Enabled() *MockEngine_Enabled_Call {
	return &MockEngine_Enabled_Call{Call: _e.mock.On("Enabled")}
}

func (_c *MockEngine_Enabled_Call) Run(run func()) *MockEngine_Enabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEngine_Enabled_Call) Return(b bool) *MockEngine_Enabled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockEngine_Enabled_Call) RunAndReturn(run func() bool) *MockEngine_Enabled_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockEngine
func (_mock *MockEngine) Get(ctx context.Context, location string, rng *ByteRange) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, location, rng)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *ByteRange) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, location, rng)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *ByteRange) io.ReadCloser); ok {
		r0 = returnFunc(ctx, location, rng)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *ByteRange) error); ok {
		r1 = returnFunc(ctx, location, rng)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEngine_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockEngine_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - location string
//   - rng *ByteRange
func (_e *MockEngine_Expecter) Get(ctx any, location any, rng any) *MockEngine_Get_Call {
	return &MockEngine_Get_Call{Call: _e.mock.On("Get", ctx, location, rng)}
}

func (_c *MockEngine_Get_Call) Run(run func(ctx context.Context, location string, rng *ByteRange)) *MockEngine_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *ByteRange
		if args[2] != nil {
			arg2 = args[2].(*ByteRange)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEngine_Get_Call) Return(readCloser io.ReadCloser, err error) *MockEngine_Get_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockEngine_Get_Call) RunAndReturn(run func(ctx context.Context, location string, rng *ByteRange) (io.ReadCloser, error)) *MockEngine_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Head provides a mock function for the type MockEngine
func (_mock *MockEngine) Head(ctx context.Context, location string) (ObjectInfo, error) {
	ret := _mock.Called(ctx, location)

	if len(ret) == 0 {
		panic("no return value specified for Head")
	}

	var r0 ObjectInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (ObjectInfo, error)); ok {
		return returnFunc(ctx, location)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ObjectInfo); ok {
		r0 = returnFunc(ctx, location)
	} else {
		r0 = ret.Get(0).(ObjectInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, location)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEngine_Head_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Head'
type MockEngine_Head_Call struct {
	*mock.Call
}

// Head is a helper method to define mock.On call
//   - ctx context.Context
//   - location string
func (_e *MockEngine_Expecter) Head(ctx any, location any) *MockEngine_Head_Call {
	return &MockEngine_Head_Call{Call: _e.mock.On("Head", ctx, location)}
}

func (_c *MockEngine_Head_Call) Run(run func(ctx context.Context, location string)) *MockEngine_Head_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEngine_Head_Call) Return(objectInfo ObjectInfo, err error) *MockEngine_Head_Call {
	_c.Call.Return(objectInfo, err)
	return _c
}

func (_c *MockEngine_Head_Call) RunAndReturn(run func(ctx context.Context, location string) (ObjectInfo, error)) *MockEngine_Head_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockEngine
func (_mock *MockEngine) ID() config.StorageBackend {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 config.StorageBackend
	if returnFunc, ok := ret.Get(0).(func() config.StorageBackend); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(config.StorageBackend)
	}
	return r0
}

// MockEngine_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockEngine_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockEngine_Expecter) ID() *MockEngine_ID_Call {
	return &MockEngine_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockEngine_ID_Call) Run(run func()) *MockEngine_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEngine_ID_Call) Return(storageBackend config.StorageBackend) *MockEngine_ID_Call {
	_c.Call.Return(storageBackend)
	return _c
}

func (_c *MockEngine_ID_Call) RunAndReturn(run func() config.StorageBackend) *MockEngine_ID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockEngine
func (_mock *MockEngine) List(ctx context.Context, prefix string) iter.Seq2[ObjectInfo, error] {
	ret := _mock.Called(ctx, prefix)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 iter.Seq2[ObjectInfo, error]
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) iter.Seq2[ObjectInfo, error]); ok {
		r0 = returnFunc(ctx, prefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq2[ObjectInfo, error])
		}
	}
	return r0
}

// MockEngine_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockEngine_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
func (_e *MockEngine_Expecter) List(ctx any, prefix any) *MockEngine_List_Call {
	return &MockEngine_List_Call{Call: _e.mock.On("List", ctx, prefix)}
}

func (_c *MockEngine_List_Call) Run(run func(ctx context.Context, prefix string)) *MockEngine_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEngine_List_Call) Return(seq2 iter.Seq2[ObjectInfo, error]) *MockEngine_List_Call {
	_c.Call.Return(seq2)
	return _c
}

func (_c *MockEngine_List_Call) RunAndReturn(run func(ctx context.Context, prefix string) iter.Seq2[ObjectInfo, error]) *MockEngine_List_Call {
	_c.Call.Return(run)
	return _c
}

// PutFile provides a mock function for the type MockEngine
func (_mock *MockEngine) PutFile(ctx context.Context, key string, localPath string) (string, error) {
	ret := _mock.Called(ctx, key, localPath)

	if len(ret) == 0 {
		panic("no return value specified for PutFile")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, key, localPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, key, localPath)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, key, localPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEngine_PutFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutFile'
type MockEngine_PutFile_Call struct {
	*mock.Call
}

// PutFile is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - localPath string
func (_e *MockEngine_Expecter) PutFile(ctx any, key any, localPath any) *MockEngine_PutFile_Call {
	return &MockEngine_PutFile_Call{Call: _e.mock.On("PutFile", ctx, key, localPath)}
}

func (_c *MockEngine_PutFile_Call) Run(run func(ctx context.Context, key string, localPath string)) *MockEngine_PutFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEngine_PutFile_Call) Return(s string, err error) *MockEngine_PutFile_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockEngine_PutFile_Call) RunAndReturn(run func(ctx context.Context, key string, localPath string) (string, error)) *MockEngine_PutFile_Call {
	_c.Call.Return(run)
	return _c
}
