// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package favourite

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockService
func (_mock *MockService) Add(ctx context.Context, userID uuid.UUID, fav Favourite) error {
	ret := _mock.Called(ctx, userID, fav)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, Favourite) error); ok {
		r0 = returnFunc(ctx, userID, fav)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockService_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - fav Favourite
func (_e *MockService_Expecter) Add(ctx interface{}, userID interface{}, fav interface{}) *MockService_Add_Call {
	return &MockService_Add_Call{Call: _e.mock.On("Add", ctx, userID, fav)}
}

func (_c *MockService_Add_Call) Run(run func(ctx context.Context, userID uuid.UUID, fav Favourite)) *MockService_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 Favourite
		if args[2] != nil {
			arg2 = args[2].(Favourite)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Add_Call) Return(err error) *MockService_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Add_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, fav Favourite) error) *MockService_Add_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockService
func (_mock *MockService) List(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]Favourite, int, error) {
	ret := _mock.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []Favourite
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]Favourite, int, error)); ok {
		return returnFunc(ctx, userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []Favourite); ok {
		r0 = returnFunc(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Favourite)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = returnFunc(ctx, userID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = returnFunc(ctx, userID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockService_Expecter) List(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockService_List_Call {
	return &MockService_List_Call{Call: _e.mock.On("List", ctx, userID, limit, offset)}
}

func (_c *MockService_List_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int, offset int)) *MockService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_List_Call) Return(favourites []Favourite, n int, err error) *MockService_List_Call {
	_c.Call.Return(favourites, n, err)
	return _c
}

func (_c *MockService_List_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, limit int, offset int) ([]Favourite, int, error)) *MockService_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListIDs provides a mock function for the type MockService
func (_mock *MockService) ListIDs(ctx context.Context, userID uuid.UUID) ([]string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListIDs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIDs'
type MockService_ListIDs_Call struct {
	*mock.Call
}

// ListIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockService_Expecter) ListIDs(ctx interface{}, userID interface{}) *MockService_ListIDs_Call {
	return &MockService_ListIDs_Call{Call: _e.mock.On("ListIDs", ctx, userID)}
}

func (_c *MockService_ListIDs_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockService_ListIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ListIDs_Call) Return(strings []string, err error) *MockService_ListIDs_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockService_ListIDs_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]string, error)) *MockService_ListIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockService
func (_mock *MockService) Remove(ctx context.Context, userID uuid.UUID, giphyID string) error {
	ret := _mock.Called(ctx, userID, giphyID)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, userID, giphyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockService_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - giphyID string
func (_e *MockService_Expecter) Remove(ctx interface{}, userID interface{}, giphyID interface{}) *MockService_Remove_Call {
	return &MockService_Remove_Call{Call: _e.mock.On("Remove", ctx, userID, giphyID)}
}

func (_c *MockService_Remove_Call) Run(run func(ctx context.Context, userID uuid.UUID, giphyID string)) *MockService_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Remove_Call) Return(err error) *MockService_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Remove_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, giphyID string) error) *MockService_Remove_Call {
	_c.Call.Return(run)
	return _c
}
