// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storage

import (
	"context"
	"io"
	"umineko_city_of_books/internal/storage/engine"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// BackfillLocal provides a mock function for the type MockService
func (_mock *MockService) BackfillLocal(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BackfillLocal")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_BackfillLocal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BackfillLocal'
type MockService_BackfillLocal_Call struct {
	*mock.Call
}

// BackfillLocal is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) BackfillLocal(ctx any) *MockService_BackfillLocal_Call {
	return &MockService_BackfillLocal_Call{Call: _e.mock.On("BackfillLocal", ctx)}
}

func (_c *MockService_BackfillLocal_Call) Run(run func(ctx context.Context)) *MockService_BackfillLocal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_BackfillLocal_Call) Return(n int, err error) *MockService_BackfillLocal_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockService_BackfillLocal_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *MockService_BackfillLocal_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockService
func (_mock *MockService) Delete(ctx context.Context, keys ...string) error {
	var tmpRet mock.Arguments
	if len(keys) > 0 {
		tmpRet = _mock.Called(ctx, keys)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = returnFunc(ctx, keys...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...string
func (_e *MockService_Expecter) Delete(ctx any, keys ...any) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete",
		append([]any{ctx}, keys...)...)}
}

func (_c *MockService_Delete_Call) Run(run func(ctx context.Context, keys ...string)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(err error) *MockService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(ctx context.Context, keys ...string) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Fetch provides a mock function for the type MockService
func (_mock *MockService) Fetch(ctx context.Context, info engine.ObjectInfo, localPath string) error {
	ret := _mock.Called(ctx, info, localPath)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, engine.ObjectInfo, string) error); ok {
		r0 = returnFunc(ctx, info, localPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockService_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - info engine.ObjectInfo
//   - localPath string
func (_e *MockService_Expecter) Fetch(ctx any, info any, localPath any) *MockService_Fetch_Call {
	return &MockService_Fetch_Call{Call: _e.mock.On("Fetch", ctx, info, localPath)}
}

func (_c *MockService_Fetch_Call) Run(run func(ctx context.Context, info engine.ObjectInfo, localPath string)) *MockService_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 engine.ObjectInfo
		if args[1] != nil {
			arg1 = args[1].(engine.ObjectInfo)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Fetch_Call) Return(err error) *MockService_Fetch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Fetch_Call) RunAndReturn(run func(ctx context.Context, info engine.ObjectInfo, localPath string) error) *MockService_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type MockService
func (_mock *MockService) Open(ctx context.Context, info engine.ObjectInfo, rng *engine.ByteRange) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, info, rng)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, engine.ObjectInfo, *engine.ByteRange) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, info, rng)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, engine.ObjectInfo, *engine.ByteRange) io.ReadCloser); ok {
		r0 = returnFunc(ctx, info, rng)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, engine.ObjectInfo, *engine.ByteRange) error); ok {
		r1 = returnFunc(ctx, info, rng)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockService_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - ctx context.Context
//   - info engine.ObjectInfo
//   - rng *engine.ByteRange
func (_e *MockService_Expecter) Open(ctx any, info any, rng any) *MockService_Open_Call {
	return &MockService_Open_Call{Call: _e.mock.On("Open", ctx, info, rng)}
}

func (_c *MockService_Open_Call) Run(run func(ctx context.Context, info engine.ObjectInfo, rng *engine.ByteRange)) *MockService_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 engine.ObjectInfo
		if args[1] != nil {
			arg1 = args[1].(engine.ObjectInfo)
		}
		var arg2 *engine.ByteRange
		if args[2] != nil {
			arg2 = args[2].(*engine.ByteRange)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Open_Call) Return(readCloser io.ReadCloser, err error) *MockService_Open_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockService_Open_Call) RunAndReturn(run func(ctx context.Context, info engine.ObjectInfo, rng *engine.ByteRange) (io.ReadCloser, error)) *MockService_Open_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type MockService
func (_mock *MockService) Stat(ctx context.Context, key string) (engine.ObjectInfo, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 engine.ObjectInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (engine.ObjectInfo, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) engine.ObjectInfo); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(engine.ObjectInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockService_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockService_Expecter) Stat(ctx any, key any) *MockService_Stat_Call {
	return &MockService_Stat_Call{Call: _e.mock.On("Stat", ctx, key)}
}

func (_c *MockService_Stat_Call) Run(run func(ctx context.Context, key string)) *MockService_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Stat_Call) Return(objectInfo engine.ObjectInfo, err error) *MockService_Stat_Call {
	_c.Call.Return(objectInfo, err)
	return _c
}

func (_c *MockService_Stat_Call) RunAndReturn(run func(ctx context.Context, key string) (engine.ObjectInfo, error)) *MockService_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function for the type MockService
func (_mock *MockService) Store(ctx context.Context, key string, localPath string) error {
	ret := _mock.Called(ctx, key, localPath)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, key, localPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockService_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - localPath string
func (_e *MockService_Expecter) Store(ctx any, key any, localPath any) *MockService_Store_Call {
	return &MockService_Store_Call{Call: _e.mock.On("Store", ctx, key, localPath)}
}

func (_c *MockService_Store_Call) Run(run func(ctx context.Context, key string, localPath string)) *MockService_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Store_Call) Return(err error) *MockService_Store_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Store_Call) RunAndReturn(run func(ctx context.Context, key string, localPath string) error) *MockService_Store_Call {
	_c.Call.Return(run)
	return _c
}
