// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sitemap

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Art provides a mock function for the type MockService
func (_mock *MockService) Art(ctx context.Context) ([]Entry, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Art")
	}

	var r0 []Entry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]Entry, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []Entry); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Entry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Art_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Art'
type MockService_Art_Call struct {
	*mock.Call
}

// Art is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Art(ctx any) *MockService_Art_Call {
	return &MockService_Art_Call{Call: _e.mock.On("Art", ctx)}
}

func (_c *MockService_Art_Call) Run(run func(ctx context.Context)) *MockService_Art_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Art_Call) Return(entrys []Entry, err error) *MockService_Art_Call {
	_c.Call.Return(entrys, err)
	return _c
}

func (_c *MockService_Art_Call) RunAndReturn(run func(ctx context.Context) ([]Entry, error)) *MockService_Art_Call {
	_c.Call.Return(run)
	return _c
}

// BaseURL provides a mock function for the type MockService
func (_mock *MockService) BaseURL() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BaseURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockService_BaseURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BaseURL'
type MockService_BaseURL_Call struct {
	*mock.Call
}

// BaseURL is a helper method to define mock.On call
func (_e *MockService_Expecter) BaseURL() *MockService_BaseURL_Call {
	return &MockService_BaseURL_Call{Call: _e.mock.On("BaseURL")}
}

func (_c *MockService_BaseURL_Call) Run(run func()) *MockService_BaseURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_BaseURL_Call) Return(s string) *MockService_BaseURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockService_BaseURL_Call) RunAndReturn(run func() string) *MockService_BaseURL_Call {
	_c.Call.Return(run)
	return _c
}

// Fanfics provides a mock function for the type MockService
func (_mock *MockService) Fanfics(ctx context.Context) ([]Entry, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Fanfics")
	}

	var r0 []Entry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]Entry, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []Entry); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Entry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Fanfics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fanfics'
type MockService_Fanfics_Call struct {
	*mock.Call
}

// Fanfics is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Fanfics(ctx any) *MockService_Fanfics_Call {
	return &MockService_Fanfics_Call{Call: _e.mock.On("Fanfics", ctx)}
}

func (_c *MockService_Fanfics_Call) Run(run func(ctx context.Context)) *MockService_Fanfics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Fanfics_Call) Return(entrys []Entry, err error) *MockService_Fanfics_Call {
	_c.Call.Return(entrys, err)
	return _c
}

func (_c *MockService_Fanfics_Call) RunAndReturn(run func(ctx context.Context) ([]Entry, error)) *MockService_Fanfics_Call {
	_c.Call.Return(run)
	return _c
}

// IndexEntries provides a mock function for the type MockService
func (_mock *MockService) IndexEntries() []IndexEntry {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IndexEntries")
	}

	var r0 []IndexEntry
	if returnFunc, ok := ret.Get(0).(func() []IndexEntry); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]IndexEntry)
		}
	}
	return r0
}

// MockService_IndexEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexEntries'
type MockService_IndexEntries_Call struct {
	*mock.Call
}

// IndexEntries is a helper method to define mock.On call
func (_e *MockService_Expecter) IndexEntries() *MockService_IndexEntries_Call {
	return &MockService_IndexEntries_Call{Call: _e.mock.On("IndexEntries")}
}

func (_c *MockService_IndexEntries_Call) Run(run func()) *MockService_IndexEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_IndexEntries_Call) Return(indexEntrys []IndexEntry) *MockService_IndexEntries_Call {
	_c.Call.Return(indexEntrys)
	return _c
}

func (_c *MockService_IndexEntries_Call) RunAndReturn(run func() []IndexEntry) *MockService_IndexEntries_Call {
	_c.Call.Return(run)
	return _c
}

// Journals provides a mock function for the type MockService
func (_mock *MockService) Journals(ctx context.Context) ([]Entry, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Journals")
	}

	var r0 []Entry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]Entry, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []Entry); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Entry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Journals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Journals'
type MockService_Journals_Call struct {
	*mock.Call
}

// Journals is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Journals(ctx any) *MockService_Journals_Call {
	return &MockService_Journals_Call{Call: _e.mock.On("Journals", ctx)}
}

func (_c *MockService_Journals_Call) Run(run func(ctx context.Context)) *MockService_Journals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Journals_Call) Return(entrys []Entry, err error) *MockService_Journals_Call {
	_c.Call.Return(entrys, err)
	return _c
}

func (_c *MockService_Journals_Call) RunAndReturn(run func(ctx context.Context) ([]Entry, error)) *MockService_Journals_Call {
	_c.Call.Return(run)
	return _c
}

// Mysteries provides a mock function for the type MockService
func (_mock *MockService) Mysteries(ctx context.Context) ([]Entry, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Mysteries")
	}

	var r0 []Entry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]Entry, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []Entry); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Entry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Mysteries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mysteries'
type MockService_Mysteries_Call struct {
	*mock.Call
}

// Mysteries is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Mysteries(ctx any) *MockService_Mysteries_Call {
	return &MockService_Mysteries_Call{Call: _e.mock.On("Mysteries", ctx)}
}

func (_c *MockService_Mysteries_Call) Run(run func(ctx context.Context)) *MockService_Mysteries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Mysteries_Call) Return(entrys []Entry, err error) *MockService_Mysteries_Call {
	_c.Call.Return(entrys, err)
	return _c
}

func (_c *MockService_Mysteries_Call) RunAndReturn(run func(ctx context.Context) ([]Entry, error)) *MockService_Mysteries_Call {
	_c.Call.Return(run)
	return _c
}

// Posts provides a mock function for the type MockService
func (_mock *MockService) Posts(ctx context.Context) ([]Entry, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Posts")
	}

	var r0 []Entry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]Entry, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []Entry); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Entry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Posts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Posts'
type MockService_Posts_Call struct {
	*mock.Call
}

// Posts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Posts(ctx any) *MockService_Posts_Call {
	return &MockService_Posts_Call{Call: _e.mock.On("Posts", ctx)}
}

func (_c *MockService_Posts_Call) Run(run func(ctx context.Context)) *MockService_Posts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Posts_Call) Return(entrys []Entry, err error) *MockService_Posts_Call {
	_c.Call.Return(entrys, err)
	return _c
}

func (_c *MockService_Posts_Call) RunAndReturn(run func(ctx context.Context) ([]Entry, error)) *MockService_Posts_Call {
	_c.Call.Return(run)
	return _c
}

// Ships provides a mock function for the type MockService
func (_mock *MockService) Ships(ctx context.Context) ([]Entry, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ships")
	}

	var r0 []Entry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]Entry, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []Entry); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Entry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Ships_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ships'
type MockService_Ships_Call struct {
	*mock.Call
}

// Ships is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Ships(ctx any) *MockService_Ships_Call {
	return &MockService_Ships_Call{Call: _e.mock.On("Ships", ctx)}
}

func (_c *MockService_Ships_Call) Run(run func(ctx context.Context)) *MockService_Ships_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Ships_Call) Return(entrys []Entry, err error) *MockService_Ships_Call {
	_c.Call.Return(entrys, err)
	return _c
}

func (_c *MockService_Ships_Call) RunAndReturn(run func(ctx context.Context) ([]Entry, error)) *MockService_Ships_Call {
	_c.Call.Return(run)
	return _c
}

// StaticEntries provides a mock function for the type MockService
func (_mock *MockService) StaticEntries(ctx context.Context) []Entry {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StaticEntries")
	}

	var r0 []Entry
	if returnFunc, ok := ret.Get(0).(func(context.Context) []Entry); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Entry)
		}
	}
	return r0
}

// MockService_StaticEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StaticEntries'
type MockService_StaticEntries_Call struct {
	*mock.Call
}

// StaticEntries is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) StaticEntries(ctx any) *MockService_StaticEntries_Call {
	return &MockService_StaticEntries_Call{Call: _e.mock.On("StaticEntries", ctx)}
}

func (_c *MockService_StaticEntries_Call) Run(run func(ctx context.Context)) *MockService_StaticEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_StaticEntries_Call) Return(entrys []Entry) *MockService_StaticEntries_Call {
	_c.Call.Return(entrys)
	return _c
}

func (_c *MockService_StaticEntries_Call) RunAndReturn(run func(ctx context.Context) []Entry) *MockService_StaticEntries_Call {
	_c.Call.Return(run)
	return _c
}

// Theories provides a mock function for the type MockService
func (_mock *MockService) Theories(ctx context.Context) ([]Entry, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Theories")
	}

	var r0 []Entry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]Entry, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []Entry); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Entry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Theories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Theories'
type MockService_Theories_Call struct {
	*mock.Call
}

// Theories is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Theories(ctx any) *MockService_Theories_Call {
	return &MockService_Theories_Call{Call: _e.mock.On("Theories", ctx)}
}

func (_c *MockService_Theories_Call) Run(run func(ctx context.Context)) *MockService_Theories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Theories_Call) Return(entrys []Entry, err error) *MockService_Theories_Call {
	_c.Call.Return(entrys, err)
	return _c
}

func (_c *MockService_Theories_Call) RunAndReturn(run func(ctx context.Context) ([]Entry, error)) *MockService_Theories_Call {
	_c.Call.Return(run)
	return _c
}

// Users provides a mock function for the type MockService
func (_mock *MockService) Users(ctx context.Context) ([]Entry, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Users")
	}

	var r0 []Entry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]Entry, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []Entry); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Entry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Users_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Users'
type MockService_Users_Call struct {
	*mock.Call
}

// Users is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Users(ctx any) *MockService_Users_Call {
	return &MockService_Users_Call{Call: _e.mock.On("Users", ctx)}
}

func (_c *MockService_Users_Call) Run(run func(ctx context.Context)) *MockService_Users_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Users_Call) Return(entrys []Entry, err error) *MockService_Users_Call {
	_c.Call.Return(entrys, err)
	return _c
}

func (_c *MockService_Users_Call) RunAndReturn(run func(ctx context.Context) ([]Entry, error)) *MockService_Users_Call {
	_c.Call.Return(run)
	return _c
}
