// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package chatbot

import (
	"context"
	"time"
	"umineko_city_of_books/internal/dto"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAdminService creates a new instance of MockAdminService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAdminService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAdminService is an autogenerated mock type for the AdminService type
type MockAdminService struct {
	mock.Mock
}

type MockAdminService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminService) EXPECT() *MockAdminService_Expecter {
	return &MockAdminService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAdminService
func (_mock *MockAdminService) Create(ctx context.Context, actorID uuid.UUID, req dto.ChatbotUpsertRequest) (*dto.ChatbotResponse, error) {
	ret := _mock.Called(ctx, actorID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.ChatbotResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.ChatbotUpsertRequest) (*dto.ChatbotResponse, error)); ok {
		return returnFunc(ctx, actorID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.ChatbotUpsertRequest) *dto.ChatbotResponse); ok {
		r0 = returnFunc(ctx, actorID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ChatbotResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.ChatbotUpsertRequest) error); ok {
		r1 = returnFunc(ctx, actorID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAdminService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID uuid.UUID
//   - req dto.ChatbotUpsertRequest
func (_e *MockAdminService_Expecter) Create(ctx any, actorID any, req any) *MockAdminService_Create_Call {
	return &MockAdminService_Create_Call{Call: _e.mock.On("Create", ctx, actorID, req)}
}

func (_c *MockAdminService_Create_Call) Run(run func(ctx context.Context, actorID uuid.UUID, req dto.ChatbotUpsertRequest)) *MockAdminService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 dto.ChatbotUpsertRequest
		if args[2] != nil {
			arg2 = args[2].(dto.ChatbotUpsertRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdminService_Create_Call) Return(chatbotResponse *dto.ChatbotResponse, err error) *MockAdminService_Create_Call {
	_c.Call.Return(chatbotResponse, err)
	return _c
}

func (_c *MockAdminService_Create_Call) RunAndReturn(run func(ctx context.Context, actorID uuid.UUID, req dto.ChatbotUpsertRequest) (*dto.ChatbotResponse, error)) *MockAdminService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBasePrompt provides a mock function for the type MockAdminService
func (_mock *MockAdminService) CreateBasePrompt(ctx context.Context, actorID uuid.UUID, req dto.ChatbotBasePromptUpsertRequest) (*dto.ChatbotBasePromptResponse, error) {
	ret := _mock.Called(ctx, actorID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateBasePrompt")
	}

	var r0 *dto.ChatbotBasePromptResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.ChatbotBasePromptUpsertRequest) (*dto.ChatbotBasePromptResponse, error)); ok {
		return returnFunc(ctx, actorID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.ChatbotBasePromptUpsertRequest) *dto.ChatbotBasePromptResponse); ok {
		r0 = returnFunc(ctx, actorID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ChatbotBasePromptResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.ChatbotBasePromptUpsertRequest) error); ok {
		r1 = returnFunc(ctx, actorID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminService_CreateBasePrompt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBasePrompt'
type MockAdminService_CreateBasePrompt_Call struct {
	*mock.Call
}

// CreateBasePrompt is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID uuid.UUID
//   - req dto.ChatbotBasePromptUpsertRequest
func (_e *MockAdminService_Expecter) CreateBasePrompt(ctx any, actorID any, req any) *MockAdminService_CreateBasePrompt_Call {
	return &MockAdminService_CreateBasePrompt_Call{Call: _e.mock.On("CreateBasePrompt", ctx, actorID, req)}
}

func (_c *MockAdminService_CreateBasePrompt_Call) Run(run func(ctx context.Context, actorID uuid.UUID, req dto.ChatbotBasePromptUpsertRequest)) *MockAdminService_CreateBasePrompt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 dto.ChatbotBasePromptUpsertRequest
		if args[2] != nil {
			arg2 = args[2].(dto.ChatbotBasePromptUpsertRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdminService_CreateBasePrompt_Call) Return(chatbotBasePromptResponse *dto.ChatbotBasePromptResponse, err error) *MockAdminService_CreateBasePrompt_Call {
	_c.Call.Return(chatbotBasePromptResponse, err)
	return _c
}

func (_c *MockAdminService_CreateBasePrompt_Call) RunAndReturn(run func(ctx context.Context, actorID uuid.UUID, req dto.ChatbotBasePromptUpsertRequest) (*dto.ChatbotBasePromptResponse, error)) *MockAdminService_CreateBasePrompt_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockAdminService
func (_mock *MockAdminService) Delete(ctx context.Context, actorID uuid.UUID, id uuid.UUID) error {
	ret := _mock.Called(ctx, actorID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, actorID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdminService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAdminService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID uuid.UUID
//   - id uuid.UUID
func (_e *MockAdminService_Expecter) Delete(ctx any, actorID any, id any) *MockAdminService_Delete_Call {
	return &MockAdminService_Delete_Call{Call: _e.mock.On("Delete", ctx, actorID, id)}
}

func (_c *MockAdminService_Delete_Call) Run(run func(ctx context.Context, actorID uuid.UUID, id uuid.UUID)) *MockAdminService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdminService_Delete_Call) Return(err error) *MockAdminService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdminService_Delete_Call) RunAndReturn(run func(ctx context.Context, actorID uuid.UUID, id uuid.UUID) error) *MockAdminService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBasePrompt provides a mock function for the type MockAdminService
func (_mock *MockAdminService) DeleteBasePrompt(ctx context.Context, actorID uuid.UUID, id uuid.UUID) error {
	ret := _mock.Called(ctx, actorID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBasePrompt")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, actorID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdminService_DeleteBasePrompt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBasePrompt'
type MockAdminService_DeleteBasePrompt_Call struct {
	*mock.Call
}

// DeleteBasePrompt is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID uuid.UUID
//   - id uuid.UUID
func (_e *MockAdminService_Expecter) DeleteBasePrompt(ctx any, actorID any, id any) *MockAdminService_DeleteBasePrompt_Call {
	return &MockAdminService_DeleteBasePrompt_Call{Call: _e.mock.On("DeleteBasePrompt", ctx, actorID, id)}
}

func (_c *MockAdminService_DeleteBasePrompt_Call) Run(run func(ctx context.Context, actorID uuid.UUID, id uuid.UUID)) *MockAdminService_DeleteBasePrompt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdminService_DeleteBasePrompt_Call) Return(err error) *MockAdminService_DeleteBasePrompt_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdminService_DeleteBasePrompt_Call) RunAndReturn(run func(ctx context.Context, actorID uuid.UUID, id uuid.UUID) error) *MockAdminService_DeleteBasePrompt_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockAdminService
func (_mock *MockAdminService) List(ctx context.Context) ([]dto.ChatbotResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []dto.ChatbotResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]dto.ChatbotResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []dto.ChatbotResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ChatbotResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAdminService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdminService_Expecter) List(ctx any) *MockAdminService_List_Call {
	return &MockAdminService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockAdminService_List_Call) Run(run func(ctx context.Context)) *MockAdminService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAdminService_List_Call) Return(chatbotResponses []dto.ChatbotResponse, err error) *MockAdminService_List_Call {
	_c.Call.Return(chatbotResponses, err)
	return _c
}

func (_c *MockAdminService_List_Call) RunAndReturn(run func(ctx context.Context) ([]dto.ChatbotResponse, error)) *MockAdminService_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListBasePrompts provides a mock function for the type MockAdminService
func (_mock *MockAdminService) ListBasePrompts(ctx context.Context) ([]dto.ChatbotBasePromptResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListBasePrompts")
	}

	var r0 []dto.ChatbotBasePromptResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]dto.ChatbotBasePromptResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []dto.ChatbotBasePromptResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ChatbotBasePromptResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminService_ListBasePrompts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBasePrompts'
type MockAdminService_ListBasePrompts_Call struct {
	*mock.Call
}

// ListBasePrompts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdminService_Expecter) ListBasePrompts(ctx any) *MockAdminService_ListBasePrompts_Call {
	return &MockAdminService_ListBasePrompts_Call{Call: _e.mock.On("ListBasePrompts", ctx)}
}

func (_c *MockAdminService_ListBasePrompts_Call) Run(run func(ctx context.Context)) *MockAdminService_ListBasePrompts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAdminService_ListBasePrompts_Call) Return(chatbotBasePromptResponses []dto.ChatbotBasePromptResponse, err error) *MockAdminService_ListBasePrompts_Call {
	_c.Call.Return(chatbotBasePromptResponses, err)
	return _c
}

func (_c *MockAdminService_ListBasePrompts_Call) RunAndReturn(run func(ctx context.Context) ([]dto.ChatbotBasePromptResponse, error)) *MockAdminService_ListBasePrompts_Call {
	_c.Call.Return(run)
	return _c
}

// Models provides a mock function for the type MockAdminService
func (_mock *MockAdminService) Models(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Models")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminService_Models_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Models'
type MockAdminService_Models_Call struct {
	*mock.Call
}

// Models is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdminService_Expecter) Models(ctx any) *MockAdminService_Models_Call {
	return &MockAdminService_Models_Call{Call: _e.mock.On("Models", ctx)}
}

func (_c *MockAdminService_Models_Call) Run(run func(ctx context.Context)) *MockAdminService_Models_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAdminService_Models_Call) Return(strings []string, err error) *MockAdminService_Models_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockAdminService_Models_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockAdminService_Models_Call {
	_c.Call.Return(run)
	return _c
}

// Test provides a mock function for the type MockAdminService
func (_mock *MockAdminService) Test(ctx context.Context, modelName string) (bool, string, error) {
	ret := _mock.Called(ctx, modelName)

	if len(ret) == 0 {
		panic("no return value specified for Test")
	}

	var r0 bool
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, string, error)); ok {
		return returnFunc(ctx, modelName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, modelName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, modelName)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, modelName)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAdminService_Test_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Test'
type MockAdminService_Test_Call struct {
	*mock.Call
}

// Test is a helper method to define mock.On call
//   - ctx context.Context
//   - modelName string
func (_e *MockAdminService_Expecter) Test(ctx any, modelName any) *MockAdminService_Test_Call {
	return &MockAdminService_Test_Call{Call: _e.mock.On("Test", ctx, modelName)}
}

func (_c *MockAdminService_Test_Call) Run(run func(ctx context.Context, modelName string)) *MockAdminService_Test_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminService_Test_Call) Return(b bool, s string, err error) *MockAdminService_Test_Call {
	_c.Call.Return(b, s, err)
	return _c
}

func (_c *MockAdminService_Test_Call) RunAndReturn(run func(ctx context.Context, modelName string) (bool, string, error)) *MockAdminService_Test_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockAdminService
func (_mock *MockAdminService) Update(ctx context.Context, actorID uuid.UUID, id uuid.UUID, req dto.ChatbotUpsertRequest) (*dto.ChatbotResponse, error) {
	ret := _mock.Called(ctx, actorID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *dto.ChatbotResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.ChatbotUpsertRequest) (*dto.ChatbotResponse, error)); ok {
		return returnFunc(ctx, actorID, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.ChatbotUpsertRequest) *dto.ChatbotResponse); ok {
		r0 = returnFunc(ctx, actorID, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ChatbotResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, dto.ChatbotUpsertRequest) error); ok {
		r1 = returnFunc(ctx, actorID, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAdminService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID uuid.UUID
//   - id uuid.UUID
//   - req dto.ChatbotUpsertRequest
func (_e *MockAdminService_Expecter) Update(ctx any, actorID any, id any, req any) *MockAdminService_Update_Call {
	return &MockAdminService_Update_Call{Call: _e.mock.On("Update", ctx, actorID, id, req)}
}

func (_c *MockAdminService_Update_Call) Run(run func(ctx context.Context, actorID uuid.UUID, id uuid.UUID, req dto.ChatbotUpsertRequest)) *MockAdminService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 dto.ChatbotUpsertRequest
		if args[3] != nil {
			arg3 = args[3].(dto.ChatbotUpsertRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAdminService_Update_Call) Return(chatbotResponse *dto.ChatbotResponse, err error) *MockAdminService_Update_Call {
	_c.Call.Return(chatbotResponse, err)
	return _c
}

func (_c *MockAdminService_Update_Call) RunAndReturn(run func(ctx context.Context, actorID uuid.UUID, id uuid.UUID, req dto.ChatbotUpsertRequest) (*dto.ChatbotResponse, error)) *MockAdminService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBasePrompt provides a mock function for the type MockAdminService
func (_mock *MockAdminService) UpdateBasePrompt(ctx context.Context, actorID uuid.UUID, id uuid.UUID, req dto.ChatbotBasePromptUpsertRequest) (*dto.ChatbotBasePromptResponse, error) {
	ret := _mock.Called(ctx, actorID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBasePrompt")
	}

	var r0 *dto.ChatbotBasePromptResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.ChatbotBasePromptUpsertRequest) (*dto.ChatbotBasePromptResponse, error)); ok {
		return returnFunc(ctx, actorID, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.ChatbotBasePromptUpsertRequest) *dto.ChatbotBasePromptResponse); ok {
		r0 = returnFunc(ctx, actorID, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ChatbotBasePromptResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, dto.ChatbotBasePromptUpsertRequest) error); ok {
		r1 = returnFunc(ctx, actorID, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminService_UpdateBasePrompt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBasePrompt'
type MockAdminService_UpdateBasePrompt_Call struct {
	*mock.Call
}

// UpdateBasePrompt is a helper method to define mock.On call
//   - ctx context.Context
//   - actorID uuid.UUID
//   - id uuid.UUID
//   - req dto.ChatbotBasePromptUpsertRequest
func (_e *MockAdminService_Expecter) UpdateBasePrompt(ctx any, actorID any, id any, req any) *MockAdminService_UpdateBasePrompt_Call {
	return &MockAdminService_UpdateBasePrompt_Call{Call: _e.mock.On("UpdateBasePrompt", ctx, actorID, id, req)}
}

func (_c *MockAdminService_UpdateBasePrompt_Call) Run(run func(ctx context.Context, actorID uuid.UUID, id uuid.UUID, req dto.ChatbotBasePromptUpsertRequest)) *MockAdminService_UpdateBasePrompt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 dto.ChatbotBasePromptUpsertRequest
		if args[3] != nil {
			arg3 = args[3].(dto.ChatbotBasePromptUpsertRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAdminService_UpdateBasePrompt_Call) Return(chatbotBasePromptResponse *dto.ChatbotBasePromptResponse, err error) *MockAdminService_UpdateBasePrompt_Call {
	_c.Call.Return(chatbotBasePromptResponse, err)
	return _c
}

func (_c *MockAdminService_UpdateBasePrompt_Call) RunAndReturn(run func(ctx context.Context, actorID uuid.UUID, id uuid.UUID, req dto.ChatbotBasePromptUpsertRequest) (*dto.ChatbotBasePromptResponse, error)) *MockAdminService_UpdateBasePrompt_Call {
	_c.Call.Return(run)
	return _c
}

// Usage provides a mock function for the type MockAdminService
func (_mock *MockAdminService) Usage(ctx context.Context, since time.Time) (*dto.ChatbotUsageResponse, error) {
	ret := _mock.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for Usage")
	}

	var r0 *dto.ChatbotUsageResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) (*dto.ChatbotUsageResponse, error)); ok {
		return returnFunc(ctx, since)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) *dto.ChatbotUsageResponse); ok {
		r0 = returnFunc(ctx, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ChatbotUsageResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, since)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminService_Usage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Usage'
type MockAdminService_Usage_Call struct {
	*mock.Call
}

// Usage is a helper method to define mock.On call
//   - ctx context.Context
//   - since time.Time
func (_e *MockAdminService_Expecter) Usage(ctx any, since any) *MockAdminService_Usage_Call {
	return &MockAdminService_Usage_Call{Call: _e.mock.On("Usage", ctx, since)}
}

func (_c *MockAdminService_Usage_Call) Run(run func(ctx context.Context, since time.Time)) *MockAdminService_Usage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminService_Usage_Call) Return(chatbotUsageResponse *dto.ChatbotUsageResponse, err error) *MockAdminService_Usage_Call {
	_c.Call.Return(chatbotUsageResponse, err)
	return _c
}

func (_c *MockAdminService_Usage_Call) RunAndReturn(run func(ctx context.Context, since time.Time) (*dto.ChatbotUsageResponse, error)) *MockAdminService_Usage_Call {
	_c.Call.Return(run)
	return _c
}
