// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package chatbot

import (
	"context"
	"umineko_city_of_books/internal/chat"
	"umineko_city_of_books/internal/config"
	"umineko_city_of_books/internal/dto"
	"umineko_city_of_books/internal/post"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Enabled provides a mock function for the type MockService
func (_mock *MockService) Enabled() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Enabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockService_Enabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enabled'
type MockService_Enabled_Call struct {
	*mock.Call
}

// Enabled is a helper method to define mock.On call
func (_e *MockService_Expecter) Enabled() *MockService_Enabled_Call {
	return &MockService_Enabled_Call{Call: _e.mock.On("Enabled")}
}

func (_c *MockService_Enabled_Call) Run(run func()) *MockService_Enabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Enabled_Call) Return(b bool) *MockService_Enabled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockService_Enabled_Call) RunAndReturn(run func() bool) *MockService_Enabled_Call {
	_c.Call.Return(run)
	return _c
}

// Listing provides a mock function for the type MockService
func (_mock *MockService) Listing() []dto.ChatbotSummary {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Listing")
	}

	var r0 []dto.ChatbotSummary
	if returnFunc, ok := ret.Get(0).(func() []dto.ChatbotSummary); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.ChatbotSummary)
		}
	}
	return r0
}

// MockService_Listing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Listing'
type MockService_Listing_Call struct {
	*mock.Call
}

// Listing is a helper method to define mock.On call
func (_e *MockService_Expecter) Listing() *MockService_Listing_Call {
	return &MockService_Listing_Call{Call: _e.mock.On("Listing")}
}

func (_c *MockService_Listing_Call) Run(run func()) *MockService_Listing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Listing_Call) Return(chatbotSummarys []dto.ChatbotSummary) *MockService_Listing_Call {
	_c.Call.Return(chatbotSummarys)
	return _c
}

func (_c *MockService_Listing_Call) RunAndReturn(run func() []dto.ChatbotSummary) *MockService_Listing_Call {
	_c.Call.Return(run)
	return _c
}

// ObserveComment provides a mock function for the type MockService
func (_mock *MockService) ObserveComment(ev post.BotContentEvent) {
	_mock.Called(ev)
	return
}

// MockService_ObserveComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ObserveComment'
type MockService_ObserveComment_Call struct {
	*mock.Call
}

// ObserveComment is a helper method to define mock.On call
//   - ev post.BotContentEvent
func (_e *MockService_Expecter) ObserveComment(ev any) *MockService_ObserveComment_Call {
	return &MockService_ObserveComment_Call{Call: _e.mock.On("ObserveComment", ev)}
}

func (_c *MockService_ObserveComment_Call) Run(run func(ev post.BotContentEvent)) *MockService_ObserveComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 post.BotContentEvent
		if args[0] != nil {
			arg0 = args[0].(post.BotContentEvent)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_ObserveComment_Call) Return() *MockService_ObserveComment_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_ObserveComment_Call) RunAndReturn(run func(ev post.BotContentEvent)) *MockService_ObserveComment_Call {
	_c.Run(run)
	return _c
}

// ObserveMessage provides a mock function for the type MockService
func (_mock *MockService) ObserveMessage(ev chat.BotMessageEvent) {
	_mock.Called(ev)
	return
}

// MockService_ObserveMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ObserveMessage'
type MockService_ObserveMessage_Call struct {
	*mock.Call
}

// ObserveMessage is a helper method to define mock.On call
//   - ev chat.BotMessageEvent
func (_e *MockService_Expecter) ObserveMessage(ev any) *MockService_ObserveMessage_Call {
	return &MockService_ObserveMessage_Call{Call: _e.mock.On("ObserveMessage", ev)}
}

func (_c *MockService_ObserveMessage_Call) Run(run func(ev chat.BotMessageEvent)) *MockService_ObserveMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 chat.BotMessageEvent
		if args[0] != nil {
			arg0 = args[0].(chat.BotMessageEvent)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_ObserveMessage_Call) Return() *MockService_ObserveMessage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_ObserveMessage_Call) RunAndReturn(run func(ev chat.BotMessageEvent)) *MockService_ObserveMessage_Call {
	_c.Run(run)
	return _c
}

// OnSettingsBatchChanged provides a mock function for the type MockService
func (_mock *MockService) OnSettingsBatchChanged(keys []config.SiteSettingKey) {
	_mock.Called(keys)
	return
}

// MockService_OnSettingsBatchChanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnSettingsBatchChanged'
type MockService_OnSettingsBatchChanged_Call struct {
	*mock.Call
}

// OnSettingsBatchChanged is a helper method to define mock.On call
//   - keys []config.SiteSettingKey
func (_e *MockService_Expecter) OnSettingsBatchChanged(keys any) *MockService_OnSettingsBatchChanged_Call {
	return &MockService_OnSettingsBatchChanged_Call{Call: _e.mock.On("OnSettingsBatchChanged", keys)}
}

func (_c *MockService_OnSettingsBatchChanged_Call) Run(run func(keys []config.SiteSettingKey)) *MockService_OnSettingsBatchChanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []config.SiteSettingKey
		if args[0] != nil {
			arg0 = args[0].([]config.SiteSettingKey)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_OnSettingsBatchChanged_Call) Return() *MockService_OnSettingsBatchChanged_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_OnSettingsBatchChanged_Call) RunAndReturn(run func(keys []config.SiteSettingKey)) *MockService_OnSettingsBatchChanged_Call {
	_c.Run(run)
	return _c
}

// Reload provides a mock function for the type MockService
func (_mock *MockService) Reload() {
	_mock.Called()
	return
}

// MockService_Reload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reload'
type MockService_Reload_Call struct {
	*mock.Call
}

// Reload is a helper method to define mock.On call
func (_e *MockService_Expecter) Reload() *MockService_Reload_Call {
	return &MockService_Reload_Call{Call: _e.mock.On("Reload")}
}

func (_c *MockService_Reload_Call) Run(run func()) *MockService_Reload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Reload_Call) Return() *MockService_Reload_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_Reload_Call) RunAndReturn(run func()) *MockService_Reload_Call {
	_c.Run(run)
	return _c
}

// Shutdown provides a mock function for the type MockService
func (_mock *MockService) Shutdown(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockService_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Shutdown(ctx any) *MockService_Shutdown_Call {
	return &MockService_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockService_Shutdown_Call) Run(run func(ctx context.Context)) *MockService_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Shutdown_Call) Return(err error) *MockService_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Shutdown_Call) RunAndReturn(run func(ctx context.Context) error) *MockService_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}
