// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package settings

import (
	"umineko_city_of_books/internal/config"

	mock "github.com/stretchr/testify/mock"
)

// NewMockListener creates a new instance of MockListener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListener(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListener {
	mock := &MockListener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListener is an autogenerated mock type for the Listener type
type MockListener struct {
	mock.Mock
}

type MockListener_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListener) EXPECT() *MockListener_Expecter {
	return &MockListener_Expecter{mock: &_m.Mock}
}

// OnSettingChanged provides a mock function for the type MockListener
func (_mock *MockListener) OnSettingChanged(key config.SiteSettingKey, value string) {
	_mock.Called(key, value)
	return
}

// MockListener_OnSettingChanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnSettingChanged'
type MockListener_OnSettingChanged_Call struct {
	*mock.Call
}

// OnSettingChanged is a helper method to define mock.On call
//   - key config.SiteSettingKey
//   - value string
func (_e *MockListener_Expecter) OnSettingChanged(key any, value any) *MockListener_OnSettingChanged_Call {
	return &MockListener_OnSettingChanged_Call{Call: _e.mock.On("OnSettingChanged", key, value)}
}

func (_c *MockListener_OnSettingChanged_Call) Run(run func(key config.SiteSettingKey, value string)) *MockListener_OnSettingChanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.SiteSettingKey
		if args[0] != nil {
			arg0 = args[0].(config.SiteSettingKey)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockListener_OnSettingChanged_Call) Return() *MockListener_OnSettingChanged_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockListener_OnSettingChanged_Call) RunAndReturn(run func(key config.SiteSettingKey, value string)) *MockListener_OnSettingChanged_Call {
	_c.Run(run)
	return _c
}
