import { roomCapabilities } from "../domain/chat/roomPolicy";
import type { ChatThread } from "./useChatThread";

export function makeChatThread(overrides: Partial<ChatThread> = {}): ChatThread {
    return {
        thread: {
            data: null,
            id: "room-1",
            loading: false,
            set: () => {},
            toggleMute: () => Promise.resolve(),
            mutePending: false,
            voice: {
                status: "idle",
                room: null,
                participantIds: [],
                presenceCount: 0,
                error: "",
                join: () => {},
                leave: () => {},
                clearError: () => {},
                enabled: true,
            },
        },
        session: {
            viewer: null,
            status: "idle",
            messages: [],
            hasMore: false,
            loadingMore: false,
            containerRef: () => {},
            contentRef: () => {},
            endRef: { current: null },
            onScroll: () => {},
            toBottom: () => {},
            editingMessageId: null,
            startEditing: () => {},
            cancelEditing: () => {},
            deleteMessage: () => Promise.resolve(),
            editMessage: () => Promise.resolve(),
            editLast: () => {},
            replyingTo: null,
            setReplyingTo: () => {},
            typingUserIds: [],
            notifyTyping: () => {},
            matchesViewerMention: null,
            readReceipts: {},
            onSent: () => {},
            toggleReaction: () => Promise.resolve(),
            togglePin: () => Promise.resolve(),
            history: {
                hasMore: false,
                loadingMore: false,
                setMessages: () => {},
                addMessage: () => {},
                seedMessages: () => {},
                loadUntilMessage: () => Promise.resolve(false),
                resync: () => Promise.resolve(),
            },
        },
        capabilities: roomCapabilities(null, null),
        toast: {
            message: null,
            show: () => {},
        },
        ...overrides,
    };
}
