import type { RoomController } from "./useRoomController";

function noop(): void {}

function never(): Promise<void> {
    return Promise.resolve();
}

export function makeRoomController(overrides: Partial<RoomController> = {}): RoomController {
    return {
        room: {
            data: null,
            id: "room-1",
            loading: false,
            joining: false,
            viewerTimeoutUntil: undefined,
            viewerTimedOut: false,
            set: noop,
            join: never,
            toggleMute: never,
            leave: never,
            remove: never,
            backToRooms: noop,
        },
        session: {
            viewer: null,
            messages: [],
            hasMore: false,
            loadingMore: false,
            containerRef: noop,
            contentRef: noop,
            endRef: { current: null },
            onScroll: noop,
            toBottom: noop,
            editingMessageId: null,
            startEditing: noop,
            cancelEditing: noop,
            replyingTo: null,
            setReplyingTo: noop,
            typingNames: [],
            notifyTyping: noop,
            matchesViewerMention: null,
            onSent: noop,
            deleteMessage: never,
            editMessage: never,
            editLast: noop,
            toggleReaction: never,
            togglePin: never,
        },
        members: {
            list: [],
            groups: [],
            presence: {},
            onlineWeight: () => 1,
            current: null,
            set: noop,
        },
        moderation: {
            busy: null,
            setBusy: noop,
            openMemberMenu: null,
            setOpenMemberMenu: noop,
            nicknameDialogTarget: null,
            setNicknameDialogTarget: noop,
            nicknameDialogValue: "",
            setNicknameDialogValue: noop,
            nicknameDialogError: "",
            nicknameDialogSaving: false,
            timeoutDialogTarget: null,
            setTimeoutDialogTarget: noop,
            timeoutDialogAmount: "10",
            setTimeoutDialogAmount: noop,
            timeoutDialogUnit: "seconds",
            setTimeoutDialogUnit: noop,
            timeoutDialogError: "",
            timeoutDialogSaving: false,
            formatTimeoutUntil: () => "",
            openNicknameDialog: noop,
            openTimeoutDialog: noop,
            handleModSetNickname: never,
            handleModUnlockNickname: never,
            handleSetTimeout: never,
            handleClearTimeout: never,
            handleKick: never,
            handleBan: never,
        },
        prefs: {
            sidebarCollapsed: false,
            toggleSidebar: noop,
            descExpanded: false,
            toggleDescExpanded: noop,
            mobileView: "chat",
            setMobileView: noop,
        },
        anchor: {
            highlightedMsgId: null,
            jumpTo: never,
        },
        voice: {
            status: "idle",
            room: null,
            participantIds: [],
            presenceCount: 0,
            error: "",
            join: never,
            leave: never,
            clearError: noop,
            enabled: true,
        },
        watchParty: {
            enabled: true,
            screenShareEnabled: true,
            loaded: true,
            sessions: [],
            activeSession: null,
            openSessionId: null,
            error: "",
            refresh: never,
            start: () => Promise.resolve(null),
            join: never,
            leave: never,
            end: never,
            transferControl: never,
            kick: never,
            identify: never,
            openExisting: noop,
            close: noop,
            clearError: noop,
            invitedPartyMissing: false,
        },
        panels: {
            pinnedOpen: false,
            setPinnedOpen: noop,
            searchOpen: false,
            setSearchOpen: noop,
            lightboxSrc: null,
            setLightboxSrc: noop,
            editProfileOpen: false,
            setEditProfileOpen: noop,
            inviteModalOpen: false,
            setInviteModalOpen: noop,
            moderationDialogOpen: false,
            setModerationDialogOpen: noop,
        },
        toast: {
            message: null,
            show: noop,
        },
        ...overrides,
    };
}
