import { makeChatThread } from "./useChatThread.fixture";
import type { RoomController } from "./useRoomController";

export function makeRoomController(overrides: Partial<RoomController> = {}): RoomController {
    const { thread, session, capabilities, toast } = makeChatThread();

    return {
        room: {
            data: thread.data,
            id: thread.id,
            loading: thread.loading,
            joining: false,
            viewerTimeoutUntil: undefined,
            viewerTimedOut: false,
            set: thread.set,
            join: () => Promise.resolve(),
            toggleMute: thread.toggleMute,
            leave: () => Promise.resolve(),
            remove: () => Promise.resolve(),
            backToRooms: () => {},
        },
        session: {
            viewer: session.viewer,
            messages: session.messages,
            hasMore: session.hasMore,
            loadingMore: session.loadingMore,
            containerRef: session.containerRef,
            contentRef: session.contentRef,
            endRef: session.endRef,
            onScroll: session.onScroll,
            toBottom: session.toBottom,
            editingMessageId: session.editingMessageId,
            startEditing: session.startEditing,
            cancelEditing: session.cancelEditing,
            replyingTo: session.replyingTo,
            setReplyingTo: session.setReplyingTo,
            typingNames: [],
            notifyTyping: session.notifyTyping,
            matchesViewerMention: session.matchesViewerMention,
            onSent: session.onSent,
            deleteMessage: session.deleteMessage,
            editMessage: session.editMessage,
            editLast: session.editLast,
            toggleReaction: session.toggleReaction,
            togglePin: session.togglePin,
        },
        members: {
            list: [],
            groups: [],
            presence: {},
            onlineWeight: () => 1,
            current: null,
            set: () => {},
        },
        moderation: {
            busy: null,
            setBusy: () => {},
            openMemberMenu: null,
            setOpenMemberMenu: () => {},
            nicknameDialogTarget: null,
            setNicknameDialogTarget: () => {},
            nicknameDialogValue: "",
            setNicknameDialogValue: () => {},
            nicknameDialogError: "",
            nicknameDialogSaving: false,
            timeoutDialogTarget: null,
            setTimeoutDialogTarget: () => {},
            timeoutDialogAmount: "10",
            setTimeoutDialogAmount: () => {},
            timeoutDialogUnit: "seconds",
            setTimeoutDialogUnit: () => {},
            timeoutDialogError: "",
            timeoutDialogSaving: false,
            formatTimeoutUntil: () => "",
            openNicknameDialog: () => {},
            openTimeoutDialog: () => {},
            handleModSetNickname: () => Promise.resolve(),
            handleModUnlockNickname: () => Promise.resolve(),
            handleSetTimeout: () => Promise.resolve(),
            handleClearTimeout: () => Promise.resolve(),
            handleKick: () => Promise.resolve(),
            handleBan: () => Promise.resolve(),
        },
        capabilities,
        prefs: {
            sidebarCollapsed: false,
            toggleSidebar: () => {},
            descExpanded: false,
            toggleDescExpanded: () => {},
            mobileView: "chat",
            setMobileView: () => {},
        },
        anchor: {
            highlightedMsgId: null,
            jumpTo: () => Promise.resolve(),
        },
        voice: thread.voice,
        watchParty: {
            enabled: true,
            screenShareEnabled: true,
            loaded: true,
            sessions: [],
            activeSession: null,
            openSessionId: null,
            error: "",
            refresh: () => Promise.resolve(),
            start: () => Promise.resolve(null),
            join: () => Promise.resolve(),
            leave: () => Promise.resolve(),
            end: () => Promise.resolve(),
            transferControl: () => Promise.resolve(),
            kick: () => Promise.resolve(),
            identify: () => Promise.resolve(),
            openExisting: () => {},
            close: () => {},
            clearError: () => {},
            invitedPartyMissing: false,
        },
        panels: {
            panelTab: null,
            openPanel: () => {},
            closePanel: () => {},
            lightboxSrc: null,
            setLightboxSrc: () => {},
            editProfileOpen: false,
            setEditProfileOpen: () => {},
            inviteModalOpen: false,
            setInviteModalOpen: () => {},
            moderationDialogOpen: false,
            setModerationDialogOpen: () => {},
        },
        toast: {
            message: toast.message,
            show: toast.show,
        },
        ...overrides,
    };
}
