package repository

type (
	AuditAction     string
	AuditTargetType string
)

const (
	AuditActionUserCreated   AuditAction = "user_created"
	AuditActionPasswordReset AuditAction = "password_reset"

	AuditActionSetRole            AuditAction = "set_role"
	AuditActionRemoveRole         AuditAction = "remove_role"
	AuditActionBanUser            AuditAction = "ban_user"
	AuditActionUnbanUser          AuditAction = "unban_user"
	AuditActionLockUser           AuditAction = "lock_user"
	AuditActionUnlockUser         AuditAction = "unlock_user"
	AuditActionDeleteUser         AuditAction = "delete_user"
	AuditActionResetPassword      AuditAction = "reset_password"
	AuditActionSetUserEmail       AuditAction = "set_user_email"
	AuditActionVerifyUserEmail    AuditAction = "verify_user_email"
	AuditActionUnverifyUserEmail  AuditAction = "unverify_user_email"
	AuditActionSetDisplayName     AuditAction = "set_display_name"
	AuditActionLockDisplayName    AuditAction = "lock_display_name"
	AuditActionUnlockDisplayName  AuditAction = "unlock_display_name"
	AuditActionForceLogout        AuditAction = "force_logout"
	AuditActionUpdateSettings     AuditAction = "update_settings"
	AuditActionSendTestEmail      AuditAction = "send_test_email"
	AuditActionCreateInvite       AuditAction = "create_invite"
	AuditActionDeleteInvite       AuditAction = "delete_invite"
	AuditActionCreateVanityRole   AuditAction = "create_vanity_role"
	AuditActionUpdateVanityRole   AuditAction = "update_vanity_role"
	AuditActionDeleteVanityRole   AuditAction = "delete_vanity_role"
	AuditActionAssignVanityRole   AuditAction = "assign_vanity_role"
	AuditActionUnassignVanityRole AuditAction = "unassign_vanity_role"

	AuditActionUpdateRolePermissions       AuditAction = "update_role_permissions"
	AuditActionUpdateVanityRolePermissions AuditAction = "update_vanity_role_permissions"

	AuditActionChatRoomBan                AuditAction = "chat_room_ban"
	AuditActionChatRoomUnban              AuditAction = "chat_room_unban"
	AuditActionChatWordFilterKick         AuditAction = "chat_word_filter_kick"
	AuditActionChatWordFilterDelete       AuditAction = "chat_word_filter_delete"
	AuditActionChatRoomBannedWordCreate   AuditAction = "chat_room_banned_word_create"
	AuditActionChatRoomBannedWordUpdate   AuditAction = "chat_room_banned_word_update"
	AuditActionChatRoomBannedWordDelete   AuditAction = "chat_room_banned_word_delete"
	AuditActionChatGlobalBannedWordCreate AuditAction = "chat_global_banned_word_create"
	AuditActionChatGlobalBannedWordUpdate AuditAction = "chat_global_banned_word_update"
	AuditActionChatGlobalBannedWordDelete AuditAction = "chat_global_banned_word_delete"

	AuditActionChatMessageDelete    AuditAction = "chat_message_delete"
	AuditActionChatMessageDeleteMod AuditAction = "chat_message_delete_mod"
	AuditActionChatRoomDelete       AuditAction = "chat_room_delete"
	AuditActionChatRoomUpdate       AuditAction = "chat_room_update"
	AuditActionChatRoomKick         AuditAction = "chat_room_kick"
	AuditActionChatRoomTimeout      AuditAction = "chat_room_timeout"

	AuditActionWatchPartyStart        AuditAction = "watch_party.start"
	AuditActionWatchPartyEnd          AuditAction = "watch_party.end"
	AuditActionWatchPartyKick         AuditAction = "watch_party.kick"
	AuditActionWatchPartyGrantControl AuditAction = "watch_party.grant_control"

	AuditActionPostCommentDelete              AuditAction = "post_comment_delete"
	AuditActionPostCommentDeleteAdmin         AuditAction = "post_comment_delete_admin"
	AuditActionArtCommentDelete               AuditAction = "art_comment_delete"
	AuditActionArtCommentDeleteAdmin          AuditAction = "art_comment_delete_admin"
	AuditActionFanficCommentDelete            AuditAction = "fanfic_comment_delete"
	AuditActionFanficCommentDeleteAdmin       AuditAction = "fanfic_comment_delete_admin"
	AuditActionMysteryCommentDelete           AuditAction = "mystery_comment_delete"
	AuditActionMysteryCommentDeleteAdmin      AuditAction = "mystery_comment_delete_admin"
	AuditActionJournalCommentDelete           AuditAction = "journal_comment_delete"
	AuditActionJournalCommentDeleteAdmin      AuditAction = "journal_comment_delete_admin"
	AuditActionShipCommentDelete              AuditAction = "ship_comment_delete"
	AuditActionShipCommentDeleteAdmin         AuditAction = "ship_comment_delete_admin"
	AuditActionSecretCommentDelete            AuditAction = "secret_comment_delete"
	AuditActionSecretCommentDeleteAdmin       AuditAction = "secret_comment_delete_admin"
	AuditActionAnnouncementCommentDelete      AuditAction = "announcement_comment_delete"
	AuditActionAnnouncementCommentDeleteAdmin AuditAction = "announcement_comment_delete_admin"
	AuditActionOCCommentDelete                AuditAction = "oc_comment_delete"
	AuditActionOCCommentDeleteAdmin           AuditAction = "oc_comment_delete_admin"

	AuditActionPostCommentUpdateAdmin         AuditAction = "post_comment_update_admin"
	AuditActionArtCommentUpdateAdmin          AuditAction = "art_comment_update_admin"
	AuditActionFanficCommentUpdateAdmin       AuditAction = "fanfic_comment_update_admin"
	AuditActionMysteryCommentUpdateAdmin      AuditAction = "mystery_comment_update_admin"
	AuditActionJournalCommentUpdateAdmin      AuditAction = "journal_comment_update_admin"
	AuditActionShipCommentUpdateAdmin         AuditAction = "ship_comment_update_admin"
	AuditActionSecretCommentUpdateAdmin       AuditAction = "secret_comment_update_admin"
	AuditActionAnnouncementCommentUpdateAdmin AuditAction = "announcement_comment_update_admin"
	AuditActionOCCommentUpdateAdmin           AuditAction = "oc_comment_update_admin"

	AuditActionPostDelete               AuditAction = "post_delete"
	AuditActionPostDeleteAdmin          AuditAction = "post_delete_admin"
	AuditActionArtDelete                AuditAction = "art_delete"
	AuditActionArtDeleteAdmin           AuditAction = "art_delete_admin"
	AuditActionGalleryDelete            AuditAction = "gallery_delete"
	AuditActionFanficDelete             AuditAction = "fanfic_delete"
	AuditActionFanficDeleteAdmin        AuditAction = "fanfic_delete_admin"
	AuditActionFanficUpdateAdmin        AuditAction = "fanfic_update_admin"
	AuditActionFanficChapterDelete      AuditAction = "fanfic_chapter_delete"
	AuditActionFanficChapterDeleteAdmin AuditAction = "fanfic_chapter_delete_admin"
	AuditActionFanficChapterUpdateAdmin AuditAction = "fanfic_chapter_update_admin"
	AuditActionJournalDelete            AuditAction = "journal_delete"
	AuditActionJournalDeleteAdmin       AuditAction = "journal_delete_admin"
	AuditActionJournalUpdateAdmin       AuditAction = "journal_update_admin"
	AuditActionJournalEntryDelete       AuditAction = "journal_entry_delete"
	AuditActionJournalEntryDeleteAdmin  AuditAction = "journal_entry_delete_admin"
	AuditActionJournalEntryCreateAdmin  AuditAction = "journal_entry_create_admin"
	AuditActionJournalEntryUpdateAdmin  AuditAction = "journal_entry_update_admin"
	AuditActionShipDelete               AuditAction = "ship_delete"
	AuditActionShipDeleteAdmin          AuditAction = "ship_delete_admin"
	AuditActionShipUpdateAdmin          AuditAction = "ship_update_admin"
	AuditActionOCDelete                 AuditAction = "oc_delete"
	AuditActionOCDeleteAdmin            AuditAction = "oc_delete_admin"
	AuditActionAnnouncementCreate       AuditAction = "announcement_create"
	AuditActionAnnouncementUpdate       AuditAction = "announcement_update"
	AuditActionAnnouncementDelete       AuditAction = "announcement_delete"
	AuditActionAnnouncementPin          AuditAction = "announcement_pin"

	AuditActionMysteryDelete             AuditAction = "mystery_delete"
	AuditActionMysteryDeleteAdmin        AuditAction = "mystery_delete_admin"
	AuditActionMysteryUpdateAdmin        AuditAction = "mystery_update_admin"
	AuditActionMysterySolved             AuditAction = "mystery_solved"
	AuditActionMysteryClosed             AuditAction = "mystery_closed"
	AuditActionMysteryClueUpdate         AuditAction = "mystery_clue_update"
	AuditActionMysteryClueDelete         AuditAction = "mystery_clue_delete"
	AuditActionMysteryAttemptDeleteAdmin AuditAction = "mystery_attempt_delete_admin"
	AuditActionTheoryDelete              AuditAction = "theory_delete"
	AuditActionTheoryDeleteAdmin         AuditAction = "theory_delete_admin"
	AuditActionTheoryUpdateAdmin         AuditAction = "theory_update_admin"
	AuditActionTheoryRefuted             AuditAction = "theory_refuted"
	AuditActionTheoryResponseDeleteAdmin AuditAction = "theory_response_delete_admin"
	AuditActionMysteryScoreAdjust        AuditAction = "mystery_score_adjust"
	AuditActionGMScoreAdjust             AuditAction = "gm_score_adjust"

	AuditActionChatbotCreate           AuditAction = "chatbot_create"
	AuditActionChatbotUpdate           AuditAction = "chatbot_update"
	AuditActionChatbotDelete           AuditAction = "chatbot_delete"
	AuditActionChatbotBasePromptCreate AuditAction = "chatbot_base_prompt_create"
	AuditActionChatbotBasePromptUpdate AuditAction = "chatbot_base_prompt_update"
	AuditActionChatbotBasePromptDelete AuditAction = "chatbot_base_prompt_delete"
	AuditActionChatbotOptInRoleMigrate AuditAction = "chatbot_opt_in_role_migrate"

	AuditActionChangePassword  AuditAction = "change_password"
	AuditActionChangeEmail     AuditAction = "change_email"
	AuditActionDeleteAccount   AuditAction = "delete_account"
	AuditActionLoginBanned     AuditAction = "login_banned"
	AuditActionBannedGifCreate AuditAction = "banned_gif_create"
	AuditActionBannedGifDelete AuditAction = "banned_gif_delete"
)

const (
	AuditTargetUser       AuditTargetType = "user"
	AuditTargetSettings   AuditTargetType = "settings"
	AuditTargetInvite     AuditTargetType = "invite"
	AuditTargetRole       AuditTargetType = "role"
	AuditTargetVanityRole AuditTargetType = "vanity_role"

	AuditTargetChatRoom              AuditTargetType = "chat_room"
	AuditTargetBannedWord            AuditTargetType = "banned_word"
	AuditTargetChatWatchPartySession AuditTargetType = "chat_watch_party_session"

	AuditTargetPost              AuditTargetType = "post"
	AuditTargetArt               AuditTargetType = "art"
	AuditTargetGallery           AuditTargetType = "gallery"
	AuditTargetFanfic            AuditTargetType = "fanfic"
	AuditTargetFanficChapter     AuditTargetType = "fanfic_chapter"
	AuditTargetJournal           AuditTargetType = "journal"
	AuditTargetJournalEntry      AuditTargetType = "journal_entry"
	AuditTargetShip              AuditTargetType = "ship"
	AuditTargetOC                AuditTargetType = "oc"
	AuditTargetAnnouncement      AuditTargetType = "announcement"
	AuditTargetMystery           AuditTargetType = "mystery"
	AuditTargetMysteryAttempt    AuditTargetType = "mystery_attempt"
	AuditTargetTheory            AuditTargetType = "theory"
	AuditTargetTheoryResponse    AuditTargetType = "theory_response"
	AuditTargetChatbot           AuditTargetType = "chatbot"
	AuditTargetChatbotBasePrompt AuditTargetType = "chatbot_base_prompt"
	AuditTargetBannedGif         AuditTargetType = "banned_gif"

	AuditTargetPostComment         AuditTargetType = "post_comment"
	AuditTargetArtComment          AuditTargetType = "art_comment"
	AuditTargetFanficComment       AuditTargetType = "fanfic_comment"
	AuditTargetMysteryComment      AuditTargetType = "mystery_comment"
	AuditTargetJournalComment      AuditTargetType = "journal_comment"
	AuditTargetShipComment         AuditTargetType = "ship_comment"
	AuditTargetSecretComment       AuditTargetType = "secret_comment"
	AuditTargetAnnouncementComment AuditTargetType = "announcement_comment"
	AuditTargetOCComment           AuditTargetType = "oc_comment"
)
