// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuditLogRepository creates a new instance of MockAuditLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditLogRepository {
	mock := &MockAuditLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuditLogRepository is an autogenerated mock type for the AuditLogRepository type
type MockAuditLogRepository struct {
	mock.Mock
}

type MockAuditLogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditLogRepository) EXPECT() *MockAuditLogRepository_Expecter {
	return &MockAuditLogRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAuditLogRepository
func (_mock *MockAuditLogRepository) Create(ctx context.Context, spec NewAuditEntry, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, spec, tx)
	} else {
		tmpRet = _mock.Called(ctx, spec)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, NewAuditEntry, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, spec, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditLogRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAuditLogRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - spec NewAuditEntry
//   - tx ...*sql.Tx
func (_e *MockAuditLogRepository_Expecter) Create(ctx any, spec any, tx ...any) *MockAuditLogRepository_Create_Call {
	return &MockAuditLogRepository_Create_Call{Call: _e.mock.On("Create",
		append([]any{ctx, spec}, tx...)...)}
}

func (_c *MockAuditLogRepository_Create_Call) Run(run func(ctx context.Context, spec NewAuditEntry, tx ...*sql.Tx)) *MockAuditLogRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 NewAuditEntry
		if args[1] != nil {
			arg1 = args[1].(NewAuditEntry)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAuditLogRepository_Create_Call) Return(err error) *MockAuditLogRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditLogRepository_Create_Call) RunAndReturn(run func(ctx context.Context, spec NewAuditEntry, tx ...*sql.Tx) error) *MockAuditLogRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSystem provides a mock function for the type MockAuditLogRepository
func (_mock *MockAuditLogRepository) CreateSystem(ctx context.Context, spec NewAuditEntry, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, spec, tx)
	} else {
		tmpRet = _mock.Called(ctx, spec)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateSystem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, NewAuditEntry, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, spec, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditLogRepository_CreateSystem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSystem'
type MockAuditLogRepository_CreateSystem_Call struct {
	*mock.Call
}

// CreateSystem is a helper method to define mock.On call
//   - ctx context.Context
//   - spec NewAuditEntry
//   - tx ...*sql.Tx
func (_e *MockAuditLogRepository_Expecter) CreateSystem(ctx any, spec any, tx ...any) *MockAuditLogRepository_CreateSystem_Call {
	return &MockAuditLogRepository_CreateSystem_Call{Call: _e.mock.On("CreateSystem",
		append([]any{ctx, spec}, tx...)...)}
}

func (_c *MockAuditLogRepository_CreateSystem_Call) Run(run func(ctx context.Context, spec NewAuditEntry, tx ...*sql.Tx)) *MockAuditLogRepository_CreateSystem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 NewAuditEntry
		if args[1] != nil {
			arg1 = args[1].(NewAuditEntry)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAuditLogRepository_CreateSystem_Call) Return(err error) *MockAuditLogRepository_CreateSystem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditLogRepository_CreateSystem_Call) RunAndReturn(run func(ctx context.Context, spec NewAuditEntry, tx ...*sql.Tx) error) *MockAuditLogRepository_CreateSystem_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockAuditLogRepository
func (_mock *MockAuditLogRepository) List(ctx context.Context, action AuditAction, limit int, offset int, tx ...*sql.Tx) ([]AuditLogEntry, int, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, action, limit, offset, tx)
	} else {
		tmpRet = _mock.Called(ctx, action, limit, offset)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []AuditLogEntry
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, AuditAction, int, int, ...*sql.Tx) ([]AuditLogEntry, int, error)); ok {
		return returnFunc(ctx, action, limit, offset, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, AuditAction, int, int, ...*sql.Tx) []AuditLogEntry); ok {
		r0 = returnFunc(ctx, action, limit, offset, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]AuditLogEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, AuditAction, int, int, ...*sql.Tx) int); ok {
		r1 = returnFunc(ctx, action, limit, offset, tx...)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, AuditAction, int, int, ...*sql.Tx) error); ok {
		r2 = returnFunc(ctx, action, limit, offset, tx...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuditLogRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAuditLogRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - action AuditAction
//   - limit int
//   - offset int
//   - tx ...*sql.Tx
func (_e *MockAuditLogRepository_Expecter) List(ctx any, action any, limit any, offset any, tx ...any) *MockAuditLogRepository_List_Call {
	return &MockAuditLogRepository_List_Call{Call: _e.mock.On("List",
		append([]any{ctx, action, limit, offset}, tx...)...)}
}

func (_c *MockAuditLogRepository_List_Call) Run(run func(ctx context.Context, action AuditAction, limit int, offset int, tx ...*sql.Tx)) *MockAuditLogRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 AuditAction
		if args[1] != nil {
			arg1 = args[1].(AuditAction)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 4 {
			variadicArgs = args[4].([]*sql.Tx)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockAuditLogRepository_List_Call) Return(auditLogEntrys []AuditLogEntry, n int, err error) *MockAuditLogRepository_List_Call {
	_c.Call.Return(auditLogEntrys, n, err)
	return _c
}

func (_c *MockAuditLogRepository_List_Call) RunAndReturn(run func(ctx context.Context, action AuditAction, limit int, offset int, tx ...*sql.Tx) ([]AuditLogEntry, int, error)) *MockAuditLogRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListForUser provides a mock function for the type MockAuditLogRepository
func (_mock *MockAuditLogRepository) ListForUser(ctx context.Context, userID uuid.UUID, limit int, offset int, tx ...*sql.Tx) ([]AuditLogEntry, int, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, userID, limit, offset, tx)
	} else {
		tmpRet = _mock.Called(ctx, userID, limit, offset)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListForUser")
	}

	var r0 []AuditLogEntry
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int, ...*sql.Tx) ([]AuditLogEntry, int, error)); ok {
		return returnFunc(ctx, userID, limit, offset, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int, ...*sql.Tx) []AuditLogEntry); ok {
		r0 = returnFunc(ctx, userID, limit, offset, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]AuditLogEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int, ...*sql.Tx) int); ok {
		r1 = returnFunc(ctx, userID, limit, offset, tx...)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int, ...*sql.Tx) error); ok {
		r2 = returnFunc(ctx, userID, limit, offset, tx...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuditLogRepository_ListForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListForUser'
type MockAuditLogRepository_ListForUser_Call struct {
	*mock.Call
}

// ListForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - limit int
//   - offset int
//   - tx ...*sql.Tx
func (_e *MockAuditLogRepository_Expecter) ListForUser(ctx any, userID any, limit any, offset any, tx ...any) *MockAuditLogRepository_ListForUser_Call {
	return &MockAuditLogRepository_ListForUser_Call{Call: _e.mock.On("ListForUser",
		append([]any{ctx, userID, limit, offset}, tx...)...)}
}

func (_c *MockAuditLogRepository_ListForUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, limit int, offset int, tx ...*sql.Tx)) *MockAuditLogRepository_ListForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 4 {
			variadicArgs = args[4].([]*sql.Tx)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockAuditLogRepository_ListForUser_Call) Return(auditLogEntrys []AuditLogEntry, n int, err error) *MockAuditLogRepository_ListForUser_Call {
	_c.Call.Return(auditLogEntrys, n, err)
	return _c
}

func (_c *MockAuditLogRepository_ListForUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, limit int, offset int, tx ...*sql.Tx) ([]AuditLogEntry, int, error)) *MockAuditLogRepository_ListForUser_Call {
	_c.Call.Return(run)
	return _c
}
