// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBannedGiphyRepository creates a new instance of MockBannedGiphyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBannedGiphyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBannedGiphyRepository {
	mock := &MockBannedGiphyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBannedGiphyRepository is an autogenerated mock type for the BannedGiphyRepository type
type MockBannedGiphyRepository struct {
	mock.Mock
}

type MockBannedGiphyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBannedGiphyRepository) EXPECT() *MockBannedGiphyRepository_Expecter {
	return &MockBannedGiphyRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockBannedGiphyRepository
func (_mock *MockBannedGiphyRepository) Add(ctx context.Context, kind string, value string, reason string, createdBy *string) error {
	ret := _mock.Called(ctx, kind, value, reason, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *string) error); ok {
		r0 = returnFunc(ctx, kind, value, reason, createdBy)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBannedGiphyRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockBannedGiphyRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - kind string
//   - value string
//   - reason string
//   - createdBy *string
func (_e *MockBannedGiphyRepository_Expecter) Add(ctx interface{}, kind interface{}, value interface{}, reason interface{}, createdBy interface{}) *MockBannedGiphyRepository_Add_Call {
	return &MockBannedGiphyRepository_Add_Call{Call: _e.mock.On("Add", ctx, kind, value, reason, createdBy)}
}

func (_c *MockBannedGiphyRepository_Add_Call) Run(run func(ctx context.Context, kind string, value string, reason string, createdBy *string)) *MockBannedGiphyRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *string
		if args[4] != nil {
			arg4 = args[4].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockBannedGiphyRepository_Add_Call) Return(err error) *MockBannedGiphyRepository_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBannedGiphyRepository_Add_Call) RunAndReturn(run func(ctx context.Context, kind string, value string, reason string, createdBy *string) error) *MockBannedGiphyRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockBannedGiphyRepository
func (_mock *MockBannedGiphyRepository) List(ctx context.Context) ([]BannedGiphyRow, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []BannedGiphyRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]BannedGiphyRow, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []BannedGiphyRow); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]BannedGiphyRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBannedGiphyRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockBannedGiphyRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBannedGiphyRepository_Expecter) List(ctx interface{}) *MockBannedGiphyRepository_List_Call {
	return &MockBannedGiphyRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockBannedGiphyRepository_List_Call) Run(run func(ctx context.Context)) *MockBannedGiphyRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBannedGiphyRepository_List_Call) Return(bannedGiphyRows []BannedGiphyRow, err error) *MockBannedGiphyRepository_List_Call {
	_c.Call.Return(bannedGiphyRows, err)
	return _c
}

func (_c *MockBannedGiphyRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]BannedGiphyRow, error)) *MockBannedGiphyRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockBannedGiphyRepository
func (_mock *MockBannedGiphyRepository) Remove(ctx context.Context, kind string, value string) error {
	ret := _mock.Called(ctx, kind, value)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, kind, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBannedGiphyRepository_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockBannedGiphyRepository_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - kind string
//   - value string
func (_e *MockBannedGiphyRepository_Expecter) Remove(ctx interface{}, kind interface{}, value interface{}) *MockBannedGiphyRepository_Remove_Call {
	return &MockBannedGiphyRepository_Remove_Call{Call: _e.mock.On("Remove", ctx, kind, value)}
}

func (_c *MockBannedGiphyRepository_Remove_Call) Run(run func(ctx context.Context, kind string, value string)) *MockBannedGiphyRepository_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBannedGiphyRepository_Remove_Call) Return(err error) *MockBannedGiphyRepository_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBannedGiphyRepository_Remove_Call) RunAndReturn(run func(ctx context.Context, kind string, value string) error) *MockBannedGiphyRepository_Remove_Call {
	_c.Call.Return(run)
	return _c
}
