// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBlockRepository creates a new instance of MockBlockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlockRepository {
	mock := &MockBlockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlockRepository is an autogenerated mock type for the BlockRepository type
type MockBlockRepository struct {
	mock.Mock
}

type MockBlockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlockRepository) EXPECT() *MockBlockRepository_Expecter {
	return &MockBlockRepository_Expecter{mock: &_m.Mock}
}

// Block provides a mock function for the type MockBlockRepository
func (_mock *MockBlockRepository) Block(ctx context.Context, blockerID uuid.UUID, blockedID uuid.UUID, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, blockerID, blockedID, tx)
	} else {
		tmpRet = _mock.Called(ctx, blockerID, blockedID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Block")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, blockerID, blockedID, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlockRepository_Block_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Block'
type MockBlockRepository_Block_Call struct {
	*mock.Call
}

// Block is a helper method to define mock.On call
//   - ctx context.Context
//   - blockerID uuid.UUID
//   - blockedID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockBlockRepository_Expecter) Block(ctx any, blockerID any, blockedID any, tx ...any) *MockBlockRepository_Block_Call {
	return &MockBlockRepository_Block_Call{Call: _e.mock.On("Block",
		append([]any{ctx, blockerID, blockedID}, tx...)...)}
}

func (_c *MockBlockRepository_Block_Call) Run(run func(ctx context.Context, blockerID uuid.UUID, blockedID uuid.UUID, tx ...*sql.Tx)) *MockBlockRepository_Block_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 3 {
			variadicArgs = args[3].([]*sql.Tx)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockBlockRepository_Block_Call) Return(err error) *MockBlockRepository_Block_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlockRepository_Block_Call) RunAndReturn(run func(ctx context.Context, blockerID uuid.UUID, blockedID uuid.UUID, tx ...*sql.Tx) error) *MockBlockRepository_Block_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlockedIDs provides a mock function for the type MockBlockRepository
func (_mock *MockBlockRepository) GetBlockedIDs(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx) ([]uuid.UUID, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, userID, tx)
	} else {
		tmpRet = _mock.Called(ctx, userID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetBlockedIDs")
	}

	var r0 []uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) ([]uuid.UUID, error)); ok {
		return returnFunc(ctx, userID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) []uuid.UUID); ok {
		r0 = returnFunc(ctx, userID, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, userID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockRepository_GetBlockedIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockedIDs'
type MockBlockRepository_GetBlockedIDs_Call struct {
	*mock.Call
}

// GetBlockedIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockBlockRepository_Expecter) GetBlockedIDs(ctx any, userID any, tx ...any) *MockBlockRepository_GetBlockedIDs_Call {
	return &MockBlockRepository_GetBlockedIDs_Call{Call: _e.mock.On("GetBlockedIDs",
		append([]any{ctx, userID}, tx...)...)}
}

func (_c *MockBlockRepository_GetBlockedIDs_Call) Run(run func(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx)) *MockBlockRepository_GetBlockedIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockBlockRepository_GetBlockedIDs_Call) Return(uUIDs []uuid.UUID, err error) *MockBlockRepository_GetBlockedIDs_Call {
	_c.Call.Return(uUIDs, err)
	return _c
}

func (_c *MockBlockRepository_GetBlockedIDs_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx) ([]uuid.UUID, error)) *MockBlockRepository_GetBlockedIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlockedUsers provides a mock function for the type MockBlockRepository
func (_mock *MockBlockRepository) GetBlockedUsers(ctx context.Context, blockerID uuid.UUID, tx ...*sql.Tx) ([]BlockedUser, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, blockerID, tx)
	} else {
		tmpRet = _mock.Called(ctx, blockerID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetBlockedUsers")
	}

	var r0 []BlockedUser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) ([]BlockedUser, error)); ok {
		return returnFunc(ctx, blockerID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) []BlockedUser); ok {
		r0 = returnFunc(ctx, blockerID, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]BlockedUser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, blockerID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockRepository_GetBlockedUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockedUsers'
type MockBlockRepository_GetBlockedUsers_Call struct {
	*mock.Call
}

// GetBlockedUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - blockerID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockBlockRepository_Expecter) GetBlockedUsers(ctx any, blockerID any, tx ...any) *MockBlockRepository_GetBlockedUsers_Call {
	return &MockBlockRepository_GetBlockedUsers_Call{Call: _e.mock.On("GetBlockedUsers",
		append([]any{ctx, blockerID}, tx...)...)}
}

func (_c *MockBlockRepository_GetBlockedUsers_Call) Run(run func(ctx context.Context, blockerID uuid.UUID, tx ...*sql.Tx)) *MockBlockRepository_GetBlockedUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockBlockRepository_GetBlockedUsers_Call) Return(blockedUsers []BlockedUser, err error) *MockBlockRepository_GetBlockedUsers_Call {
	_c.Call.Return(blockedUsers, err)
	return _c
}

func (_c *MockBlockRepository_GetBlockedUsers_Call) RunAndReturn(run func(ctx context.Context, blockerID uuid.UUID, tx ...*sql.Tx) ([]BlockedUser, error)) *MockBlockRepository_GetBlockedUsers_Call {
	_c.Call.Return(run)
	return _c
}

// IsBlocked provides a mock function for the type MockBlockRepository
func (_mock *MockBlockRepository) IsBlocked(ctx context.Context, blockerID uuid.UUID, blockedID uuid.UUID, tx ...*sql.Tx) (bool, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, blockerID, blockedID, tx)
	} else {
		tmpRet = _mock.Called(ctx, blockerID, blockedID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for IsBlocked")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, ...*sql.Tx) (bool, error)); ok {
		return returnFunc(ctx, blockerID, blockedID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, ...*sql.Tx) bool); ok {
		r0 = returnFunc(ctx, blockerID, blockedID, tx...)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, blockerID, blockedID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockRepository_IsBlocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsBlocked'
type MockBlockRepository_IsBlocked_Call struct {
	*mock.Call
}

// IsBlocked is a helper method to define mock.On call
//   - ctx context.Context
//   - blockerID uuid.UUID
//   - blockedID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockBlockRepository_Expecter) IsBlocked(ctx any, blockerID any, blockedID any, tx ...any) *MockBlockRepository_IsBlocked_Call {
	return &MockBlockRepository_IsBlocked_Call{Call: _e.mock.On("IsBlocked",
		append([]any{ctx, blockerID, blockedID}, tx...)...)}
}

func (_c *MockBlockRepository_IsBlocked_Call) Run(run func(ctx context.Context, blockerID uuid.UUID, blockedID uuid.UUID, tx ...*sql.Tx)) *MockBlockRepository_IsBlocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 3 {
			variadicArgs = args[3].([]*sql.Tx)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockBlockRepository_IsBlocked_Call) Return(b bool, err error) *MockBlockRepository_IsBlocked_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockBlockRepository_IsBlocked_Call) RunAndReturn(run func(ctx context.Context, blockerID uuid.UUID, blockedID uuid.UUID, tx ...*sql.Tx) (bool, error)) *MockBlockRepository_IsBlocked_Call {
	_c.Call.Return(run)
	return _c
}

// IsBlockedEither provides a mock function for the type MockBlockRepository
func (_mock *MockBlockRepository) IsBlockedEither(ctx context.Context, userA uuid.UUID, userB uuid.UUID, tx ...*sql.Tx) (bool, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, userA, userB, tx)
	} else {
		tmpRet = _mock.Called(ctx, userA, userB)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for IsBlockedEither")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, ...*sql.Tx) (bool, error)); ok {
		return returnFunc(ctx, userA, userB, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, ...*sql.Tx) bool); ok {
		r0 = returnFunc(ctx, userA, userB, tx...)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, userA, userB, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockRepository_IsBlockedEither_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsBlockedEither'
type MockBlockRepository_IsBlockedEither_Call struct {
	*mock.Call
}

// IsBlockedEither is a helper method to define mock.On call
//   - ctx context.Context
//   - userA uuid.UUID
//   - userB uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockBlockRepository_Expecter) IsBlockedEither(ctx any, userA any, userB any, tx ...any) *MockBlockRepository_IsBlockedEither_Call {
	return &MockBlockRepository_IsBlockedEither_Call{Call: _e.mock.On("IsBlockedEither",
		append([]any{ctx, userA, userB}, tx...)...)}
}

func (_c *MockBlockRepository_IsBlockedEither_Call) Run(run func(ctx context.Context, userA uuid.UUID, userB uuid.UUID, tx ...*sql.Tx)) *MockBlockRepository_IsBlockedEither_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 3 {
			variadicArgs = args[3].([]*sql.Tx)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockBlockRepository_IsBlockedEither_Call) Return(b bool, err error) *MockBlockRepository_IsBlockedEither_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockBlockRepository_IsBlockedEither_Call) RunAndReturn(run func(ctx context.Context, userA uuid.UUID, userB uuid.UUID, tx ...*sql.Tx) (bool, error)) *MockBlockRepository_IsBlockedEither_Call {
	_c.Call.Return(run)
	return _c
}

// Unblock provides a mock function for the type MockBlockRepository
func (_mock *MockBlockRepository) Unblock(ctx context.Context, blockerID uuid.UUID, blockedID uuid.UUID, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, blockerID, blockedID, tx)
	} else {
		tmpRet = _mock.Called(ctx, blockerID, blockedID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Unblock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, blockerID, blockedID, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlockRepository_Unblock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unblock'
type MockBlockRepository_Unblock_Call struct {
	*mock.Call
}

// Unblock is a helper method to define mock.On call
//   - ctx context.Context
//   - blockerID uuid.UUID
//   - blockedID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockBlockRepository_Expecter) Unblock(ctx any, blockerID any, blockedID any, tx ...any) *MockBlockRepository_Unblock_Call {
	return &MockBlockRepository_Unblock_Call{Call: _e.mock.On("Unblock",
		append([]any{ctx, blockerID, blockedID}, tx...)...)}
}

func (_c *MockBlockRepository_Unblock_Call) Run(run func(ctx context.Context, blockerID uuid.UUID, blockedID uuid.UUID, tx ...*sql.Tx)) *MockBlockRepository_Unblock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 3 {
			variadicArgs = args[3].([]*sql.Tx)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockBlockRepository_Unblock_Call) Return(err error) *MockBlockRepository_Unblock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlockRepository_Unblock_Call) RunAndReturn(run func(ctx context.Context, blockerID uuid.UUID, blockedID uuid.UUID, tx ...*sql.Tx) error) *MockBlockRepository_Unblock_Call {
	_c.Call.Return(run)
	return _c
}
