// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChatBannedWordRepository creates a new instance of MockChatBannedWordRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatBannedWordRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatBannedWordRepository {
	mock := &MockChatBannedWordRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatBannedWordRepository is an autogenerated mock type for the ChatBannedWordRepository type
type MockChatBannedWordRepository struct {
	mock.Mock
}

type MockChatBannedWordRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatBannedWordRepository) EXPECT() *MockChatBannedWordRepository_Expecter {
	return &MockChatBannedWordRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockChatBannedWordRepository
func (_mock *MockChatBannedWordRepository) Create(ctx context.Context, spec ChatBannedWordSpec, tx ...*sql.Tx) (*ChatBannedWordRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, spec, tx)
	} else {
		tmpRet = _mock.Called(ctx, spec)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *ChatBannedWordRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ChatBannedWordSpec, ...*sql.Tx) (*ChatBannedWordRow, error)); ok {
		return returnFunc(ctx, spec, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ChatBannedWordSpec, ...*sql.Tx) *ChatBannedWordRow); ok {
		r0 = returnFunc(ctx, spec, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ChatBannedWordRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ChatBannedWordSpec, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, spec, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatBannedWordRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockChatBannedWordRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - spec ChatBannedWordSpec
//   - tx ...*sql.Tx
func (_e *MockChatBannedWordRepository_Expecter) Create(ctx any, spec any, tx ...any) *MockChatBannedWordRepository_Create_Call {
	return &MockChatBannedWordRepository_Create_Call{Call: _e.mock.On("Create",
		append([]any{ctx, spec}, tx...)...)}
}

func (_c *MockChatBannedWordRepository_Create_Call) Run(run func(ctx context.Context, spec ChatBannedWordSpec, tx ...*sql.Tx)) *MockChatBannedWordRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ChatBannedWordSpec
		if args[1] != nil {
			arg1 = args[1].(ChatBannedWordSpec)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatBannedWordRepository_Create_Call) Return(chatBannedWordRow *ChatBannedWordRow, err error) *MockChatBannedWordRepository_Create_Call {
	_c.Call.Return(chatBannedWordRow, err)
	return _c
}

func (_c *MockChatBannedWordRepository_Create_Call) RunAndReturn(run func(ctx context.Context, spec ChatBannedWordSpec, tx ...*sql.Tx) (*ChatBannedWordRow, error)) *MockChatBannedWordRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithAudit provides a mock function for the type MockChatBannedWordRepository
func (_mock *MockChatBannedWordRepository) CreateWithAudit(ctx context.Context, spec ChatBannedWordSpec, audit NewAuditEntry, tx ...*sql.Tx) (*ChatBannedWordRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, spec, audit, tx)
	} else {
		tmpRet = _mock.Called(ctx, spec, audit)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateWithAudit")
	}

	var r0 *ChatBannedWordRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ChatBannedWordSpec, NewAuditEntry, ...*sql.Tx) (*ChatBannedWordRow, error)); ok {
		return returnFunc(ctx, spec, audit, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ChatBannedWordSpec, NewAuditEntry, ...*sql.Tx) *ChatBannedWordRow); ok {
		r0 = returnFunc(ctx, spec, audit, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ChatBannedWordRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ChatBannedWordSpec, NewAuditEntry, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, spec, audit, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatBannedWordRepository_CreateWithAudit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithAudit'
type MockChatBannedWordRepository_CreateWithAudit_Call struct {
	*mock.Call
}

// CreateWithAudit is a helper method to define mock.On call
//   - ctx context.Context
//   - spec ChatBannedWordSpec
//   - audit NewAuditEntry
//   - tx ...*sql.Tx
func (_e *MockChatBannedWordRepository_Expecter) CreateWithAudit(ctx any, spec any, audit any, tx ...any) *MockChatBannedWordRepository_CreateWithAudit_Call {
	return &MockChatBannedWordRepository_CreateWithAudit_Call{Call: _e.mock.On("CreateWithAudit",
		append([]any{ctx, spec, audit}, tx...)...)}
}

func (_c *MockChatBannedWordRepository_CreateWithAudit_Call) Run(run func(ctx context.Context, spec ChatBannedWordSpec, audit NewAuditEntry, tx ...*sql.Tx)) *MockChatBannedWordRepository_CreateWithAudit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ChatBannedWordSpec
		if args[1] != nil {
			arg1 = args[1].(ChatBannedWordSpec)
		}
		var arg2 NewAuditEntry
		if args[2] != nil {
			arg2 = args[2].(NewAuditEntry)
		}
		var arg3 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 3 {
			variadicArgs = args[3].([]*sql.Tx)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockChatBannedWordRepository_CreateWithAudit_Call) Return(chatBannedWordRow *ChatBannedWordRow, err error) *MockChatBannedWordRepository_CreateWithAudit_Call {
	_c.Call.Return(chatBannedWordRow, err)
	return _c
}

func (_c *MockChatBannedWordRepository_CreateWithAudit_Call) RunAndReturn(run func(ctx context.Context, spec ChatBannedWordSpec, audit NewAuditEntry, tx ...*sql.Tx) (*ChatBannedWordRow, error)) *MockChatBannedWordRepository_CreateWithAudit_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockChatBannedWordRepository
func (_mock *MockChatBannedWordRepository) Delete(ctx context.Context, id uuid.UUID, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, id, tx)
	} else {
		tmpRet = _mock.Called(ctx, id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, id, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatBannedWordRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockChatBannedWordRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockChatBannedWordRepository_Expecter) Delete(ctx any, id any, tx ...any) *MockChatBannedWordRepository_Delete_Call {
	return &MockChatBannedWordRepository_Delete_Call{Call: _e.mock.On("Delete",
		append([]any{ctx, id}, tx...)...)}
}

func (_c *MockChatBannedWordRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID, tx ...*sql.Tx)) *MockChatBannedWordRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatBannedWordRepository_Delete_Call) Return(err error) *MockChatBannedWordRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatBannedWordRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, tx ...*sql.Tx) error) *MockChatBannedWordRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWithAudit provides a mock function for the type MockChatBannedWordRepository
func (_mock *MockChatBannedWordRepository) DeleteWithAudit(ctx context.Context, id uuid.UUID, audit NewAuditEntry, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, id, audit, tx)
	} else {
		tmpRet = _mock.Called(ctx, id, audit)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteWithAudit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, NewAuditEntry, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, id, audit, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatBannedWordRepository_DeleteWithAudit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWithAudit'
type MockChatBannedWordRepository_DeleteWithAudit_Call struct {
	*mock.Call
}

// DeleteWithAudit is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - audit NewAuditEntry
//   - tx ...*sql.Tx
func (_e *MockChatBannedWordRepository_Expecter) DeleteWithAudit(ctx any, id any, audit any, tx ...any) *MockChatBannedWordRepository_DeleteWithAudit_Call {
	return &MockChatBannedWordRepository_DeleteWithAudit_Call{Call: _e.mock.On("DeleteWithAudit",
		append([]any{ctx, id, audit}, tx...)...)}
}

func (_c *MockChatBannedWordRepository_DeleteWithAudit_Call) Run(run func(ctx context.Context, id uuid.UUID, audit NewAuditEntry, tx ...*sql.Tx)) *MockChatBannedWordRepository_DeleteWithAudit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 NewAuditEntry
		if args[2] != nil {
			arg2 = args[2].(NewAuditEntry)
		}
		var arg3 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 3 {
			variadicArgs = args[3].([]*sql.Tx)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockChatBannedWordRepository_DeleteWithAudit_Call) Return(err error) *MockChatBannedWordRepository_DeleteWithAudit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatBannedWordRepository_DeleteWithAudit_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, audit NewAuditEntry, tx ...*sql.Tx) error) *MockChatBannedWordRepository_DeleteWithAudit_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockChatBannedWordRepository
func (_mock *MockChatBannedWordRepository) GetByID(ctx context.Context, id uuid.UUID, tx ...*sql.Tx) (*ChatBannedWordRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, id, tx)
	} else {
		tmpRet = _mock.Called(ctx, id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *ChatBannedWordRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) (*ChatBannedWordRow, error)); ok {
		return returnFunc(ctx, id, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) *ChatBannedWordRow); ok {
		r0 = returnFunc(ctx, id, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ChatBannedWordRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, id, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatBannedWordRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockChatBannedWordRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockChatBannedWordRepository_Expecter) GetByID(ctx any, id any, tx ...any) *MockChatBannedWordRepository_GetByID_Call {
	return &MockChatBannedWordRepository_GetByID_Call{Call: _e.mock.On("GetByID",
		append([]any{ctx, id}, tx...)...)}
}

func (_c *MockChatBannedWordRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID, tx ...*sql.Tx)) *MockChatBannedWordRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatBannedWordRepository_GetByID_Call) Return(chatBannedWordRow *ChatBannedWordRow, err error) *MockChatBannedWordRepository_GetByID_Call {
	_c.Call.Return(chatBannedWordRow, err)
	return _c
}

func (_c *MockChatBannedWordRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, tx ...*sql.Tx) (*ChatBannedWordRow, error)) *MockChatBannedWordRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListApplicable provides a mock function for the type MockChatBannedWordRepository
func (_mock *MockChatBannedWordRepository) ListApplicable(ctx context.Context, roomID uuid.UUID, tx ...*sql.Tx) ([]ChatBannedWordRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, roomID, tx)
	} else {
		tmpRet = _mock.Called(ctx, roomID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListApplicable")
	}

	var r0 []ChatBannedWordRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) ([]ChatBannedWordRow, error)); ok {
		return returnFunc(ctx, roomID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) []ChatBannedWordRow); ok {
		r0 = returnFunc(ctx, roomID, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ChatBannedWordRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, roomID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatBannedWordRepository_ListApplicable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListApplicable'
type MockChatBannedWordRepository_ListApplicable_Call struct {
	*mock.Call
}

// ListApplicable is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockChatBannedWordRepository_Expecter) ListApplicable(ctx any, roomID any, tx ...any) *MockChatBannedWordRepository_ListApplicable_Call {
	return &MockChatBannedWordRepository_ListApplicable_Call{Call: _e.mock.On("ListApplicable",
		append([]any{ctx, roomID}, tx...)...)}
}

func (_c *MockChatBannedWordRepository_ListApplicable_Call) Run(run func(ctx context.Context, roomID uuid.UUID, tx ...*sql.Tx)) *MockChatBannedWordRepository_ListApplicable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatBannedWordRepository_ListApplicable_Call) Return(chatBannedWordRows []ChatBannedWordRow, err error) *MockChatBannedWordRepository_ListApplicable_Call {
	_c.Call.Return(chatBannedWordRows, err)
	return _c
}

func (_c *MockChatBannedWordRepository_ListApplicable_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID, tx ...*sql.Tx) ([]ChatBannedWordRow, error)) *MockChatBannedWordRepository_ListApplicable_Call {
	_c.Call.Return(run)
	return _c
}

// ListForRoom provides a mock function for the type MockChatBannedWordRepository
func (_mock *MockChatBannedWordRepository) ListForRoom(ctx context.Context, roomID uuid.UUID, tx ...*sql.Tx) ([]ChatBannedWordRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, roomID, tx)
	} else {
		tmpRet = _mock.Called(ctx, roomID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListForRoom")
	}

	var r0 []ChatBannedWordRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) ([]ChatBannedWordRow, error)); ok {
		return returnFunc(ctx, roomID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) []ChatBannedWordRow); ok {
		r0 = returnFunc(ctx, roomID, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ChatBannedWordRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, roomID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatBannedWordRepository_ListForRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListForRoom'
type MockChatBannedWordRepository_ListForRoom_Call struct {
	*mock.Call
}

// ListForRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockChatBannedWordRepository_Expecter) ListForRoom(ctx any, roomID any, tx ...any) *MockChatBannedWordRepository_ListForRoom_Call {
	return &MockChatBannedWordRepository_ListForRoom_Call{Call: _e.mock.On("ListForRoom",
		append([]any{ctx, roomID}, tx...)...)}
}

func (_c *MockChatBannedWordRepository_ListForRoom_Call) Run(run func(ctx context.Context, roomID uuid.UUID, tx ...*sql.Tx)) *MockChatBannedWordRepository_ListForRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatBannedWordRepository_ListForRoom_Call) Return(chatBannedWordRows []ChatBannedWordRow, err error) *MockChatBannedWordRepository_ListForRoom_Call {
	_c.Call.Return(chatBannedWordRows, err)
	return _c
}

func (_c *MockChatBannedWordRepository_ListForRoom_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID, tx ...*sql.Tx) ([]ChatBannedWordRow, error)) *MockChatBannedWordRepository_ListForRoom_Call {
	_c.Call.Return(run)
	return _c
}

// ListGlobal provides a mock function for the type MockChatBannedWordRepository
func (_mock *MockChatBannedWordRepository) ListGlobal(ctx context.Context, tx ...*sql.Tx) ([]ChatBannedWordRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, tx)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListGlobal")
	}

	var r0 []ChatBannedWordRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*sql.Tx) ([]ChatBannedWordRow, error)); ok {
		return returnFunc(ctx, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*sql.Tx) []ChatBannedWordRow); ok {
		r0 = returnFunc(ctx, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ChatBannedWordRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatBannedWordRepository_ListGlobal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGlobal'
type MockChatBannedWordRepository_ListGlobal_Call struct {
	*mock.Call
}

// ListGlobal is a helper method to define mock.On call
//   - ctx context.Context
//   - tx ...*sql.Tx
func (_e *MockChatBannedWordRepository_Expecter) ListGlobal(ctx any, tx ...any) *MockChatBannedWordRepository_ListGlobal_Call {
	return &MockChatBannedWordRepository_ListGlobal_Call{Call: _e.mock.On("ListGlobal",
		append([]any{ctx}, tx...)...)}
}

func (_c *MockChatBannedWordRepository_ListGlobal_Call) Run(run func(ctx context.Context, tx ...*sql.Tx)) *MockChatBannedWordRepository_ListGlobal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 1 {
			variadicArgs = args[1].([]*sql.Tx)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockChatBannedWordRepository_ListGlobal_Call) Return(chatBannedWordRows []ChatBannedWordRow, err error) *MockChatBannedWordRepository_ListGlobal_Call {
	_c.Call.Return(chatBannedWordRows, err)
	return _c
}

func (_c *MockChatBannedWordRepository_ListGlobal_Call) RunAndReturn(run func(ctx context.Context, tx ...*sql.Tx) ([]ChatBannedWordRow, error)) *MockChatBannedWordRepository_ListGlobal_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockChatBannedWordRepository
func (_mock *MockChatBannedWordRepository) Update(ctx context.Context, id uuid.UUID, spec ChatBannedWordUpdate, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, id, spec, tx)
	} else {
		tmpRet = _mock.Called(ctx, id, spec)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ChatBannedWordUpdate, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, id, spec, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatBannedWordRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockChatBannedWordRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - spec ChatBannedWordUpdate
//   - tx ...*sql.Tx
func (_e *MockChatBannedWordRepository_Expecter) Update(ctx any, id any, spec any, tx ...any) *MockChatBannedWordRepository_Update_Call {
	return &MockChatBannedWordRepository_Update_Call{Call: _e.mock.On("Update",
		append([]any{ctx, id, spec}, tx...)...)}
}

func (_c *MockChatBannedWordRepository_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, spec ChatBannedWordUpdate, tx ...*sql.Tx)) *MockChatBannedWordRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 ChatBannedWordUpdate
		if args[2] != nil {
			arg2 = args[2].(ChatBannedWordUpdate)
		}
		var arg3 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 3 {
			variadicArgs = args[3].([]*sql.Tx)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockChatBannedWordRepository_Update_Call) Return(err error) *MockChatBannedWordRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatBannedWordRepository_Update_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, spec ChatBannedWordUpdate, tx ...*sql.Tx) error) *MockChatBannedWordRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
