// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChatRoomBanDAO creates a new instance of MockChatRoomBanDAO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatRoomBanDAO(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatRoomBanDAO {
	mock := &MockChatRoomBanDAO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatRoomBanDAO is an autogenerated mock type for the ChatRoomBanDAO type
type MockChatRoomBanDAO struct {
	mock.Mock
}

type MockChatRoomBanDAO_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatRoomBanDAO) EXPECT() *MockChatRoomBanDAO_Expecter {
	return &MockChatRoomBanDAO_Expecter{mock: &_m.Mock}
}

// Ban provides a mock function for the type MockChatRoomBanDAO
func (_mock *MockChatRoomBanDAO) Ban(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, bannedBy *uuid.UUID, reason string, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, roomID, userID, bannedBy, reason, tx)
	} else {
		tmpRet = _mock.Called(ctx, roomID, userID, bannedBy, reason)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Ban")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *uuid.UUID, string, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, roomID, userID, bannedBy, reason, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatRoomBanDAO_Ban_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ban'
type MockChatRoomBanDAO_Ban_Call struct {
	*mock.Call
}

// Ban is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
//   - bannedBy *uuid.UUID
//   - reason string
//   - tx ...*sql.Tx
func (_e *MockChatRoomBanDAO_Expecter) Ban(ctx any, roomID any, userID any, bannedBy any, reason any, tx ...any) *MockChatRoomBanDAO_Ban_Call {
	return &MockChatRoomBanDAO_Ban_Call{Call: _e.mock.On("Ban",
		append([]any{ctx, roomID, userID, bannedBy, reason}, tx...)...)}
}

func (_c *MockChatRoomBanDAO_Ban_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, bannedBy *uuid.UUID, reason string, tx ...*sql.Tx)) *MockChatRoomBanDAO_Ban_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 *uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(*uuid.UUID)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 5 {
			variadicArgs = args[5].([]*sql.Tx)
		}
		arg5 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5...,
		)
	})
	return _c
}

func (_c *MockChatRoomBanDAO_Ban_Call) Return(err error) *MockChatRoomBanDAO_Ban_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatRoomBanDAO_Ban_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, bannedBy *uuid.UUID, reason string, tx ...*sql.Tx) error) *MockChatRoomBanDAO_Ban_Call {
	_c.Call.Return(run)
	return _c
}

// BannedRoomIDsForUser provides a mock function for the type MockChatRoomBanDAO
func (_mock *MockChatRoomBanDAO) BannedRoomIDsForUser(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx) ([]uuid.UUID, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, userID, tx)
	} else {
		tmpRet = _mock.Called(ctx, userID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for BannedRoomIDsForUser")
	}

	var r0 []uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) ([]uuid.UUID, error)); ok {
		return returnFunc(ctx, userID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) []uuid.UUID); ok {
		r0 = returnFunc(ctx, userID, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, userID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatRoomBanDAO_BannedRoomIDsForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BannedRoomIDsForUser'
type MockChatRoomBanDAO_BannedRoomIDsForUser_Call struct {
	*mock.Call
}

// BannedRoomIDsForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockChatRoomBanDAO_Expecter) BannedRoomIDsForUser(ctx any, userID any, tx ...any) *MockChatRoomBanDAO_BannedRoomIDsForUser_Call {
	return &MockChatRoomBanDAO_BannedRoomIDsForUser_Call{Call: _e.mock.On("BannedRoomIDsForUser",
		append([]any{ctx, userID}, tx...)...)}
}

func (_c *MockChatRoomBanDAO_BannedRoomIDsForUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx)) *MockChatRoomBanDAO_BannedRoomIDsForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatRoomBanDAO_BannedRoomIDsForUser_Call) Return(uUIDs []uuid.UUID, err error) *MockChatRoomBanDAO_BannedRoomIDsForUser_Call {
	_c.Call.Return(uUIDs, err)
	return _c
}

func (_c *MockChatRoomBanDAO_BannedRoomIDsForUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx) ([]uuid.UUID, error)) *MockChatRoomBanDAO_BannedRoomIDsForUser_Call {
	_c.Call.Return(run)
	return _c
}

// IsBanned provides a mock function for the type MockChatRoomBanDAO
func (_mock *MockChatRoomBanDAO) IsBanned(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, tx ...*sql.Tx) (bool, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, roomID, userID, tx)
	} else {
		tmpRet = _mock.Called(ctx, roomID, userID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for IsBanned")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, ...*sql.Tx) (bool, error)); ok {
		return returnFunc(ctx, roomID, userID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, ...*sql.Tx) bool); ok {
		r0 = returnFunc(ctx, roomID, userID, tx...)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, roomID, userID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatRoomBanDAO_IsBanned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsBanned'
type MockChatRoomBanDAO_IsBanned_Call struct {
	*mock.Call
}

// IsBanned is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockChatRoomBanDAO_Expecter) IsBanned(ctx any, roomID any, userID any, tx ...any) *MockChatRoomBanDAO_IsBanned_Call {
	return &MockChatRoomBanDAO_IsBanned_Call{Call: _e.mock.On("IsBanned",
		append([]any{ctx, roomID, userID}, tx...)...)}
}

func (_c *MockChatRoomBanDAO_IsBanned_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, tx ...*sql.Tx)) *MockChatRoomBanDAO_IsBanned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 3 {
			variadicArgs = args[3].([]*sql.Tx)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockChatRoomBanDAO_IsBanned_Call) Return(b bool, err error) *MockChatRoomBanDAO_IsBanned_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockChatRoomBanDAO_IsBanned_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, tx ...*sql.Tx) (bool, error)) *MockChatRoomBanDAO_IsBanned_Call {
	_c.Call.Return(run)
	return _c
}

// ListForRoom provides a mock function for the type MockChatRoomBanDAO
func (_mock *MockChatRoomBanDAO) ListForRoom(ctx context.Context, roomID uuid.UUID, tx ...*sql.Tx) ([]ChatRoomBanRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, roomID, tx)
	} else {
		tmpRet = _mock.Called(ctx, roomID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListForRoom")
	}

	var r0 []ChatRoomBanRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) ([]ChatRoomBanRow, error)); ok {
		return returnFunc(ctx, roomID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) []ChatRoomBanRow); ok {
		r0 = returnFunc(ctx, roomID, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ChatRoomBanRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, roomID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatRoomBanDAO_ListForRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListForRoom'
type MockChatRoomBanDAO_ListForRoom_Call struct {
	*mock.Call
}

// ListForRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockChatRoomBanDAO_Expecter) ListForRoom(ctx any, roomID any, tx ...any) *MockChatRoomBanDAO_ListForRoom_Call {
	return &MockChatRoomBanDAO_ListForRoom_Call{Call: _e.mock.On("ListForRoom",
		append([]any{ctx, roomID}, tx...)...)}
}

func (_c *MockChatRoomBanDAO_ListForRoom_Call) Run(run func(ctx context.Context, roomID uuid.UUID, tx ...*sql.Tx)) *MockChatRoomBanDAO_ListForRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatRoomBanDAO_ListForRoom_Call) Return(chatRoomBanRows []ChatRoomBanRow, err error) *MockChatRoomBanDAO_ListForRoom_Call {
	_c.Call.Return(chatRoomBanRows, err)
	return _c
}

func (_c *MockChatRoomBanDAO_ListForRoom_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID, tx ...*sql.Tx) ([]ChatRoomBanRow, error)) *MockChatRoomBanDAO_ListForRoom_Call {
	_c.Call.Return(run)
	return _c
}

// Unban provides a mock function for the type MockChatRoomBanDAO
func (_mock *MockChatRoomBanDAO) Unban(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, roomID, userID, tx)
	} else {
		tmpRet = _mock.Called(ctx, roomID, userID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Unban")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, roomID, userID, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatRoomBanDAO_Unban_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unban'
type MockChatRoomBanDAO_Unban_Call struct {
	*mock.Call
}

// Unban is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockChatRoomBanDAO_Expecter) Unban(ctx any, roomID any, userID any, tx ...any) *MockChatRoomBanDAO_Unban_Call {
	return &MockChatRoomBanDAO_Unban_Call{Call: _e.mock.On("Unban",
		append([]any{ctx, roomID, userID}, tx...)...)}
}

func (_c *MockChatRoomBanDAO_Unban_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, tx ...*sql.Tx)) *MockChatRoomBanDAO_Unban_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 3 {
			variadicArgs = args[3].([]*sql.Tx)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockChatRoomBanDAO_Unban_Call) Return(err error) *MockChatRoomBanDAO_Unban_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatRoomBanDAO_Unban_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID, tx ...*sql.Tx) error) *MockChatRoomBanDAO_Unban_Call {
	_c.Call.Return(run)
	return _c
}
