// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChatbotDAO creates a new instance of MockChatbotDAO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatbotDAO(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatbotDAO {
	mock := &MockChatbotDAO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatbotDAO is an autogenerated mock type for the ChatbotDAO type
type MockChatbotDAO struct {
	mock.Mock
}

type MockChatbotDAO_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatbotDAO) EXPECT() *MockChatbotDAO_Expecter {
	return &MockChatbotDAO_Expecter{mock: &_m.Mock}
}

// CompleteInvocation provides a mock function for the type MockChatbotDAO
func (_mock *MockChatbotDAO) CompleteInvocation(ctx context.Context, id uuid.UUID, usage InvocationUsage, status InvocationStatus, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, id, usage, status, tx)
	} else {
		tmpRet = _mock.Called(ctx, id, usage, status)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CompleteInvocation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, InvocationUsage, InvocationStatus, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, id, usage, status, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatbotDAO_CompleteInvocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteInvocation'
type MockChatbotDAO_CompleteInvocation_Call struct {
	*mock.Call
}

// CompleteInvocation is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - usage InvocationUsage
//   - status InvocationStatus
//   - tx ...*sql.Tx
func (_e *MockChatbotDAO_Expecter) CompleteInvocation(ctx any, id any, usage any, status any, tx ...any) *MockChatbotDAO_CompleteInvocation_Call {
	return &MockChatbotDAO_CompleteInvocation_Call{Call: _e.mock.On("CompleteInvocation",
		append([]any{ctx, id, usage, status}, tx...)...)}
}

func (_c *MockChatbotDAO_CompleteInvocation_Call) Run(run func(ctx context.Context, id uuid.UUID, usage InvocationUsage, status InvocationStatus, tx ...*sql.Tx)) *MockChatbotDAO_CompleteInvocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 InvocationUsage
		if args[2] != nil {
			arg2 = args[2].(InvocationUsage)
		}
		var arg3 InvocationStatus
		if args[3] != nil {
			arg3 = args[3].(InvocationStatus)
		}
		var arg4 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 4 {
			variadicArgs = args[4].([]*sql.Tx)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockChatbotDAO_CompleteInvocation_Call) Return(err error) *MockChatbotDAO_CompleteInvocation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatbotDAO_CompleteInvocation_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, usage InvocationUsage, status InvocationStatus, tx ...*sql.Tx) error) *MockChatbotDAO_CompleteInvocation_Call {
	_c.Call.Return(run)
	return _c
}

// CountInvocationsToday provides a mock function for the type MockChatbotDAO
func (_mock *MockChatbotDAO) CountInvocationsToday(ctx context.Context, tx ...*sql.Tx) (int, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, tx)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CountInvocationsToday")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*sql.Tx) (int, error)); ok {
		return returnFunc(ctx, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*sql.Tx) int); ok {
		r0 = returnFunc(ctx, tx...)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatbotDAO_CountInvocationsToday_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountInvocationsToday'
type MockChatbotDAO_CountInvocationsToday_Call struct {
	*mock.Call
}

// CountInvocationsToday is a helper method to define mock.On call
//   - ctx context.Context
//   - tx ...*sql.Tx
func (_e *MockChatbotDAO_Expecter) CountInvocationsToday(ctx any, tx ...any) *MockChatbotDAO_CountInvocationsToday_Call {
	return &MockChatbotDAO_CountInvocationsToday_Call{Call: _e.mock.On("CountInvocationsToday",
		append([]any{ctx}, tx...)...)}
}

func (_c *MockChatbotDAO_CountInvocationsToday_Call) Run(run func(ctx context.Context, tx ...*sql.Tx)) *MockChatbotDAO_CountInvocationsToday_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 1 {
			variadicArgs = args[1].([]*sql.Tx)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockChatbotDAO_CountInvocationsToday_Call) Return(n int, err error) *MockChatbotDAO_CountInvocationsToday_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockChatbotDAO_CountInvocationsToday_Call) RunAndReturn(run func(ctx context.Context, tx ...*sql.Tx) (int, error)) *MockChatbotDAO_CountInvocationsToday_Call {
	_c.Call.Return(run)
	return _c
}

// CountUserInvocationsToday provides a mock function for the type MockChatbotDAO
func (_mock *MockChatbotDAO) CountUserInvocationsToday(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx) (int, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, userID, tx)
	} else {
		tmpRet = _mock.Called(ctx, userID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CountUserInvocationsToday")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) (int, error)); ok {
		return returnFunc(ctx, userID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) int); ok {
		r0 = returnFunc(ctx, userID, tx...)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, userID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatbotDAO_CountUserInvocationsToday_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountUserInvocationsToday'
type MockChatbotDAO_CountUserInvocationsToday_Call struct {
	*mock.Call
}

// CountUserInvocationsToday is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockChatbotDAO_Expecter) CountUserInvocationsToday(ctx any, userID any, tx ...any) *MockChatbotDAO_CountUserInvocationsToday_Call {
	return &MockChatbotDAO_CountUserInvocationsToday_Call{Call: _e.mock.On("CountUserInvocationsToday",
		append([]any{ctx, userID}, tx...)...)}
}

func (_c *MockChatbotDAO_CountUserInvocationsToday_Call) Run(run func(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx)) *MockChatbotDAO_CountUserInvocationsToday_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatbotDAO_CountUserInvocationsToday_Call) Return(n int, err error) *MockChatbotDAO_CountUserInvocationsToday_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockChatbotDAO_CountUserInvocationsToday_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx) (int, error)) *MockChatbotDAO_CountUserInvocationsToday_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBot provides a mock function for the type MockChatbotDAO
func (_mock *MockChatbotDAO) CreateBot(ctx context.Context, bot Chatbot, tx ...*sql.Tx) (*Chatbot, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, bot, tx)
	} else {
		tmpRet = _mock.Called(ctx, bot)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateBot")
	}

	var r0 *Chatbot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Chatbot, ...*sql.Tx) (*Chatbot, error)); ok {
		return returnFunc(ctx, bot, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Chatbot, ...*sql.Tx) *Chatbot); ok {
		r0 = returnFunc(ctx, bot, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Chatbot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Chatbot, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, bot, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatbotDAO_CreateBot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBot'
type MockChatbotDAO_CreateBot_Call struct {
	*mock.Call
}

// CreateBot is a helper method to define mock.On call
//   - ctx context.Context
//   - bot Chatbot
//   - tx ...*sql.Tx
func (_e *MockChatbotDAO_Expecter) CreateBot(ctx any, bot any, tx ...any) *MockChatbotDAO_CreateBot_Call {
	return &MockChatbotDAO_CreateBot_Call{Call: _e.mock.On("CreateBot",
		append([]any{ctx, bot}, tx...)...)}
}

func (_c *MockChatbotDAO_CreateBot_Call) Run(run func(ctx context.Context, bot Chatbot, tx ...*sql.Tx)) *MockChatbotDAO_CreateBot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Chatbot
		if args[1] != nil {
			arg1 = args[1].(Chatbot)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatbotDAO_CreateBot_Call) Return(chatbot *Chatbot, err error) *MockChatbotDAO_CreateBot_Call {
	_c.Call.Return(chatbot, err)
	return _c
}

func (_c *MockChatbotDAO_CreateBot_Call) RunAndReturn(run func(ctx context.Context, bot Chatbot, tx ...*sql.Tx) (*Chatbot, error)) *MockChatbotDAO_CreateBot_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInvocation provides a mock function for the type MockChatbotDAO
func (_mock *MockChatbotDAO) CreateInvocation(ctx context.Context, spec NewInvocation, tx ...*sql.Tx) (*ChatbotInvocation, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, spec, tx)
	} else {
		tmpRet = _mock.Called(ctx, spec)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateInvocation")
	}

	var r0 *ChatbotInvocation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, NewInvocation, ...*sql.Tx) (*ChatbotInvocation, error)); ok {
		return returnFunc(ctx, spec, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, NewInvocation, ...*sql.Tx) *ChatbotInvocation); ok {
		r0 = returnFunc(ctx, spec, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ChatbotInvocation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, NewInvocation, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, spec, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatbotDAO_CreateInvocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInvocation'
type MockChatbotDAO_CreateInvocation_Call struct {
	*mock.Call
}

// CreateInvocation is a helper method to define mock.On call
//   - ctx context.Context
//   - spec NewInvocation
//   - tx ...*sql.Tx
func (_e *MockChatbotDAO_Expecter) CreateInvocation(ctx any, spec any, tx ...any) *MockChatbotDAO_CreateInvocation_Call {
	return &MockChatbotDAO_CreateInvocation_Call{Call: _e.mock.On("CreateInvocation",
		append([]any{ctx, spec}, tx...)...)}
}

func (_c *MockChatbotDAO_CreateInvocation_Call) Run(run func(ctx context.Context, spec NewInvocation, tx ...*sql.Tx)) *MockChatbotDAO_CreateInvocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 NewInvocation
		if args[1] != nil {
			arg1 = args[1].(NewInvocation)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatbotDAO_CreateInvocation_Call) Return(chatbotInvocation *ChatbotInvocation, err error) *MockChatbotDAO_CreateInvocation_Call {
	_c.Call.Return(chatbotInvocation, err)
	return _c
}

func (_c *MockChatbotDAO_CreateInvocation_Call) RunAndReturn(run func(ctx context.Context, spec NewInvocation, tx ...*sql.Tx) (*ChatbotInvocation, error)) *MockChatbotDAO_CreateInvocation_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBot provides a mock function for the type MockChatbotDAO
func (_mock *MockChatbotDAO) DeleteBot(ctx context.Context, id uuid.UUID, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, id, tx)
	} else {
		tmpRet = _mock.Called(ctx, id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteBot")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, id, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatbotDAO_DeleteBot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBot'
type MockChatbotDAO_DeleteBot_Call struct {
	*mock.Call
}

// DeleteBot is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockChatbotDAO_Expecter) DeleteBot(ctx any, id any, tx ...any) *MockChatbotDAO_DeleteBot_Call {
	return &MockChatbotDAO_DeleteBot_Call{Call: _e.mock.On("DeleteBot",
		append([]any{ctx, id}, tx...)...)}
}

func (_c *MockChatbotDAO_DeleteBot_Call) Run(run func(ctx context.Context, id uuid.UUID, tx ...*sql.Tx)) *MockChatbotDAO_DeleteBot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatbotDAO_DeleteBot_Call) Return(err error) *MockChatbotDAO_DeleteBot_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatbotDAO_DeleteBot_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, tx ...*sql.Tx) error) *MockChatbotDAO_DeleteBot_Call {
	_c.Call.Return(run)
	return _c
}

// GetBotByUserID provides a mock function for the type MockChatbotDAO
func (_mock *MockChatbotDAO) GetBotByUserID(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx) (*Chatbot, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, userID, tx)
	} else {
		tmpRet = _mock.Called(ctx, userID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetBotByUserID")
	}

	var r0 *Chatbot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) (*Chatbot, error)); ok {
		return returnFunc(ctx, userID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) *Chatbot); ok {
		r0 = returnFunc(ctx, userID, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Chatbot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, userID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatbotDAO_GetBotByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBotByUserID'
type MockChatbotDAO_GetBotByUserID_Call struct {
	*mock.Call
}

// GetBotByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockChatbotDAO_Expecter) GetBotByUserID(ctx any, userID any, tx ...any) *MockChatbotDAO_GetBotByUserID_Call {
	return &MockChatbotDAO_GetBotByUserID_Call{Call: _e.mock.On("GetBotByUserID",
		append([]any{ctx, userID}, tx...)...)}
}

func (_c *MockChatbotDAO_GetBotByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx)) *MockChatbotDAO_GetBotByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatbotDAO_GetBotByUserID_Call) Return(chatbot *Chatbot, err error) *MockChatbotDAO_GetBotByUserID_Call {
	_c.Call.Return(chatbot, err)
	return _c
}

func (_c *MockChatbotDAO_GetBotByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx) (*Chatbot, error)) *MockChatbotDAO_GetBotByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ListBots provides a mock function for the type MockChatbotDAO
func (_mock *MockChatbotDAO) ListBots(ctx context.Context, tx ...*sql.Tx) ([]Chatbot, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, tx)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListBots")
	}

	var r0 []Chatbot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*sql.Tx) ([]Chatbot, error)); ok {
		return returnFunc(ctx, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*sql.Tx) []Chatbot); ok {
		r0 = returnFunc(ctx, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Chatbot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatbotDAO_ListBots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBots'
type MockChatbotDAO_ListBots_Call struct {
	*mock.Call
}

// ListBots is a helper method to define mock.On call
//   - ctx context.Context
//   - tx ...*sql.Tx
func (_e *MockChatbotDAO_Expecter) ListBots(ctx any, tx ...any) *MockChatbotDAO_ListBots_Call {
	return &MockChatbotDAO_ListBots_Call{Call: _e.mock.On("ListBots",
		append([]any{ctx}, tx...)...)}
}

func (_c *MockChatbotDAO_ListBots_Call) Run(run func(ctx context.Context, tx ...*sql.Tx)) *MockChatbotDAO_ListBots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 1 {
			variadicArgs = args[1].([]*sql.Tx)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockChatbotDAO_ListBots_Call) Return(chatbots []Chatbot, err error) *MockChatbotDAO_ListBots_Call {
	_c.Call.Return(chatbots, err)
	return _c
}

func (_c *MockChatbotDAO_ListBots_Call) RunAndReturn(run func(ctx context.Context, tx ...*sql.Tx) ([]Chatbot, error)) *MockChatbotDAO_ListBots_Call {
	_c.Call.Return(run)
	return _c
}

// OldestInvocationToday provides a mock function for the type MockChatbotDAO
func (_mock *MockChatbotDAO) OldestInvocationToday(ctx context.Context, tx ...*sql.Tx) (time.Time, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, tx)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for OldestInvocationToday")
	}

	var r0 time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*sql.Tx) (time.Time, error)); ok {
		return returnFunc(ctx, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*sql.Tx) time.Time); ok {
		r0 = returnFunc(ctx, tx...)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatbotDAO_OldestInvocationToday_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OldestInvocationToday'
type MockChatbotDAO_OldestInvocationToday_Call struct {
	*mock.Call
}

// OldestInvocationToday is a helper method to define mock.On call
//   - ctx context.Context
//   - tx ...*sql.Tx
func (_e *MockChatbotDAO_Expecter) OldestInvocationToday(ctx any, tx ...any) *MockChatbotDAO_OldestInvocationToday_Call {
	return &MockChatbotDAO_OldestInvocationToday_Call{Call: _e.mock.On("OldestInvocationToday",
		append([]any{ctx}, tx...)...)}
}

func (_c *MockChatbotDAO_OldestInvocationToday_Call) Run(run func(ctx context.Context, tx ...*sql.Tx)) *MockChatbotDAO_OldestInvocationToday_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 1 {
			variadicArgs = args[1].([]*sql.Tx)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockChatbotDAO_OldestInvocationToday_Call) Return(time1 time.Time, err error) *MockChatbotDAO_OldestInvocationToday_Call {
	_c.Call.Return(time1, err)
	return _c
}

func (_c *MockChatbotDAO_OldestInvocationToday_Call) RunAndReturn(run func(ctx context.Context, tx ...*sql.Tx) (time.Time, error)) *MockChatbotDAO_OldestInvocationToday_Call {
	_c.Call.Return(run)
	return _c
}

// OldestUserInvocationToday provides a mock function for the type MockChatbotDAO
func (_mock *MockChatbotDAO) OldestUserInvocationToday(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx) (time.Time, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, userID, tx)
	} else {
		tmpRet = _mock.Called(ctx, userID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for OldestUserInvocationToday")
	}

	var r0 time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) (time.Time, error)); ok {
		return returnFunc(ctx, userID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) time.Time); ok {
		r0 = returnFunc(ctx, userID, tx...)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, userID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatbotDAO_OldestUserInvocationToday_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OldestUserInvocationToday'
type MockChatbotDAO_OldestUserInvocationToday_Call struct {
	*mock.Call
}

// OldestUserInvocationToday is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockChatbotDAO_Expecter) OldestUserInvocationToday(ctx any, userID any, tx ...any) *MockChatbotDAO_OldestUserInvocationToday_Call {
	return &MockChatbotDAO_OldestUserInvocationToday_Call{Call: _e.mock.On("OldestUserInvocationToday",
		append([]any{ctx, userID}, tx...)...)}
}

func (_c *MockChatbotDAO_OldestUserInvocationToday_Call) Run(run func(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx)) *MockChatbotDAO_OldestUserInvocationToday_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatbotDAO_OldestUserInvocationToday_Call) Return(time1 time.Time, err error) *MockChatbotDAO_OldestUserInvocationToday_Call {
	_c.Call.Return(time1, err)
	return _c
}

func (_c *MockChatbotDAO_OldestUserInvocationToday_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx) (time.Time, error)) *MockChatbotDAO_OldestUserInvocationToday_Call {
	_c.Call.Return(run)
	return _c
}

// StatsSince provides a mock function for the type MockChatbotDAO
func (_mock *MockChatbotDAO) StatsSince(ctx context.Context, since time.Time, tx ...*sql.Tx) (*ChatbotStats, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, since, tx)
	} else {
		tmpRet = _mock.Called(ctx, since)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for StatsSince")
	}

	var r0 *ChatbotStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, ...*sql.Tx) (*ChatbotStats, error)); ok {
		return returnFunc(ctx, since, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, ...*sql.Tx) *ChatbotStats); ok {
		r0 = returnFunc(ctx, since, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ChatbotStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, since, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatbotDAO_StatsSince_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatsSince'
type MockChatbotDAO_StatsSince_Call struct {
	*mock.Call
}

// StatsSince is a helper method to define mock.On call
//   - ctx context.Context
//   - since time.Time
//   - tx ...*sql.Tx
func (_e *MockChatbotDAO_Expecter) StatsSince(ctx any, since any, tx ...any) *MockChatbotDAO_StatsSince_Call {
	return &MockChatbotDAO_StatsSince_Call{Call: _e.mock.On("StatsSince",
		append([]any{ctx, since}, tx...)...)}
}

func (_c *MockChatbotDAO_StatsSince_Call) Run(run func(ctx context.Context, since time.Time, tx ...*sql.Tx)) *MockChatbotDAO_StatsSince_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatbotDAO_StatsSince_Call) Return(chatbotStats *ChatbotStats, err error) *MockChatbotDAO_StatsSince_Call {
	_c.Call.Return(chatbotStats, err)
	return _c
}

func (_c *MockChatbotDAO_StatsSince_Call) RunAndReturn(run func(ctx context.Context, since time.Time, tx ...*sql.Tx) (*ChatbotStats, error)) *MockChatbotDAO_StatsSince_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBot provides a mock function for the type MockChatbotDAO
func (_mock *MockChatbotDAO) UpdateBot(ctx context.Context, bot Chatbot, tx ...*sql.Tx) (*Chatbot, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, bot, tx)
	} else {
		tmpRet = _mock.Called(ctx, bot)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateBot")
	}

	var r0 *Chatbot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Chatbot, ...*sql.Tx) (*Chatbot, error)); ok {
		return returnFunc(ctx, bot, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Chatbot, ...*sql.Tx) *Chatbot); ok {
		r0 = returnFunc(ctx, bot, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Chatbot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Chatbot, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, bot, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatbotDAO_UpdateBot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBot'
type MockChatbotDAO_UpdateBot_Call struct {
	*mock.Call
}

// UpdateBot is a helper method to define mock.On call
//   - ctx context.Context
//   - bot Chatbot
//   - tx ...*sql.Tx
func (_e *MockChatbotDAO_Expecter) UpdateBot(ctx any, bot any, tx ...any) *MockChatbotDAO_UpdateBot_Call {
	return &MockChatbotDAO_UpdateBot_Call{Call: _e.mock.On("UpdateBot",
		append([]any{ctx, bot}, tx...)...)}
}

func (_c *MockChatbotDAO_UpdateBot_Call) Run(run func(ctx context.Context, bot Chatbot, tx ...*sql.Tx)) *MockChatbotDAO_UpdateBot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Chatbot
		if args[1] != nil {
			arg1 = args[1].(Chatbot)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatbotDAO_UpdateBot_Call) Return(chatbot *Chatbot, err error) *MockChatbotDAO_UpdateBot_Call {
	_c.Call.Return(chatbot, err)
	return _c
}

func (_c *MockChatbotDAO_UpdateBot_Call) RunAndReturn(run func(ctx context.Context, bot Chatbot, tx ...*sql.Tx) (*Chatbot, error)) *MockChatbotDAO_UpdateBot_Call {
	_c.Call.Return(run)
	return _c
}
