// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChatbotBasePromptRepository creates a new instance of MockChatbotBasePromptRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatbotBasePromptRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatbotBasePromptRepository {
	mock := &MockChatbotBasePromptRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatbotBasePromptRepository is an autogenerated mock type for the ChatbotBasePromptRepository type
type MockChatbotBasePromptRepository struct {
	mock.Mock
}

type MockChatbotBasePromptRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatbotBasePromptRepository) EXPECT() *MockChatbotBasePromptRepository_Expecter {
	return &MockChatbotBasePromptRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockChatbotBasePromptRepository
func (_mock *MockChatbotBasePromptRepository) Create(ctx context.Context, prompt ChatbotBasePrompt) error {
	ret := _mock.Called(ctx, prompt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ChatbotBasePrompt) error); ok {
		r0 = returnFunc(ctx, prompt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatbotBasePromptRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockChatbotBasePromptRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - prompt ChatbotBasePrompt
func (_e *MockChatbotBasePromptRepository_Expecter) Create(ctx any, prompt any) *MockChatbotBasePromptRepository_Create_Call {
	return &MockChatbotBasePromptRepository_Create_Call{Call: _e.mock.On("Create", ctx, prompt)}
}

func (_c *MockChatbotBasePromptRepository_Create_Call) Run(run func(ctx context.Context, prompt ChatbotBasePrompt)) *MockChatbotBasePromptRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ChatbotBasePrompt
		if args[1] != nil {
			arg1 = args[1].(ChatbotBasePrompt)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatbotBasePromptRepository_Create_Call) Return(err error) *MockChatbotBasePromptRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatbotBasePromptRepository_Create_Call) RunAndReturn(run func(ctx context.Context, prompt ChatbotBasePrompt) error) *MockChatbotBasePromptRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockChatbotBasePromptRepository
func (_mock *MockChatbotBasePromptRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatbotBasePromptRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockChatbotBasePromptRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockChatbotBasePromptRepository_Expecter) Delete(ctx any, id any) *MockChatbotBasePromptRepository_Delete_Call {
	return &MockChatbotBasePromptRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockChatbotBasePromptRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockChatbotBasePromptRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatbotBasePromptRepository_Delete_Call) Return(err error) *MockChatbotBasePromptRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatbotBasePromptRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockChatbotBasePromptRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockChatbotBasePromptRepository
func (_mock *MockChatbotBasePromptRepository) GetByID(ctx context.Context, id uuid.UUID) (*ChatbotBasePrompt, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *ChatbotBasePrompt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*ChatbotBasePrompt, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *ChatbotBasePrompt); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ChatbotBasePrompt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatbotBasePromptRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockChatbotBasePromptRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockChatbotBasePromptRepository_Expecter) GetByID(ctx any, id any) *MockChatbotBasePromptRepository_GetByID_Call {
	return &MockChatbotBasePromptRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockChatbotBasePromptRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockChatbotBasePromptRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatbotBasePromptRepository_GetByID_Call) Return(chatbotBasePrompt *ChatbotBasePrompt, err error) *MockChatbotBasePromptRepository_GetByID_Call {
	_c.Call.Return(chatbotBasePrompt, err)
	return _c
}

func (_c *MockChatbotBasePromptRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*ChatbotBasePrompt, error)) *MockChatbotBasePromptRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockChatbotBasePromptRepository
func (_mock *MockChatbotBasePromptRepository) List(ctx context.Context) ([]ChatbotBasePrompt, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []ChatbotBasePrompt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]ChatbotBasePrompt, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []ChatbotBasePrompt); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ChatbotBasePrompt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatbotBasePromptRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockChatbotBasePromptRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockChatbotBasePromptRepository_Expecter) List(ctx any) *MockChatbotBasePromptRepository_List_Call {
	return &MockChatbotBasePromptRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockChatbotBasePromptRepository_List_Call) Run(run func(ctx context.Context)) *MockChatbotBasePromptRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChatbotBasePromptRepository_List_Call) Return(chatbotBasePrompts []ChatbotBasePrompt, err error) *MockChatbotBasePromptRepository_List_Call {
	_c.Call.Return(chatbotBasePrompts, err)
	return _c
}

func (_c *MockChatbotBasePromptRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]ChatbotBasePrompt, error)) *MockChatbotBasePromptRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockChatbotBasePromptRepository
func (_mock *MockChatbotBasePromptRepository) Update(ctx context.Context, prompt ChatbotBasePrompt) error {
	ret := _mock.Called(ctx, prompt)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ChatbotBasePrompt) error); ok {
		r0 = returnFunc(ctx, prompt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatbotBasePromptRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockChatbotBasePromptRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - prompt ChatbotBasePrompt
func (_e *MockChatbotBasePromptRepository_Expecter) Update(ctx any, prompt any) *MockChatbotBasePromptRepository_Update_Call {
	return &MockChatbotBasePromptRepository_Update_Call{Call: _e.mock.On("Update", ctx, prompt)}
}

func (_c *MockChatbotBasePromptRepository_Update_Call) Run(run func(ctx context.Context, prompt ChatbotBasePrompt)) *MockChatbotBasePromptRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ChatbotBasePrompt
		if args[1] != nil {
			arg1 = args[1].(ChatbotBasePrompt)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatbotBasePromptRepository_Update_Call) Return(err error) *MockChatbotBasePromptRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatbotBasePromptRepository_Update_Call) RunAndReturn(run func(ctx context.Context, prompt ChatbotBasePrompt) error) *MockChatbotBasePromptRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
