// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHomeFeedRepository creates a new instance of MockHomeFeedRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHomeFeedRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHomeFeedRepository {
	mock := &MockHomeFeedRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHomeFeedRepository is an autogenerated mock type for the HomeFeedRepository type
type MockHomeFeedRepository struct {
	mock.Mock
}

type MockHomeFeedRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHomeFeedRepository) EXPECT() *MockHomeFeedRepository_Expecter {
	return &MockHomeFeedRepository_Expecter{mock: &_m.Mock}
}

// ListCornerActivity24h provides a mock function for the type MockHomeFeedRepository
func (_mock *MockHomeFeedRepository) ListCornerActivity24h(ctx context.Context) ([]HomeCornerActivityRow, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListCornerActivity24h")
	}

	var r0 []HomeCornerActivityRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]HomeCornerActivityRow, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []HomeCornerActivityRow); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]HomeCornerActivityRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHomeFeedRepository_ListCornerActivity24h_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCornerActivity24h'
type MockHomeFeedRepository_ListCornerActivity24h_Call struct {
	*mock.Call
}

// ListCornerActivity24h is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHomeFeedRepository_Expecter) ListCornerActivity24h(ctx interface{}) *MockHomeFeedRepository_ListCornerActivity24h_Call {
	return &MockHomeFeedRepository_ListCornerActivity24h_Call{Call: _e.mock.On("ListCornerActivity24h", ctx)}
}

func (_c *MockHomeFeedRepository_ListCornerActivity24h_Call) Run(run func(ctx context.Context)) *MockHomeFeedRepository_ListCornerActivity24h_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHomeFeedRepository_ListCornerActivity24h_Call) Return(homeCornerActivityRows []HomeCornerActivityRow, err error) *MockHomeFeedRepository_ListCornerActivity24h_Call {
	_c.Call.Return(homeCornerActivityRows, err)
	return _c
}

func (_c *MockHomeFeedRepository_ListCornerActivity24h_Call) RunAndReturn(run func(ctx context.Context) ([]HomeCornerActivityRow, error)) *MockHomeFeedRepository_ListCornerActivity24h_Call {
	_c.Call.Return(run)
	return _c
}

// ListPublicRooms provides a mock function for the type MockHomeFeedRepository
func (_mock *MockHomeFeedRepository) ListPublicRooms(ctx context.Context, limit int) ([]HomePublicRoomRow, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListPublicRooms")
	}

	var r0 []HomePublicRoomRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]HomePublicRoomRow, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []HomePublicRoomRow); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]HomePublicRoomRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHomeFeedRepository_ListPublicRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPublicRooms'
type MockHomeFeedRepository_ListPublicRooms_Call struct {
	*mock.Call
}

// ListPublicRooms is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockHomeFeedRepository_Expecter) ListPublicRooms(ctx interface{}, limit interface{}) *MockHomeFeedRepository_ListPublicRooms_Call {
	return &MockHomeFeedRepository_ListPublicRooms_Call{Call: _e.mock.On("ListPublicRooms", ctx, limit)}
}

func (_c *MockHomeFeedRepository_ListPublicRooms_Call) Run(run func(ctx context.Context, limit int)) *MockHomeFeedRepository_ListPublicRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHomeFeedRepository_ListPublicRooms_Call) Return(homePublicRoomRows []HomePublicRoomRow, err error) *MockHomeFeedRepository_ListPublicRooms_Call {
	_c.Call.Return(homePublicRoomRows, err)
	return _c
}

func (_c *MockHomeFeedRepository_ListPublicRooms_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]HomePublicRoomRow, error)) *MockHomeFeedRepository_ListPublicRooms_Call {
	_c.Call.Return(run)
	return _c
}

// ListRecentActivity provides a mock function for the type MockHomeFeedRepository
func (_mock *MockHomeFeedRepository) ListRecentActivity(ctx context.Context, limit int) ([]HomeActivityRow, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListRecentActivity")
	}

	var r0 []HomeActivityRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]HomeActivityRow, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []HomeActivityRow); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]HomeActivityRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHomeFeedRepository_ListRecentActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRecentActivity'
type MockHomeFeedRepository_ListRecentActivity_Call struct {
	*mock.Call
}

// ListRecentActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockHomeFeedRepository_Expecter) ListRecentActivity(ctx interface{}, limit interface{}) *MockHomeFeedRepository_ListRecentActivity_Call {
	return &MockHomeFeedRepository_ListRecentActivity_Call{Call: _e.mock.On("ListRecentActivity", ctx, limit)}
}

func (_c *MockHomeFeedRepository_ListRecentActivity_Call) Run(run func(ctx context.Context, limit int)) *MockHomeFeedRepository_ListRecentActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHomeFeedRepository_ListRecentActivity_Call) Return(homeActivityRows []HomeActivityRow, err error) *MockHomeFeedRepository_ListRecentActivity_Call {
	_c.Call.Return(homeActivityRows, err)
	return _c
}

func (_c *MockHomeFeedRepository_ListRecentActivity_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]HomeActivityRow, error)) *MockHomeFeedRepository_ListRecentActivity_Call {
	_c.Call.Return(run)
	return _c
}

// ListRecentMembers provides a mock function for the type MockHomeFeedRepository
func (_mock *MockHomeFeedRepository) ListRecentMembers(ctx context.Context, limit int) ([]HomeMemberRow, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListRecentMembers")
	}

	var r0 []HomeMemberRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]HomeMemberRow, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []HomeMemberRow); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]HomeMemberRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHomeFeedRepository_ListRecentMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRecentMembers'
type MockHomeFeedRepository_ListRecentMembers_Call struct {
	*mock.Call
}

// ListRecentMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockHomeFeedRepository_Expecter) ListRecentMembers(ctx interface{}, limit interface{}) *MockHomeFeedRepository_ListRecentMembers_Call {
	return &MockHomeFeedRepository_ListRecentMembers_Call{Call: _e.mock.On("ListRecentMembers", ctx, limit)}
}

func (_c *MockHomeFeedRepository_ListRecentMembers_Call) Run(run func(ctx context.Context, limit int)) *MockHomeFeedRepository_ListRecentMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHomeFeedRepository_ListRecentMembers_Call) Return(homeMemberRows []HomeMemberRow, err error) *MockHomeFeedRepository_ListRecentMembers_Call {
	_c.Call.Return(homeMemberRows, err)
	return _c
}

func (_c *MockHomeFeedRepository_ListRecentMembers_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]HomeMemberRow, error)) *MockHomeFeedRepository_ListRecentMembers_Call {
	_c.Call.Return(run)
	return _c
}

// ListSidebarActivity provides a mock function for the type MockHomeFeedRepository
func (_mock *MockHomeFeedRepository) ListSidebarActivity(ctx context.Context) ([]SidebarActivityEntry, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListSidebarActivity")
	}

	var r0 []SidebarActivityEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]SidebarActivityEntry, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []SidebarActivityEntry); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SidebarActivityEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHomeFeedRepository_ListSidebarActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSidebarActivity'
type MockHomeFeedRepository_ListSidebarActivity_Call struct {
	*mock.Call
}

// ListSidebarActivity is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHomeFeedRepository_Expecter) ListSidebarActivity(ctx interface{}) *MockHomeFeedRepository_ListSidebarActivity_Call {
	return &MockHomeFeedRepository_ListSidebarActivity_Call{Call: _e.mock.On("ListSidebarActivity", ctx)}
}

func (_c *MockHomeFeedRepository_ListSidebarActivity_Call) Run(run func(ctx context.Context)) *MockHomeFeedRepository_ListSidebarActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHomeFeedRepository_ListSidebarActivity_Call) Return(sidebarActivityEntrys []SidebarActivityEntry, err error) *MockHomeFeedRepository_ListSidebarActivity_Call {
	_c.Call.Return(sidebarActivityEntrys, err)
	return _c
}

func (_c *MockHomeFeedRepository_ListSidebarActivity_Call) RunAndReturn(run func(ctx context.Context) ([]SidebarActivityEntry, error)) *MockHomeFeedRepository_ListSidebarActivity_Call {
	_c.Call.Return(run)
	return _c
}
