// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLiveStreamRepository creates a new instance of MockLiveStreamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLiveStreamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLiveStreamRepository {
	mock := &MockLiveStreamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLiveStreamRepository is an autogenerated mock type for the LiveStreamRepository type
type MockLiveStreamRepository struct {
	mock.Mock
}

type MockLiveStreamRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLiveStreamRepository) EXPECT() *MockLiveStreamRepository_Expecter {
	return &MockLiveStreamRepository_Expecter{mock: &_m.Mock}
}

// AdjustViewerCount provides a mock function for the type MockLiveStreamRepository
func (_mock *MockLiveStreamRepository) AdjustViewerCount(ctx context.Context, id uuid.UUID, delta int) (int, bool, error) {
	ret := _mock.Called(ctx, id, delta)

	if len(ret) == 0 {
		panic("no return value specified for AdjustViewerCount")
	}

	var r0 int
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) (int, bool, error)); ok {
		return returnFunc(ctx, id, delta)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) int); ok {
		r0 = returnFunc(ctx, id, delta)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) bool); ok {
		r1 = returnFunc(ctx, id, delta)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, int) error); ok {
		r2 = returnFunc(ctx, id, delta)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockLiveStreamRepository_AdjustViewerCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdjustViewerCount'
type MockLiveStreamRepository_AdjustViewerCount_Call struct {
	*mock.Call
}

// AdjustViewerCount is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - delta int
func (_e *MockLiveStreamRepository_Expecter) AdjustViewerCount(ctx interface{}, id interface{}, delta interface{}) *MockLiveStreamRepository_AdjustViewerCount_Call {
	return &MockLiveStreamRepository_AdjustViewerCount_Call{Call: _e.mock.On("AdjustViewerCount", ctx, id, delta)}
}

func (_c *MockLiveStreamRepository_AdjustViewerCount_Call) Run(run func(ctx context.Context, id uuid.UUID, delta int)) *MockLiveStreamRepository_AdjustViewerCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLiveStreamRepository_AdjustViewerCount_Call) Return(n int, b bool, err error) *MockLiveStreamRepository_AdjustViewerCount_Call {
	_c.Call.Return(n, b, err)
	return _c
}

func (_c *MockLiveStreamRepository_AdjustViewerCount_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, delta int) (int, bool, error)) *MockLiveStreamRepository_AdjustViewerCount_Call {
	_c.Call.Return(run)
	return _c
}

// CountActive provides a mock function for the type MockLiveStreamRepository
func (_mock *MockLiveStreamRepository) CountActive(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountActive")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLiveStreamRepository_CountActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountActive'
type MockLiveStreamRepository_CountActive_Call struct {
	*mock.Call
}

// CountActive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLiveStreamRepository_Expecter) CountActive(ctx interface{}) *MockLiveStreamRepository_CountActive_Call {
	return &MockLiveStreamRepository_CountActive_Call{Call: _e.mock.On("CountActive", ctx)}
}

func (_c *MockLiveStreamRepository_CountActive_Call) Run(run func(ctx context.Context)) *MockLiveStreamRepository_CountActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLiveStreamRepository_CountActive_Call) Return(n int, err error) *MockLiveStreamRepository_CountActive_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockLiveStreamRepository_CountActive_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *MockLiveStreamRepository_CountActive_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockLiveStreamRepository
func (_mock *MockLiveStreamRepository) Create(ctx context.Context, userID uuid.UUID, title string, maxConcurrent int) (uuid.UUID, error) {
	ret := _mock.Called(ctx, userID, title, maxConcurrent)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int) (uuid.UUID, error)); ok {
		return returnFunc(ctx, userID, title, maxConcurrent)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int) uuid.UUID); ok {
		r0 = returnFunc(ctx, userID, title, maxConcurrent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int) error); ok {
		r1 = returnFunc(ctx, userID, title, maxConcurrent)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLiveStreamRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLiveStreamRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - title string
//   - maxConcurrent int
func (_e *MockLiveStreamRepository_Expecter) Create(ctx interface{}, userID interface{}, title interface{}, maxConcurrent interface{}) *MockLiveStreamRepository_Create_Call {
	return &MockLiveStreamRepository_Create_Call{Call: _e.mock.On("Create", ctx, userID, title, maxConcurrent)}
}

func (_c *MockLiveStreamRepository_Create_Call) Run(run func(ctx context.Context, userID uuid.UUID, title string, maxConcurrent int)) *MockLiveStreamRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockLiveStreamRepository_Create_Call) Return(uUID uuid.UUID, err error) *MockLiveStreamRepository_Create_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockLiveStreamRepository_Create_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, title string, maxConcurrent int) (uuid.UUID, error)) *MockLiveStreamRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveByUser provides a mock function for the type MockLiveStreamRepository
func (_mock *MockLiveStreamRepository) GetActiveByUser(ctx context.Context, userID uuid.UUID) (*LiveStreamRow, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveByUser")
	}

	var r0 *LiveStreamRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*LiveStreamRow, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *LiveStreamRow); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*LiveStreamRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLiveStreamRepository_GetActiveByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveByUser'
type MockLiveStreamRepository_GetActiveByUser_Call struct {
	*mock.Call
}

// GetActiveByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockLiveStreamRepository_Expecter) GetActiveByUser(ctx interface{}, userID interface{}) *MockLiveStreamRepository_GetActiveByUser_Call {
	return &MockLiveStreamRepository_GetActiveByUser_Call{Call: _e.mock.On("GetActiveByUser", ctx, userID)}
}

func (_c *MockLiveStreamRepository_GetActiveByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockLiveStreamRepository_GetActiveByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLiveStreamRepository_GetActiveByUser_Call) Return(liveStreamRow *LiveStreamRow, err error) *MockLiveStreamRepository_GetActiveByUser_Call {
	_c.Call.Return(liveStreamRow, err)
	return _c
}

func (_c *MockLiveStreamRepository_GetActiveByUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*LiveStreamRow, error)) *MockLiveStreamRepository_GetActiveByUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockLiveStreamRepository
func (_mock *MockLiveStreamRepository) GetByID(ctx context.Context, id uuid.UUID) (*LiveStreamRow, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *LiveStreamRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*LiveStreamRow, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *LiveStreamRow); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*LiveStreamRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLiveStreamRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockLiveStreamRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockLiveStreamRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockLiveStreamRepository_GetByID_Call {
	return &MockLiveStreamRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockLiveStreamRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockLiveStreamRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLiveStreamRepository_GetByID_Call) Return(liveStreamRow *LiveStreamRow, err error) *MockLiveStreamRepository_GetByID_Call {
	_c.Call.Return(liveStreamRow, err)
	return _c
}

func (_c *MockLiveStreamRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*LiveStreamRow, error)) *MockLiveStreamRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByRoom provides a mock function for the type MockLiveStreamRepository
func (_mock *MockLiveStreamRepository) GetByRoom(ctx context.Context, room string) (*LiveStreamRow, error) {
	ret := _mock.Called(ctx, room)

	if len(ret) == 0 {
		panic("no return value specified for GetByRoom")
	}

	var r0 *LiveStreamRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*LiveStreamRow, error)); ok {
		return returnFunc(ctx, room)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *LiveStreamRow); ok {
		r0 = returnFunc(ctx, room)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*LiveStreamRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, room)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLiveStreamRepository_GetByRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByRoom'
type MockLiveStreamRepository_GetByRoom_Call struct {
	*mock.Call
}

// GetByRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - room string
func (_e *MockLiveStreamRepository_Expecter) GetByRoom(ctx interface{}, room interface{}) *MockLiveStreamRepository_GetByRoom_Call {
	return &MockLiveStreamRepository_GetByRoom_Call{Call: _e.mock.On("GetByRoom", ctx, room)}
}

func (_c *MockLiveStreamRepository_GetByRoom_Call) Run(run func(ctx context.Context, room string)) *MockLiveStreamRepository_GetByRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLiveStreamRepository_GetByRoom_Call) Return(liveStreamRow *LiveStreamRow, err error) *MockLiveStreamRepository_GetByRoom_Call {
	_c.Call.Return(liveStreamRow, err)
	return _c
}

func (_c *MockLiveStreamRepository_GetByRoom_Call) RunAndReturn(run func(ctx context.Context, room string) (*LiveStreamRow, error)) *MockLiveStreamRepository_GetByRoom_Call {
	_c.Call.Return(run)
	return _c
}

// ListLive provides a mock function for the type MockLiveStreamRepository
func (_mock *MockLiveStreamRepository) ListLive(ctx context.Context) ([]LiveStreamRow, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListLive")
	}

	var r0 []LiveStreamRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]LiveStreamRow, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []LiveStreamRow); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]LiveStreamRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLiveStreamRepository_ListLive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLive'
type MockLiveStreamRepository_ListLive_Call struct {
	*mock.Call
}

// ListLive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLiveStreamRepository_Expecter) ListLive(ctx interface{}) *MockLiveStreamRepository_ListLive_Call {
	return &MockLiveStreamRepository_ListLive_Call{Call: _e.mock.On("ListLive", ctx)}
}

func (_c *MockLiveStreamRepository_ListLive_Call) Run(run func(ctx context.Context)) *MockLiveStreamRepository_ListLive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLiveStreamRepository_ListLive_Call) Return(liveStreamRows []LiveStreamRow, err error) *MockLiveStreamRepository_ListLive_Call {
	_c.Call.Return(liveStreamRows, err)
	return _c
}

func (_c *MockLiveStreamRepository_ListLive_Call) RunAndReturn(run func(ctx context.Context) ([]LiveStreamRow, error)) *MockLiveStreamRepository_ListLive_Call {
	_c.Call.Return(run)
	return _c
}

// ListStartingBefore provides a mock function for the type MockLiveStreamRepository
func (_mock *MockLiveStreamRepository) ListStartingBefore(ctx context.Context, cutoff string) ([]LiveStreamRow, error) {
	ret := _mock.Called(ctx, cutoff)

	if len(ret) == 0 {
		panic("no return value specified for ListStartingBefore")
	}

	var r0 []LiveStreamRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]LiveStreamRow, error)); ok {
		return returnFunc(ctx, cutoff)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []LiveStreamRow); ok {
		r0 = returnFunc(ctx, cutoff)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]LiveStreamRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, cutoff)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLiveStreamRepository_ListStartingBefore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStartingBefore'
type MockLiveStreamRepository_ListStartingBefore_Call struct {
	*mock.Call
}

// ListStartingBefore is a helper method to define mock.On call
//   - ctx context.Context
//   - cutoff string
func (_e *MockLiveStreamRepository_Expecter) ListStartingBefore(ctx interface{}, cutoff interface{}) *MockLiveStreamRepository_ListStartingBefore_Call {
	return &MockLiveStreamRepository_ListStartingBefore_Call{Call: _e.mock.On("ListStartingBefore", ctx, cutoff)}
}

func (_c *MockLiveStreamRepository_ListStartingBefore_Call) Run(run func(ctx context.Context, cutoff string)) *MockLiveStreamRepository_ListStartingBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLiveStreamRepository_ListStartingBefore_Call) Return(liveStreamRows []LiveStreamRow, err error) *MockLiveStreamRepository_ListStartingBefore_Call {
	_c.Call.Return(liveStreamRows, err)
	return _c
}

func (_c *MockLiveStreamRepository_ListStartingBefore_Call) RunAndReturn(run func(ctx context.Context, cutoff string) ([]LiveStreamRow, error)) *MockLiveStreamRepository_ListStartingBefore_Call {
	_c.Call.Return(run)
	return _c
}

// MarkLive provides a mock function for the type MockLiveStreamRepository
func (_mock *MockLiveStreamRepository) MarkLive(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkLive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLiveStreamRepository_MarkLive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkLive'
type MockLiveStreamRepository_MarkLive_Call struct {
	*mock.Call
}

// MarkLive is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockLiveStreamRepository_Expecter) MarkLive(ctx interface{}, id interface{}) *MockLiveStreamRepository_MarkLive_Call {
	return &MockLiveStreamRepository_MarkLive_Call{Call: _e.mock.On("MarkLive", ctx, id)}
}

func (_c *MockLiveStreamRepository_MarkLive_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockLiveStreamRepository_MarkLive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLiveStreamRepository_MarkLive_Call) Return(err error) *MockLiveStreamRepository_MarkLive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLiveStreamRepository_MarkLive_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockLiveStreamRepository_MarkLive_Call {
	_c.Call.Return(run)
	return _c
}

// MarkOffline provides a mock function for the type MockLiveStreamRepository
func (_mock *MockLiveStreamRepository) MarkOffline(ctx context.Context, id uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkOffline")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLiveStreamRepository_MarkOffline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkOffline'
type MockLiveStreamRepository_MarkOffline_Call struct {
	*mock.Call
}

// MarkOffline is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockLiveStreamRepository_Expecter) MarkOffline(ctx interface{}, id interface{}) *MockLiveStreamRepository_MarkOffline_Call {
	return &MockLiveStreamRepository_MarkOffline_Call{Call: _e.mock.On("MarkOffline", ctx, id)}
}

func (_c *MockLiveStreamRepository_MarkOffline_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockLiveStreamRepository_MarkOffline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLiveStreamRepository_MarkOffline_Call) Return(b bool, err error) *MockLiveStreamRepository_MarkOffline_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockLiveStreamRepository_MarkOffline_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (bool, error)) *MockLiveStreamRepository_MarkOffline_Call {
	_c.Call.Return(run)
	return _c
}

// SetIngress provides a mock function for the type MockLiveStreamRepository
func (_mock *MockLiveStreamRepository) SetIngress(ctx context.Context, id uuid.UUID, ingressID string, room string, whipURL string, streamKey string) error {
	ret := _mock.Called(ctx, id, ingressID, room, whipURL, streamKey)

	if len(ret) == 0 {
		panic("no return value specified for SetIngress")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, id, ingressID, room, whipURL, streamKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLiveStreamRepository_SetIngress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetIngress'
type MockLiveStreamRepository_SetIngress_Call struct {
	*mock.Call
}

// SetIngress is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - ingressID string
//   - room string
//   - whipURL string
//   - streamKey string
func (_e *MockLiveStreamRepository_Expecter) SetIngress(ctx interface{}, id interface{}, ingressID interface{}, room interface{}, whipURL interface{}, streamKey interface{}) *MockLiveStreamRepository_SetIngress_Call {
	return &MockLiveStreamRepository_SetIngress_Call{Call: _e.mock.On("SetIngress", ctx, id, ingressID, room, whipURL, streamKey)}
}

func (_c *MockLiveStreamRepository_SetIngress_Call) Run(run func(ctx context.Context, id uuid.UUID, ingressID string, room string, whipURL string, streamKey string)) *MockLiveStreamRepository_SetIngress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockLiveStreamRepository_SetIngress_Call) Return(err error) *MockLiveStreamRepository_SetIngress_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLiveStreamRepository_SetIngress_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, ingressID string, room string, whipURL string, streamKey string) error) *MockLiveStreamRepository_SetIngress_Call {
	_c.Call.Return(run)
	return _c
}
