// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOverlayTokenRepository creates a new instance of MockOverlayTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOverlayTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOverlayTokenRepository {
	mock := &MockOverlayTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOverlayTokenRepository is an autogenerated mock type for the OverlayTokenRepository type
type MockOverlayTokenRepository struct {
	mock.Mock
}

type MockOverlayTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOverlayTokenRepository) EXPECT() *MockOverlayTokenRepository_Expecter {
	return &MockOverlayTokenRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockOverlayTokenRepository
func (_mock *MockOverlayTokenRepository) Delete(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOverlayTokenRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockOverlayTokenRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockOverlayTokenRepository_Expecter) Delete(ctx any, userID any) *MockOverlayTokenRepository_Delete_Call {
	return &MockOverlayTokenRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, userID)}
}

func (_c *MockOverlayTokenRepository_Delete_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockOverlayTokenRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOverlayTokenRepository_Delete_Call) Return(err error) *MockOverlayTokenRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOverlayTokenRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockOverlayTokenRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUser provides a mock function for the type MockOverlayTokenRepository
func (_mock *MockOverlayTokenRepository) GetByUser(ctx context.Context, userID uuid.UUID) (string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOverlayTokenRepository_GetByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUser'
type MockOverlayTokenRepository_GetByUser_Call struct {
	*mock.Call
}

// GetByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockOverlayTokenRepository_Expecter) GetByUser(ctx any, userID any) *MockOverlayTokenRepository_GetByUser_Call {
	return &MockOverlayTokenRepository_GetByUser_Call{Call: _e.mock.On("GetByUser", ctx, userID)}
}

func (_c *MockOverlayTokenRepository_GetByUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockOverlayTokenRepository_GetByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOverlayTokenRepository_GetByUser_Call) Return(s string, err error) *MockOverlayTokenRepository_GetByUser_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockOverlayTokenRepository_GetByUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (string, error)) *MockOverlayTokenRepository_GetByUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByToken provides a mock function for the type MockOverlayTokenRepository
func (_mock *MockOverlayTokenRepository) GetUserByToken(ctx context.Context, token string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByToken")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOverlayTokenRepository_GetUserByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByToken'
type MockOverlayTokenRepository_GetUserByToken_Call struct {
	*mock.Call
}

// GetUserByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockOverlayTokenRepository_Expecter) GetUserByToken(ctx any, token any) *MockOverlayTokenRepository_GetUserByToken_Call {
	return &MockOverlayTokenRepository_GetUserByToken_Call{Call: _e.mock.On("GetUserByToken", ctx, token)}
}

func (_c *MockOverlayTokenRepository_GetUserByToken_Call) Run(run func(ctx context.Context, token string)) *MockOverlayTokenRepository_GetUserByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOverlayTokenRepository_GetUserByToken_Call) Return(uUID uuid.UUID, err error) *MockOverlayTokenRepository_GetUserByToken_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockOverlayTokenRepository_GetUserByToken_Call) RunAndReturn(run func(ctx context.Context, token string) (uuid.UUID, error)) *MockOverlayTokenRepository_GetUserByToken_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockOverlayTokenRepository
func (_mock *MockOverlayTokenRepository) Upsert(ctx context.Context, userID uuid.UUID, token string) error {
	ret := _mock.Called(ctx, userID, token)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, userID, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOverlayTokenRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockOverlayTokenRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - token string
func (_e *MockOverlayTokenRepository_Expecter) Upsert(ctx any, userID any, token any) *MockOverlayTokenRepository_Upsert_Call {
	return &MockOverlayTokenRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, userID, token)}
}

func (_c *MockOverlayTokenRepository_Upsert_Call) Run(run func(ctx context.Context, userID uuid.UUID, token string)) *MockOverlayTokenRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOverlayTokenRepository_Upsert_Call) Return(err error) *MockOverlayTokenRepository_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOverlayTokenRepository_Upsert_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, token string) error) *MockOverlayTokenRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
