// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReportRepository creates a new instance of MockReportRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportRepository {
	mock := &MockReportRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReportRepository is an autogenerated mock type for the ReportRepository type
type MockReportRepository struct {
	mock.Mock
}

type MockReportRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportRepository) EXPECT() *MockReportRepository_Expecter {
	return &MockReportRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockReportRepository
func (_mock *MockReportRepository) Create(ctx context.Context, spec NewReport, tx ...*sql.Tx) (*ReportRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, spec, tx)
	} else {
		tmpRet = _mock.Called(ctx, spec)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *ReportRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, NewReport, ...*sql.Tx) (*ReportRow, error)); ok {
		return returnFunc(ctx, spec, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, NewReport, ...*sql.Tx) *ReportRow); ok {
		r0 = returnFunc(ctx, spec, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ReportRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, NewReport, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, spec, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockReportRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - spec NewReport
//   - tx ...*sql.Tx
func (_e *MockReportRepository_Expecter) Create(ctx any, spec any, tx ...any) *MockReportRepository_Create_Call {
	return &MockReportRepository_Create_Call{Call: _e.mock.On("Create",
		append([]any{ctx, spec}, tx...)...)}
}

func (_c *MockReportRepository_Create_Call) Run(run func(ctx context.Context, spec NewReport, tx ...*sql.Tx)) *MockReportRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 NewReport
		if args[1] != nil {
			arg1 = args[1].(NewReport)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockReportRepository_Create_Call) Return(reportRow *ReportRow, err error) *MockReportRepository_Create_Call {
	_c.Call.Return(reportRow, err)
	return _c
}

func (_c *MockReportRepository_Create_Call) RunAndReturn(run func(ctx context.Context, spec NewReport, tx ...*sql.Tx) (*ReportRow, error)) *MockReportRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockReportRepository
func (_mock *MockReportRepository) GetByID(ctx context.Context, id int, tx ...*sql.Tx) (*ReportRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, id, tx)
	} else {
		tmpRet = _mock.Called(ctx, id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *ReportRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, ...*sql.Tx) (*ReportRow, error)); ok {
		return returnFunc(ctx, id, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, ...*sql.Tx) *ReportRow); ok {
		r0 = returnFunc(ctx, id, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ReportRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, id, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockReportRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - tx ...*sql.Tx
func (_e *MockReportRepository_Expecter) GetByID(ctx any, id any, tx ...any) *MockReportRepository_GetByID_Call {
	return &MockReportRepository_GetByID_Call{Call: _e.mock.On("GetByID",
		append([]any{ctx, id}, tx...)...)}
}

func (_c *MockReportRepository_GetByID_Call) Run(run func(ctx context.Context, id int, tx ...*sql.Tx)) *MockReportRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockReportRepository_GetByID_Call) Return(reportRow *ReportRow, err error) *MockReportRepository_GetByID_Call {
	_c.Call.Return(reportRow, err)
	return _c
}

func (_c *MockReportRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int, tx ...*sql.Tx) (*ReportRow, error)) *MockReportRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockReportRepository
func (_mock *MockReportRepository) List(ctx context.Context, status string, limit int, offset int, tx ...*sql.Tx) ([]ReportRow, int, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, status, limit, offset, tx)
	} else {
		tmpRet = _mock.Called(ctx, status, limit, offset)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []ReportRow
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int, ...*sql.Tx) ([]ReportRow, int, error)); ok {
		return returnFunc(ctx, status, limit, offset, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int, ...*sql.Tx) []ReportRow); ok {
		r0 = returnFunc(ctx, status, limit, offset, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ReportRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int, ...*sql.Tx) int); ok {
		r1 = returnFunc(ctx, status, limit, offset, tx...)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, int, int, ...*sql.Tx) error); ok {
		r2 = returnFunc(ctx, status, limit, offset, tx...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockReportRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockReportRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - status string
//   - limit int
//   - offset int
//   - tx ...*sql.Tx
func (_e *MockReportRepository_Expecter) List(ctx any, status any, limit any, offset any, tx ...any) *MockReportRepository_List_Call {
	return &MockReportRepository_List_Call{Call: _e.mock.On("List",
		append([]any{ctx, status, limit, offset}, tx...)...)}
}

func (_c *MockReportRepository_List_Call) Run(run func(ctx context.Context, status string, limit int, offset int, tx ...*sql.Tx)) *MockReportRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 4 {
			variadicArgs = args[4].([]*sql.Tx)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockReportRepository_List_Call) Return(reportRows []ReportRow, n int, err error) *MockReportRepository_List_Call {
	_c.Call.Return(reportRows, n, err)
	return _c
}

func (_c *MockReportRepository_List_Call) RunAndReturn(run func(ctx context.Context, status string, limit int, offset int, tx ...*sql.Tx) ([]ReportRow, int, error)) *MockReportRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Resolve provides a mock function for the type MockReportRepository
func (_mock *MockReportRepository) Resolve(ctx context.Context, id int, resolvedBy uuid.UUID, comment string, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, id, resolvedBy, comment, tx)
	} else {
		tmpRet = _mock.Called(ctx, id, resolvedBy, comment)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, uuid.UUID, string, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, id, resolvedBy, comment, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReportRepository_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockReportRepository_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - resolvedBy uuid.UUID
//   - comment string
//   - tx ...*sql.Tx
func (_e *MockReportRepository_Expecter) Resolve(ctx any, id any, resolvedBy any, comment any, tx ...any) *MockReportRepository_Resolve_Call {
	return &MockReportRepository_Resolve_Call{Call: _e.mock.On("Resolve",
		append([]any{ctx, id, resolvedBy, comment}, tx...)...)}
}

func (_c *MockReportRepository_Resolve_Call) Run(run func(ctx context.Context, id int, resolvedBy uuid.UUID, comment string, tx ...*sql.Tx)) *MockReportRepository_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 4 {
			variadicArgs = args[4].([]*sql.Tx)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockReportRepository_Resolve_Call) Return(err error) *MockReportRepository_Resolve_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReportRepository_Resolve_Call) RunAndReturn(run func(ctx context.Context, id int, resolvedBy uuid.UUID, comment string, tx ...*sql.Tx) error) *MockReportRepository_Resolve_Call {
	_c.Call.Return(run)
	return _c
}
