// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSettingsDAO creates a new instance of MockSettingsDAO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSettingsDAO(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSettingsDAO {
	mock := &MockSettingsDAO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSettingsDAO is an autogenerated mock type for the SettingsDAO type
type MockSettingsDAO struct {
	mock.Mock
}

type MockSettingsDAO_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSettingsDAO) EXPECT() *MockSettingsDAO_Expecter {
	return &MockSettingsDAO_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockSettingsDAO
func (_mock *MockSettingsDAO) Delete(ctx context.Context, key string, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, key, tx)
	} else {
		tmpRet = _mock.Called(ctx, key)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, key, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSettingsDAO_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSettingsDAO_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - tx ...*sql.Tx
func (_e *MockSettingsDAO_Expecter) Delete(ctx any, key any, tx ...any) *MockSettingsDAO_Delete_Call {
	return &MockSettingsDAO_Delete_Call{Call: _e.mock.On("Delete",
		append([]any{ctx, key}, tx...)...)}
}

func (_c *MockSettingsDAO_Delete_Call) Run(run func(ctx context.Context, key string, tx ...*sql.Tx)) *MockSettingsDAO_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSettingsDAO_Delete_Call) Return(err error) *MockSettingsDAO_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSettingsDAO_Delete_Call) RunAndReturn(run func(ctx context.Context, key string, tx ...*sql.Tx) error) *MockSettingsDAO_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockSettingsDAO
func (_mock *MockSettingsDAO) Get(ctx context.Context, key string, tx ...*sql.Tx) (string, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, key, tx)
	} else {
		tmpRet = _mock.Called(ctx, key)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*sql.Tx) (string, error)); ok {
		return returnFunc(ctx, key, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*sql.Tx) string); ok {
		r0 = returnFunc(ctx, key, tx...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, key, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSettingsDAO_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSettingsDAO_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - tx ...*sql.Tx
func (_e *MockSettingsDAO_Expecter) Get(ctx any, key any, tx ...any) *MockSettingsDAO_Get_Call {
	return &MockSettingsDAO_Get_Call{Call: _e.mock.On("Get",
		append([]any{ctx, key}, tx...)...)}
}

func (_c *MockSettingsDAO_Get_Call) Run(run func(ctx context.Context, key string, tx ...*sql.Tx)) *MockSettingsDAO_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSettingsDAO_Get_Call) Return(s string, err error) *MockSettingsDAO_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSettingsDAO_Get_Call) RunAndReturn(run func(ctx context.Context, key string, tx ...*sql.Tx) (string, error)) *MockSettingsDAO_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockSettingsDAO
func (_mock *MockSettingsDAO) GetAll(ctx context.Context, tx ...*sql.Tx) (map[string]string, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, tx)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*sql.Tx) (map[string]string, error)); ok {
		return returnFunc(ctx, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*sql.Tx) map[string]string); ok {
		r0 = returnFunc(ctx, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSettingsDAO_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockSettingsDAO_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - tx ...*sql.Tx
func (_e *MockSettingsDAO_Expecter) GetAll(ctx any, tx ...any) *MockSettingsDAO_GetAll_Call {
	return &MockSettingsDAO_GetAll_Call{Call: _e.mock.On("GetAll",
		append([]any{ctx}, tx...)...)}
}

func (_c *MockSettingsDAO_GetAll_Call) Run(run func(ctx context.Context, tx ...*sql.Tx)) *MockSettingsDAO_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 1 {
			variadicArgs = args[1].([]*sql.Tx)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockSettingsDAO_GetAll_Call) Return(stringToString map[string]string, err error) *MockSettingsDAO_GetAll_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockSettingsDAO_GetAll_Call) RunAndReturn(run func(ctx context.Context, tx ...*sql.Tx) (map[string]string, error)) *MockSettingsDAO_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockSettingsDAO
func (_mock *MockSettingsDAO) Set(ctx context.Context, key string, value string, updatedBy uuid.UUID, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, key, value, updatedBy, tx)
	} else {
		tmpRet = _mock.Called(ctx, key, value, updatedBy)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, uuid.UUID, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, key, value, updatedBy, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSettingsDAO_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockSettingsDAO_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
//   - updatedBy uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockSettingsDAO_Expecter) Set(ctx any, key any, value any, updatedBy any, tx ...any) *MockSettingsDAO_Set_Call {
	return &MockSettingsDAO_Set_Call{Call: _e.mock.On("Set",
		append([]any{ctx, key, value, updatedBy}, tx...)...)}
}

func (_c *MockSettingsDAO_Set_Call) Run(run func(ctx context.Context, key string, value string, updatedBy uuid.UUID, tx ...*sql.Tx)) *MockSettingsDAO_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		var arg4 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 4 {
			variadicArgs = args[4].([]*sql.Tx)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockSettingsDAO_Set_Call) Return(err error) *MockSettingsDAO_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSettingsDAO_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value string, updatedBy uuid.UUID, tx ...*sql.Tx) error) *MockSettingsDAO_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetMultiple provides a mock function for the type MockSettingsDAO
func (_mock *MockSettingsDAO) SetMultiple(ctx context.Context, settings map[string]string, updatedBy uuid.UUID, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, settings, updatedBy, tx)
	} else {
		tmpRet = _mock.Called(ctx, settings, updatedBy)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SetMultiple")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string, uuid.UUID, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, settings, updatedBy, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSettingsDAO_SetMultiple_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMultiple'
type MockSettingsDAO_SetMultiple_Call struct {
	*mock.Call
}

// SetMultiple is a helper method to define mock.On call
//   - ctx context.Context
//   - settings map[string]string
//   - updatedBy uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockSettingsDAO_Expecter) SetMultiple(ctx any, settings any, updatedBy any, tx ...any) *MockSettingsDAO_SetMultiple_Call {
	return &MockSettingsDAO_SetMultiple_Call{Call: _e.mock.On("SetMultiple",
		append([]any{ctx, settings, updatedBy}, tx...)...)}
}

func (_c *MockSettingsDAO_SetMultiple_Call) Run(run func(ctx context.Context, settings map[string]string, updatedBy uuid.UUID, tx ...*sql.Tx)) *MockSettingsDAO_SetMultiple_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]string
		if args[1] != nil {
			arg1 = args[1].(map[string]string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 3 {
			variadicArgs = args[3].([]*sql.Tx)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockSettingsDAO_SetMultiple_Call) Return(err error) *MockSettingsDAO_SetMultiple_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSettingsDAO_SetMultiple_Call) RunAndReturn(run func(ctx context.Context, settings map[string]string, updatedBy uuid.UUID, tx ...*sql.Tx) error) *MockSettingsDAO_SetMultiple_Call {
	_c.Call.Return(run)
	return _c
}
