// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"database/sql"
	"umineko_city_of_books/internal/model"
	"umineko_city_of_books/internal/model/spec"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStoredFileRepository creates a new instance of MockStoredFileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStoredFileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStoredFileRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockStoredFileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockStoredFileRepository is an autogenerated mock type for the StoredFileRepository type
type MockStoredFileRepository struct {
	mock.Mock
}

type MockStoredFileRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStoredFileRepository) EXPECT() *MockStoredFileRepository_Expecter {
	return &MockStoredFileRepository_Expecter{mock: &_m.Mock}
}

// Backfill provides a mock function for the type MockStoredFileRepository
func (_mock *MockStoredFileRepository) Backfill(ctx context.Context, s spec.StoredFileBackfill, tx ...*sql.Tx) (int64, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Backfill")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.StoredFileBackfill, ...*sql.Tx) (int64, error)); ok {
		return returnFunc(ctx, s, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.StoredFileBackfill, ...*sql.Tx) int64); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.StoredFileBackfill, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, s, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStoredFileRepository_Backfill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Backfill'
type MockStoredFileRepository_Backfill_Call struct {
	*mock.Call
}

// Backfill is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.StoredFileBackfill
//   - tx ...*sql.Tx
func (_e *MockStoredFileRepository_Expecter) Backfill(ctx any, s any, tx ...any) *MockStoredFileRepository_Backfill_Call {
	return &MockStoredFileRepository_Backfill_Call{Call: _e.mock.On("Backfill",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockStoredFileRepository_Backfill_Call) Run(run func(ctx context.Context, s spec.StoredFileBackfill, tx ...*sql.Tx)) *MockStoredFileRepository_Backfill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.StoredFileBackfill
		if args[1] != nil {
			arg1 = args[1].(spec.StoredFileBackfill)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockStoredFileRepository_Backfill_Call) Return(n int64, err error) *MockStoredFileRepository_Backfill_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStoredFileRepository_Backfill_Call) RunAndReturn(run func(ctx context.Context, s spec.StoredFileBackfill, tx ...*sql.Tx) (int64, error)) *MockStoredFileRepository_Backfill_Call {
	_c.Call.Return(run)
	return _c
}

// CountByBackend provides a mock function for the type MockStoredFileRepository
func (_mock *MockStoredFileRepository) CountByBackend(ctx context.Context, s spec.StoredFileBackend, tx ...*sql.Tx) (int64, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CountByBackend")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.StoredFileBackend, ...*sql.Tx) (int64, error)); ok {
		return returnFunc(ctx, s, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.StoredFileBackend, ...*sql.Tx) int64); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.StoredFileBackend, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, s, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStoredFileRepository_CountByBackend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByBackend'
type MockStoredFileRepository_CountByBackend_Call struct {
	*mock.Call
}

// CountByBackend is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.StoredFileBackend
//   - tx ...*sql.Tx
func (_e *MockStoredFileRepository_Expecter) CountByBackend(ctx any, s any, tx ...any) *MockStoredFileRepository_CountByBackend_Call {
	return &MockStoredFileRepository_CountByBackend_Call{Call: _e.mock.On("CountByBackend",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockStoredFileRepository_CountByBackend_Call) Run(run func(ctx context.Context, s spec.StoredFileBackend, tx ...*sql.Tx)) *MockStoredFileRepository_CountByBackend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.StoredFileBackend
		if args[1] != nil {
			arg1 = args[1].(spec.StoredFileBackend)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockStoredFileRepository_CountByBackend_Call) Return(n int64, err error) *MockStoredFileRepository_CountByBackend_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStoredFileRepository_CountByBackend_Call) RunAndReturn(run func(ctx context.Context, s spec.StoredFileBackend, tx ...*sql.Tx) (int64, error)) *MockStoredFileRepository_CountByBackend_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockStoredFileRepository
func (_mock *MockStoredFileRepository) Delete(ctx context.Context, s spec.StoredFileKeys, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.StoredFileKeys, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStoredFileRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStoredFileRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.StoredFileKeys
//   - tx ...*sql.Tx
func (_e *MockStoredFileRepository_Expecter) Delete(ctx any, s any, tx ...any) *MockStoredFileRepository_Delete_Call {
	return &MockStoredFileRepository_Delete_Call{Call: _e.mock.On("Delete",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockStoredFileRepository_Delete_Call) Run(run func(ctx context.Context, s spec.StoredFileKeys, tx ...*sql.Tx)) *MockStoredFileRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.StoredFileKeys
		if args[1] != nil {
			arg1 = args[1].(spec.StoredFileKeys)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockStoredFileRepository_Delete_Call) Return(err error) *MockStoredFileRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStoredFileRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, s spec.StoredFileKeys, tx ...*sql.Tx) error) *MockStoredFileRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockStoredFileRepository
func (_mock *MockStoredFileRepository) Get(ctx context.Context, s spec.StoredFileKey, tx ...*sql.Tx) (*model.StoredFileRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.StoredFileRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.StoredFileKey, ...*sql.Tx) (*model.StoredFileRow, error)); ok {
		return returnFunc(ctx, s, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.StoredFileKey, ...*sql.Tx) *model.StoredFileRow); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.StoredFileRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.StoredFileKey, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, s, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStoredFileRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStoredFileRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.StoredFileKey
//   - tx ...*sql.Tx
func (_e *MockStoredFileRepository_Expecter) Get(ctx any, s any, tx ...any) *MockStoredFileRepository_Get_Call {
	return &MockStoredFileRepository_Get_Call{Call: _e.mock.On("Get",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockStoredFileRepository_Get_Call) Run(run func(ctx context.Context, s spec.StoredFileKey, tx ...*sql.Tx)) *MockStoredFileRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.StoredFileKey
		if args[1] != nil {
			arg1 = args[1].(spec.StoredFileKey)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockStoredFileRepository_Get_Call) Return(storedFileRow *model.StoredFileRow, err error) *MockStoredFileRepository_Get_Call {
	_c.Call.Return(storedFileRow, err)
	return _c
}

func (_c *MockStoredFileRepository_Get_Call) RunAndReturn(run func(ctx context.Context, s spec.StoredFileKey, tx ...*sql.Tx) (*model.StoredFileRow, error)) *MockStoredFileRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListByKeys provides a mock function for the type MockStoredFileRepository
func (_mock *MockStoredFileRepository) ListByKeys(ctx context.Context, s spec.StoredFileKeys, tx ...*sql.Tx) ([]model.StoredFileRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListByKeys")
	}

	var r0 []model.StoredFileRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.StoredFileKeys, ...*sql.Tx) ([]model.StoredFileRow, error)); ok {
		return returnFunc(ctx, s, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.StoredFileKeys, ...*sql.Tx) []model.StoredFileRow); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.StoredFileRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.StoredFileKeys, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, s, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStoredFileRepository_ListByKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByKeys'
type MockStoredFileRepository_ListByKeys_Call struct {
	*mock.Call
}

// ListByKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.StoredFileKeys
//   - tx ...*sql.Tx
func (_e *MockStoredFileRepository_Expecter) ListByKeys(ctx any, s any, tx ...any) *MockStoredFileRepository_ListByKeys_Call {
	return &MockStoredFileRepository_ListByKeys_Call{Call: _e.mock.On("ListByKeys",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockStoredFileRepository_ListByKeys_Call) Run(run func(ctx context.Context, s spec.StoredFileKeys, tx ...*sql.Tx)) *MockStoredFileRepository_ListByKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.StoredFileKeys
		if args[1] != nil {
			arg1 = args[1].(spec.StoredFileKeys)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockStoredFileRepository_ListByKeys_Call) Return(storedFileRows []model.StoredFileRow, err error) *MockStoredFileRepository_ListByKeys_Call {
	_c.Call.Return(storedFileRows, err)
	return _c
}

func (_c *MockStoredFileRepository_ListByKeys_Call) RunAndReturn(run func(ctx context.Context, s spec.StoredFileKeys, tx ...*sql.Tx) ([]model.StoredFileRow, error)) *MockStoredFileRepository_ListByKeys_Call {
	_c.Call.Return(run)
	return _c
}

// ListByPrefix provides a mock function for the type MockStoredFileRepository
func (_mock *MockStoredFileRepository) ListByPrefix(ctx context.Context, s spec.StoredFilePrefix, tx ...*sql.Tx) ([]model.StoredFileRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListByPrefix")
	}

	var r0 []model.StoredFileRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.StoredFilePrefix, ...*sql.Tx) ([]model.StoredFileRow, error)); ok {
		return returnFunc(ctx, s, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.StoredFilePrefix, ...*sql.Tx) []model.StoredFileRow); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.StoredFileRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.StoredFilePrefix, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, s, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStoredFileRepository_ListByPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByPrefix'
type MockStoredFileRepository_ListByPrefix_Call struct {
	*mock.Call
}

// ListByPrefix is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.StoredFilePrefix
//   - tx ...*sql.Tx
func (_e *MockStoredFileRepository_Expecter) ListByPrefix(ctx any, s any, tx ...any) *MockStoredFileRepository_ListByPrefix_Call {
	return &MockStoredFileRepository_ListByPrefix_Call{Call: _e.mock.On("ListByPrefix",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockStoredFileRepository_ListByPrefix_Call) Run(run func(ctx context.Context, s spec.StoredFilePrefix, tx ...*sql.Tx)) *MockStoredFileRepository_ListByPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.StoredFilePrefix
		if args[1] != nil {
			arg1 = args[1].(spec.StoredFilePrefix)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockStoredFileRepository_ListByPrefix_Call) Return(storedFileRows []model.StoredFileRow, err error) *MockStoredFileRepository_ListByPrefix_Call {
	_c.Call.Return(storedFileRows, err)
	return _c
}

func (_c *MockStoredFileRepository_ListByPrefix_Call) RunAndReturn(run func(ctx context.Context, s spec.StoredFilePrefix, tx ...*sql.Tx) ([]model.StoredFileRow, error)) *MockStoredFileRepository_ListByPrefix_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockStoredFileRepository
func (_mock *MockStoredFileRepository) Upsert(ctx context.Context, s spec.NewStoredFile, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NewStoredFile, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStoredFileRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockStoredFileRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.NewStoredFile
//   - tx ...*sql.Tx
func (_e *MockStoredFileRepository_Expecter) Upsert(ctx any, s any, tx ...any) *MockStoredFileRepository_Upsert_Call {
	return &MockStoredFileRepository_Upsert_Call{Call: _e.mock.On("Upsert",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockStoredFileRepository_Upsert_Call) Run(run func(ctx context.Context, s spec.NewStoredFile, tx ...*sql.Tx)) *MockStoredFileRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.NewStoredFile
		if args[1] != nil {
			arg1 = args[1].(spec.NewStoredFile)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockStoredFileRepository_Upsert_Call) Return(err error) *MockStoredFileRepository_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStoredFileRepository_Upsert_Call) RunAndReturn(run func(ctx context.Context, s spec.NewStoredFile, tx ...*sql.Tx) error) *MockStoredFileRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
