// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package upload

import (
	"context"
	"io"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CleanStaging provides a mock function for the type MockService
func (_mock *MockService) CleanStaging(olderThan time.Duration) (int, error) {
	ret := _mock.Called(olderThan)

	if len(ret) == 0 {
		panic("no return value specified for CleanStaging")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(time.Duration) (int, error)); ok {
		return returnFunc(olderThan)
	}
	if returnFunc, ok := ret.Get(0).(func(time.Duration) int); ok {
		r0 = returnFunc(olderThan)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(time.Duration) error); ok {
		r1 = returnFunc(olderThan)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CleanStaging_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanStaging'
type MockService_CleanStaging_Call struct {
	*mock.Call
}

// CleanStaging is a helper method to define mock.On call
//   - olderThan time.Duration
func (_e *MockService_Expecter) CleanStaging(olderThan any) *MockService_CleanStaging_Call {
	return &MockService_CleanStaging_Call{Call: _e.mock.On("CleanStaging", olderThan)}
}

func (_c *MockService_CleanStaging_Call) Run(run func(olderThan time.Duration)) *MockService_CleanStaging_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_CleanStaging_Call) Return(n int, err error) *MockService_CleanStaging_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockService_CleanStaging_Call) RunAndReturn(run func(olderThan time.Duration) (int, error)) *MockService_CleanStaging_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockService
func (_mock *MockService) Delete(urlPaths ...string) {
	if len(urlPaths) > 0 {
		_mock.Called(urlPaths)
	} else {
		_mock.Called()
	}

	return
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - urlPaths ...string
func (_e *MockService_Expecter) Delete(urlPaths ...any) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete",
		append([]any{}, urlPaths...)...)}
}

func (_c *MockService_Delete_Call) Run(run func(urlPaths ...string)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		var variadicArgs []string
		if len(args) > 0 {
			variadicArgs = args[0].([]string)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockService_Delete_Call) Return() *MockService_Delete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(urlPaths ...string)) *MockService_Delete_Call {
	_c.Run(run)
	return _c
}

// DeleteByPrefix provides a mock function for the type MockService
func (_mock *MockService) DeleteByPrefix(ctx context.Context, subDir string, prefix string) error {
	ret := _mock.Called(ctx, subDir, prefix)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByPrefix")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, subDir, prefix)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteByPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByPrefix'
type MockService_DeleteByPrefix_Call struct {
	*mock.Call
}

// DeleteByPrefix is a helper method to define mock.On call
//   - ctx context.Context
//   - subDir string
//   - prefix string
func (_e *MockService_Expecter) DeleteByPrefix(ctx any, subDir any, prefix any) *MockService_DeleteByPrefix_Call {
	return &MockService_DeleteByPrefix_Call{Call: _e.mock.On("DeleteByPrefix", ctx, subDir, prefix)}
}

func (_c *MockService_DeleteByPrefix_Call) Run(run func(ctx context.Context, subDir string, prefix string)) *MockService_DeleteByPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_DeleteByPrefix_Call) Return(err error) *MockService_DeleteByPrefix_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteByPrefix_Call) RunAndReturn(run func(ctx context.Context, subDir string, prefix string) error) *MockService_DeleteByPrefix_Call {
	_c.Call.Return(run)
	return _c
}

// Discard provides a mock function for the type MockService
func (_mock *MockService) Discard(localPath string) {
	_mock.Called(localPath)
	return
}

// MockService_Discard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Discard'
type MockService_Discard_Call struct {
	*mock.Call
}

// Discard is a helper method to define mock.On call
//   - localPath string
func (_e *MockService_Expecter) Discard(localPath any) *MockService_Discard_Call {
	return &MockService_Discard_Call{Call: _e.mock.On("Discard", localPath)}
}

func (_c *MockService_Discard_Call) Run(run func(localPath string)) *MockService_Discard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Discard_Call) Return() *MockService_Discard_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_Discard_Call) RunAndReturn(run func(localPath string)) *MockService_Discard_Call {
	_c.Run(run)
	return _c
}

// SaveAttachment provides a mock function for the type MockService
func (_mock *MockService) SaveAttachment(ctx context.Context, subDir string, fileSize int64, maxSize int64, reader io.Reader) (string, error) {
	ret := _mock.Called(ctx, subDir, fileSize, maxSize, reader)

	if len(ret) == 0 {
		panic("no return value specified for SaveAttachment")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64, io.Reader) (string, error)); ok {
		return returnFunc(ctx, subDir, fileSize, maxSize, reader)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64, io.Reader) string); ok {
		r0 = returnFunc(ctx, subDir, fileSize, maxSize, reader)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, int64, io.Reader) error); ok {
		r1 = returnFunc(ctx, subDir, fileSize, maxSize, reader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_SaveAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAttachment'
type MockService_SaveAttachment_Call struct {
	*mock.Call
}

// SaveAttachment is a helper method to define mock.On call
//   - ctx context.Context
//   - subDir string
//   - fileSize int64
//   - maxSize int64
//   - reader io.Reader
func (_e *MockService_Expecter) SaveAttachment(ctx any, subDir any, fileSize any, maxSize any, reader any) *MockService_SaveAttachment_Call {
	return &MockService_SaveAttachment_Call{Call: _e.mock.On("SaveAttachment", ctx, subDir, fileSize, maxSize, reader)}
}

func (_c *MockService_SaveAttachment_Call) Run(run func(ctx context.Context, subDir string, fileSize int64, maxSize int64, reader io.Reader)) *MockService_SaveAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 io.Reader
		if args[4] != nil {
			arg4 = args[4].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockService_SaveAttachment_Call) Return(s string, err error) *MockService_SaveAttachment_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_SaveAttachment_Call) RunAndReturn(run func(ctx context.Context, subDir string, fileSize int64, maxSize int64, reader io.Reader) (string, error)) *MockService_SaveAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAudio provides a mock function for the type MockService
func (_mock *MockService) SaveAudio(ctx context.Context, subDir string, id uuid.UUID, fileSize int64, maxSize int64, reader io.Reader) (string, error) {
	ret := _mock.Called(ctx, subDir, id, fileSize, maxSize, reader)

	if len(ret) == 0 {
		panic("no return value specified for SaveAudio")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, int64, int64, io.Reader) (string, error)); ok {
		return returnFunc(ctx, subDir, id, fileSize, maxSize, reader)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, int64, int64, io.Reader) string); ok {
		r0 = returnFunc(ctx, subDir, id, fileSize, maxSize, reader)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uuid.UUID, int64, int64, io.Reader) error); ok {
		r1 = returnFunc(ctx, subDir, id, fileSize, maxSize, reader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_SaveAudio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAudio'
type MockService_SaveAudio_Call struct {
	*mock.Call
}

// SaveAudio is a helper method to define mock.On call
//   - ctx context.Context
//   - subDir string
//   - id uuid.UUID
//   - fileSize int64
//   - maxSize int64
//   - reader io.Reader
func (_e *MockService_Expecter) SaveAudio(ctx any, subDir any, id any, fileSize any, maxSize any, reader any) *MockService_SaveAudio_Call {
	return &MockService_SaveAudio_Call{Call: _e.mock.On("SaveAudio", ctx, subDir, id, fileSize, maxSize, reader)}
}

func (_c *MockService_SaveAudio_Call) Run(run func(ctx context.Context, subDir string, id uuid.UUID, fileSize int64, maxSize int64, reader io.Reader)) *MockService_SaveAudio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 io.Reader
		if args[5] != nil {
			arg5 = args[5].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockService_SaveAudio_Call) Return(s string, err error) *MockService_SaveAudio_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_SaveAudio_Call) RunAndReturn(run func(ctx context.Context, subDir string, id uuid.UUID, fileSize int64, maxSize int64, reader io.Reader) (string, error)) *MockService_SaveAudio_Call {
	_c.Call.Return(run)
	return _c
}

// SaveFile provides a mock function for the type MockService
func (_mock *MockService) SaveFile(ctx context.Context, subDir string, filename string, reader io.Reader) (string, error) {
	ret := _mock.Called(ctx, subDir, filename, reader)

	if len(ret) == 0 {
		panic("no return value specified for SaveFile")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, io.Reader) (string, error)); ok {
		return returnFunc(ctx, subDir, filename, reader)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, io.Reader) string); ok {
		r0 = returnFunc(ctx, subDir, filename, reader)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, io.Reader) error); ok {
		r1 = returnFunc(ctx, subDir, filename, reader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_SaveFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveFile'
type MockService_SaveFile_Call struct {
	*mock.Call
}

// SaveFile is a helper method to define mock.On call
//   - ctx context.Context
//   - subDir string
//   - filename string
//   - reader io.Reader
func (_e *MockService_Expecter) SaveFile(ctx any, subDir any, filename any, reader any) *MockService_SaveFile_Call {
	return &MockService_SaveFile_Call{Call: _e.mock.On("SaveFile", ctx, subDir, filename, reader)}
}

func (_c *MockService_SaveFile_Call) Run(run func(ctx context.Context, subDir string, filename string, reader io.Reader)) *MockService_SaveFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_SaveFile_Call) Return(s string, err error) *MockService_SaveFile_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_SaveFile_Call) RunAndReturn(run func(ctx context.Context, subDir string, filename string, reader io.Reader) (string, error)) *MockService_SaveFile_Call {
	_c.Call.Return(run)
	return _c
}

// SaveImage provides a mock function for the type MockService
func (_mock *MockService) SaveImage(ctx context.Context, subDir string, id uuid.UUID, fileSize int64, maxSize int64, reader io.Reader) (string, error) {
	ret := _mock.Called(ctx, subDir, id, fileSize, maxSize, reader)

	if len(ret) == 0 {
		panic("no return value specified for SaveImage")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, int64, int64, io.Reader) (string, error)); ok {
		return returnFunc(ctx, subDir, id, fileSize, maxSize, reader)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, int64, int64, io.Reader) string); ok {
		r0 = returnFunc(ctx, subDir, id, fileSize, maxSize, reader)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uuid.UUID, int64, int64, io.Reader) error); ok {
		r1 = returnFunc(ctx, subDir, id, fileSize, maxSize, reader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_SaveImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveImage'
type MockService_SaveImage_Call struct {
	*mock.Call
}

// SaveImage is a helper method to define mock.On call
//   - ctx context.Context
//   - subDir string
//   - id uuid.UUID
//   - fileSize int64
//   - maxSize int64
//   - reader io.Reader
func (_e *MockService_Expecter) SaveImage(ctx any, subDir any, id any, fileSize any, maxSize any, reader any) *MockService_SaveImage_Call {
	return &MockService_SaveImage_Call{Call: _e.mock.On("SaveImage", ctx, subDir, id, fileSize, maxSize, reader)}
}

func (_c *MockService_SaveImage_Call) Run(run func(ctx context.Context, subDir string, id uuid.UUID, fileSize int64, maxSize int64, reader io.Reader)) *MockService_SaveImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 io.Reader
		if args[5] != nil {
			arg5 = args[5].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockService_SaveImage_Call) Return(s string, err error) *MockService_SaveImage_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_SaveImage_Call) RunAndReturn(run func(ctx context.Context, subDir string, id uuid.UUID, fileSize int64, maxSize int64, reader io.Reader) (string, error)) *MockService_SaveImage_Call {
	_c.Call.Return(run)
	return _c
}

// StageMedia provides a mock function for the type MockService
func (_mock *MockService) StageMedia(ctx context.Context, mediaType string, subDir string, id uuid.UUID, fileSize int64, maxSize int64, reader io.Reader) (string, error) {
	ret := _mock.Called(ctx, mediaType, subDir, id, fileSize, maxSize, reader)

	if len(ret) == 0 {
		panic("no return value specified for StageMedia")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, uuid.UUID, int64, int64, io.Reader) (string, error)); ok {
		return returnFunc(ctx, mediaType, subDir, id, fileSize, maxSize, reader)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, uuid.UUID, int64, int64, io.Reader) string); ok {
		r0 = returnFunc(ctx, mediaType, subDir, id, fileSize, maxSize, reader)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, uuid.UUID, int64, int64, io.Reader) error); ok {
		r1 = returnFunc(ctx, mediaType, subDir, id, fileSize, maxSize, reader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_StageMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StageMedia'
type MockService_StageMedia_Call struct {
	*mock.Call
}

// StageMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - mediaType string
//   - subDir string
//   - id uuid.UUID
//   - fileSize int64
//   - maxSize int64
//   - reader io.Reader
func (_e *MockService_Expecter) StageMedia(ctx any, mediaType any, subDir any, id any, fileSize any, maxSize any, reader any) *MockService_StageMedia_Call {
	return &MockService_StageMedia_Call{Call: _e.mock.On("StageMedia", ctx, mediaType, subDir, id, fileSize, maxSize, reader)}
}

func (_c *MockService_StageMedia_Call) Run(run func(ctx context.Context, mediaType string, subDir string, id uuid.UUID, fileSize int64, maxSize int64, reader io.Reader)) *MockService_StageMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 int64
		if args[5] != nil {
			arg5 = args[5].(int64)
		}
		var arg6 io.Reader
		if args[6] != nil {
			arg6 = args[6].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockService_StageMedia_Call) Return(s string, err error) *MockService_StageMedia_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_StageMedia_Call) RunAndReturn(run func(ctx context.Context, mediaType string, subDir string, id uuid.UUID, fileSize int64, maxSize int64, reader io.Reader) (string, error)) *MockService_StageMedia_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function for the type MockService
func (_mock *MockService) Store(ctx context.Context, subDir string, localPath string) (string, error) {
	ret := _mock.Called(ctx, subDir, localPath)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, subDir, localPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, subDir, localPath)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, subDir, localPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockService_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - subDir string
//   - localPath string
func (_e *MockService_Expecter) Store(ctx any, subDir any, localPath any) *MockService_Store_Call {
	return &MockService_Store_Call{Call: _e.mock.On("Store", ctx, subDir, localPath)}
}

func (_c *MockService_Store_Call) Run(run func(ctx context.Context, subDir string, localPath string)) *MockService_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Store_Call) Return(s string, err error) *MockService_Store_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_Store_Call) RunAndReturn(run func(ctx context.Context, subDir string, localPath string) (string, error)) *MockService_Store_Call {
	_c.Call.Return(run)
	return _c
}
