// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package hyperbeam

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateVM provides a mock function for the type MockService
func (_mock *MockService) CreateVM(ctx context.Context, opts CreateVMOptions) (*VM, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for CreateVM")
	}

	var r0 *VM
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateVMOptions) (*VM, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateVMOptions) *VM); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*VM)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CreateVMOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateVM_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVM'
type MockService_CreateVM_Call struct {
	*mock.Call
}

// CreateVM is a helper method to define mock.On call
//   - ctx context.Context
//   - opts CreateVMOptions
func (_e *MockService_Expecter) CreateVM(ctx interface{}, opts interface{}) *MockService_CreateVM_Call {
	return &MockService_CreateVM_Call{Call: _e.mock.On("CreateVM", ctx, opts)}
}

func (_c *MockService_CreateVM_Call) Run(run func(ctx context.Context, opts CreateVMOptions)) *MockService_CreateVM_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateVMOptions
		if args[1] != nil {
			arg1 = args[1].(CreateVMOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CreateVM_Call) Return(vM *VM, err error) *MockService_CreateVM_Call {
	_c.Call.Return(vM, err)
	return _c
}

func (_c *MockService_CreateVM_Call) RunAndReturn(run func(ctx context.Context, opts CreateVMOptions) (*VM, error)) *MockService_CreateVM_Call {
	_c.Call.Return(run)
	return _c
}

// Enabled provides a mock function for the type MockService
func (_mock *MockService) Enabled() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Enabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockService_Enabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enabled'
type MockService_Enabled_Call struct {
	*mock.Call
}

// Enabled is a helper method to define mock.On call
func (_e *MockService_Expecter) Enabled() *MockService_Enabled_Call {
	return &MockService_Enabled_Call{Call: _e.mock.On("Enabled")}
}

func (_c *MockService_Enabled_Call) Run(run func()) *MockService_Enabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Enabled_Call) Return(b bool) *MockService_Enabled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockService_Enabled_Call) RunAndReturn(run func() bool) *MockService_Enabled_Call {
	_c.Call.Return(run)
	return _c
}

// GetVMStatus provides a mock function for the type MockService
func (_mock *MockService) GetVMStatus(ctx context.Context, sessionID string) (*VMStatus, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetVMStatus")
	}

	var r0 *VMStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*VMStatus, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *VMStatus); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*VMStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetVMStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVMStatus'
type MockService_GetVMStatus_Call struct {
	*mock.Call
}

// GetVMStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockService_Expecter) GetVMStatus(ctx interface{}, sessionID interface{}) *MockService_GetVMStatus_Call {
	return &MockService_GetVMStatus_Call{Call: _e.mock.On("GetVMStatus", ctx, sessionID)}
}

func (_c *MockService_GetVMStatus_Call) Run(run func(ctx context.Context, sessionID string)) *MockService_GetVMStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetVMStatus_Call) Return(vMStatus *VMStatus, err error) *MockService_GetVMStatus_Call {
	_c.Call.Return(vMStatus, err)
	return _c
}

func (_c *MockService_GetVMStatus_Call) RunAndReturn(run func(ctx context.Context, sessionID string) (*VMStatus, error)) *MockService_GetVMStatus_Call {
	_c.Call.Return(run)
	return _c
}

// SetControlRole provides a mock function for the type MockService
func (_mock *MockService) SetControlRole(ctx context.Context, vmBaseURL string, userIdentifier string, hasControl bool) error {
	ret := _mock.Called(ctx, vmBaseURL, userIdentifier, hasControl)

	if len(ret) == 0 {
		panic("no return value specified for SetControlRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) error); ok {
		r0 = returnFunc(ctx, vmBaseURL, userIdentifier, hasControl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SetControlRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetControlRole'
type MockService_SetControlRole_Call struct {
	*mock.Call
}

// SetControlRole is a helper method to define mock.On call
//   - ctx context.Context
//   - vmBaseURL string
//   - userIdentifier string
//   - hasControl bool
func (_e *MockService_Expecter) SetControlRole(ctx interface{}, vmBaseURL interface{}, userIdentifier interface{}, hasControl interface{}) *MockService_SetControlRole_Call {
	return &MockService_SetControlRole_Call{Call: _e.mock.On("SetControlRole", ctx, vmBaseURL, userIdentifier, hasControl)}
}

func (_c *MockService_SetControlRole_Call) Run(run func(ctx context.Context, vmBaseURL string, userIdentifier string, hasControl bool)) *MockService_SetControlRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_SetControlRole_Call) Return(err error) *MockService_SetControlRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SetControlRole_Call) RunAndReturn(run func(ctx context.Context, vmBaseURL string, userIdentifier string, hasControl bool) error) *MockService_SetControlRole_Call {
	_c.Call.Return(run)
	return _c
}

// TerminateVM provides a mock function for the type MockService
func (_mock *MockService) TerminateVM(ctx context.Context, sessionID string) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for TerminateVM")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_TerminateVM_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TerminateVM'
type MockService_TerminateVM_Call struct {
	*mock.Call
}

// TerminateVM is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockService_Expecter) TerminateVM(ctx interface{}, sessionID interface{}) *MockService_TerminateVM_Call {
	return &MockService_TerminateVM_Call{Call: _e.mock.On("TerminateVM", ctx, sessionID)}
}

func (_c *MockService_TerminateVM_Call) Run(run func(ctx context.Context, sessionID string)) *MockService_TerminateVM_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_TerminateVM_Call) Return(err error) *MockService_TerminateVM_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_TerminateVM_Call) RunAndReturn(run func(ctx context.Context, sessionID string) error) *MockService_TerminateVM_Call {
	_c.Call.Return(run)
	return _c
}
