// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usersecret

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetUserIDsWithSecret provides a mock function for the type MockService
func (_mock *MockService) GetUserIDsWithSecret(ctx context.Context, secretID string) ([]uuid.UUID, error) {
	ret := _mock.Called(ctx, secretID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserIDsWithSecret")
	}

	var r0 []uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]uuid.UUID, error)); ok {
		return returnFunc(ctx, secretID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []uuid.UUID); ok {
		r0 = returnFunc(ctx, secretID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, secretID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetUserIDsWithSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserIDsWithSecret'
type MockService_GetUserIDsWithSecret_Call struct {
	*mock.Call
}

// GetUserIDsWithSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID string
func (_e *MockService_Expecter) GetUserIDsWithSecret(ctx interface{}, secretID interface{}) *MockService_GetUserIDsWithSecret_Call {
	return &MockService_GetUserIDsWithSecret_Call{Call: _e.mock.On("GetUserIDsWithSecret", ctx, secretID)}
}

func (_c *MockService_GetUserIDsWithSecret_Call) Run(run func(ctx context.Context, secretID string)) *MockService_GetUserIDsWithSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetUserIDsWithSecret_Call) Return(uUIDs []uuid.UUID, err error) *MockService_GetUserIDsWithSecret_Call {
	_c.Call.Return(uUIDs, err)
	return _c
}

func (_c *MockService_GetUserIDsWithSecret_Call) RunAndReturn(run func(ctx context.Context, secretID string) ([]uuid.UUID, error)) *MockService_GetUserIDsWithSecret_Call {
	_c.Call.Return(run)
	return _c
}

// IsSolvedByAnyone provides a mock function for the type MockService
func (_mock *MockService) IsSolvedByAnyone(ctx context.Context, secretID string) (bool, error) {
	ret := _mock.Called(ctx, secretID)

	if len(ret) == 0 {
		panic("no return value specified for IsSolvedByAnyone")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, secretID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, secretID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, secretID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_IsSolvedByAnyone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSolvedByAnyone'
type MockService_IsSolvedByAnyone_Call struct {
	*mock.Call
}

// IsSolvedByAnyone is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID string
func (_e *MockService_Expecter) IsSolvedByAnyone(ctx interface{}, secretID interface{}) *MockService_IsSolvedByAnyone_Call {
	return &MockService_IsSolvedByAnyone_Call{Call: _e.mock.On("IsSolvedByAnyone", ctx, secretID)}
}

func (_c *MockService_IsSolvedByAnyone_Call) Run(run func(ctx context.Context, secretID string)) *MockService_IsSolvedByAnyone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_IsSolvedByAnyone_Call) Return(b bool, err error) *MockService_IsSolvedByAnyone_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockService_IsSolvedByAnyone_Call) RunAndReturn(run func(ctx context.Context, secretID string) (bool, error)) *MockService_IsSolvedByAnyone_Call {
	_c.Call.Return(run)
	return _c
}

// ListForUser provides a mock function for the type MockService
func (_mock *MockService) ListForUser(ctx context.Context, userID uuid.UUID) ([]string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListForUser")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListForUser'
type MockService_ListForUser_Call struct {
	*mock.Call
}

// ListForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockService_Expecter) ListForUser(ctx interface{}, userID interface{}) *MockService_ListForUser_Call {
	return &MockService_ListForUser_Call{Call: _e.mock.On("ListForUser", ctx, userID)}
}

func (_c *MockService_ListForUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockService_ListForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ListForUser_Call) Return(strings []string, err error) *MockService_ListForUser_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockService_ListForUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]string, error)) *MockService_ListForUser_Call {
	_c.Call.Return(run)
	return _c
}

// Unlock provides a mock function for the type MockService
func (_mock *MockService) Unlock(ctx context.Context, userID uuid.UUID, secretRef string, phrase string) (*UnlockResult, error) {
	ret := _mock.Called(ctx, userID, secretRef, phrase)

	if len(ret) == 0 {
		panic("no return value specified for Unlock")
	}

	var r0 *UnlockResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (*UnlockResult, error)); ok {
		return returnFunc(ctx, userID, secretRef, phrase)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) *UnlockResult); ok {
		r0 = returnFunc(ctx, userID, secretRef, phrase)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UnlockResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = returnFunc(ctx, userID, secretRef, phrase)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Unlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unlock'
type MockService_Unlock_Call struct {
	*mock.Call
}

// Unlock is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - secretRef string
//   - phrase string
func (_e *MockService_Expecter) Unlock(ctx interface{}, userID interface{}, secretRef interface{}, phrase interface{}) *MockService_Unlock_Call {
	return &MockService_Unlock_Call{Call: _e.mock.On("Unlock", ctx, userID, secretRef, phrase)}
}

func (_c *MockService_Unlock_Call) Run(run func(ctx context.Context, userID uuid.UUID, secretRef string, phrase string)) *MockService_Unlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_Unlock_Call) Return(unlockResult *UnlockResult, err error) *MockService_Unlock_Call {
	_c.Call.Return(unlockResult, err)
	return _c
}

func (_c *MockService_Unlock_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, secretRef string, phrase string) (*UnlockResult, error)) *MockService_Unlock_Call {
	_c.Call.Return(run)
	return _c
}
