-- +goose Up

CREATE TABLE ocs (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    series TEXT NOT NULL,
    custom_series_name TEXT NOT NULL DEFAULT '',
    image_url TEXT NOT NULL DEFAULT '',
    thumbnail_url TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (series IN ('umineko', 'higurashi', 'ciconia', 'custom')),
    CHECK (series <> 'custom' OR custom_series_name <> '')
);
CREATE UNIQUE INDEX idx_ocs_user_name_lower ON ocs (user_id, lower(name));
CREATE INDEX idx_ocs_user_id ON ocs (user_id);
CREATE INDEX idx_ocs_series ON ocs (series);
CREATE INDEX idx_ocs_custom_series_name ON ocs (lower(custom_series_name)) WHERE series = 'custom';

ALTER TABLE ocs ADD COLUMN search_vector tsvector
    GENERATED ALWAYS AS (
        setweight(to_tsvector('english', coalesce(name, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(description, '')), 'B')
    ) STORED;
CREATE INDEX idx_ocs_search_vector ON ocs USING GIN(search_vector);
CREATE INDEX idx_ocs_name_trgm ON ocs USING GIN(name gin_trgm_ops);

CREATE TABLE oc_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oc_id UUID NOT NULL REFERENCES ocs(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    thumbnail_url TEXT NOT NULL DEFAULT '',
    caption TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX idx_oc_images_oc_id ON oc_images (oc_id, sort_order);

CREATE TABLE oc_votes (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    oc_id UUID NOT NULL REFERENCES ocs(id) ON DELETE CASCADE,
    value INTEGER NOT NULL CHECK (value IN (1, -1)),
    PRIMARY KEY (user_id, oc_id)
);

CREATE TABLE oc_favourites (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    oc_id UUID NOT NULL REFERENCES ocs(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, oc_id)
);
CREATE INDEX idx_oc_favourites_oc_id ON oc_favourites (oc_id);

CREATE TABLE oc_comments (
    id UUID PRIMARY KEY,
    oc_id UUID NOT NULL REFERENCES ocs(id) ON DELETE CASCADE,
    parent_id UUID REFERENCES oc_comments(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);
CREATE INDEX idx_oc_comments_oc_id ON oc_comments (oc_id, created_at);

ALTER TABLE oc_comments ADD COLUMN search_vector tsvector
    GENERATED ALWAYS AS (to_tsvector('english', coalesce(body, ''))) STORED;
CREATE INDEX idx_oc_comments_search_vector ON oc_comments USING GIN(search_vector);

CREATE TABLE oc_comment_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id UUID NOT NULL REFERENCES oc_comments(id) ON DELETE CASCADE,
    media_url TEXT NOT NULL,
    media_type TEXT NOT NULL,
    thumbnail_url TEXT NOT NULL DEFAULT '',
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE oc_comment_likes (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    comment_id UUID NOT NULL REFERENCES oc_comments(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, comment_id)
);

ALTER TABLE users ADD COLUMN default_profile_tab TEXT NOT NULL DEFAULT 'posts'
    CHECK (default_profile_tab IN (
        'posts', 'theories', 'art', 'galleries', 'ships', 'mysteries', 'fanfics',
        'fanfic-favourites', 'journals', 'journal-follows', 'activity', 'followers', 'following', 'ocs'
    ));

-- +goose Down

ALTER TABLE users DROP COLUMN IF EXISTS default_profile_tab;

DROP TABLE IF EXISTS oc_comment_likes;
DROP TABLE IF EXISTS oc_comment_media;

DROP INDEX IF EXISTS idx_oc_comments_search_vector;
DROP INDEX IF EXISTS idx_oc_comments_oc_id;
DROP TABLE IF EXISTS oc_comments;

DROP INDEX IF EXISTS idx_oc_favourites_oc_id;
DROP TABLE IF EXISTS oc_favourites;

DROP TABLE IF EXISTS oc_votes;

DROP INDEX IF EXISTS idx_oc_images_oc_id;
DROP TABLE IF EXISTS oc_images;

DROP INDEX IF EXISTS idx_ocs_name_trgm;
DROP INDEX IF EXISTS idx_ocs_search_vector;
DROP INDEX IF EXISTS idx_ocs_custom_series_name;
DROP INDEX IF EXISTS idx_ocs_series;
DROP INDEX IF EXISTS idx_ocs_user_id;
DROP INDEX IF EXISTS idx_ocs_user_name_lower;
DROP TABLE IF EXISTS ocs;
