-- +goose Up
ALTER TABLE announcement_comments ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE announcements ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE art ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE art_comments ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE chat_banned_words ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE chat_messages ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE chat_rooms ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE chatbot_base_prompts ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE chatbot_invocations ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE chatbots ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE fanfic_chapters ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE fanfic_comments ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE fanfics ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE galleries ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE game_rooms ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE journal_comments ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE journal_entries ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE journals ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE mysteries ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE mystery_attempts ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE mystery_comments ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE oc_comments ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE ocs ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE post_comments ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE post_polls ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE posts ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE responses ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE secret_comments ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE ship_comments ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE ships ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE theories ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE users ALTER COLUMN id SET DEFAULT gen_random_uuid();

-- +goose Down
ALTER TABLE announcement_comments ALTER COLUMN id DROP DEFAULT;
ALTER TABLE announcements ALTER COLUMN id DROP DEFAULT;
ALTER TABLE art ALTER COLUMN id DROP DEFAULT;
ALTER TABLE art_comments ALTER COLUMN id DROP DEFAULT;
ALTER TABLE chat_banned_words ALTER COLUMN id DROP DEFAULT;
ALTER TABLE chat_messages ALTER COLUMN id DROP DEFAULT;
ALTER TABLE chat_rooms ALTER COLUMN id DROP DEFAULT;
ALTER TABLE chatbot_base_prompts ALTER COLUMN id DROP DEFAULT;
ALTER TABLE chatbot_invocations ALTER COLUMN id DROP DEFAULT;
ALTER TABLE chatbots ALTER COLUMN id DROP DEFAULT;
ALTER TABLE fanfic_chapters ALTER COLUMN id DROP DEFAULT;
ALTER TABLE fanfic_comments ALTER COLUMN id DROP DEFAULT;
ALTER TABLE fanfics ALTER COLUMN id DROP DEFAULT;
ALTER TABLE galleries ALTER COLUMN id DROP DEFAULT;
ALTER TABLE game_rooms ALTER COLUMN id DROP DEFAULT;
ALTER TABLE journal_comments ALTER COLUMN id DROP DEFAULT;
ALTER TABLE journal_entries ALTER COLUMN id DROP DEFAULT;
ALTER TABLE journals ALTER COLUMN id DROP DEFAULT;
ALTER TABLE mysteries ALTER COLUMN id DROP DEFAULT;
ALTER TABLE mystery_attempts ALTER COLUMN id DROP DEFAULT;
ALTER TABLE mystery_comments ALTER COLUMN id DROP DEFAULT;
ALTER TABLE oc_comments ALTER COLUMN id DROP DEFAULT;
ALTER TABLE ocs ALTER COLUMN id DROP DEFAULT;
ALTER TABLE post_comments ALTER COLUMN id DROP DEFAULT;
ALTER TABLE post_polls ALTER COLUMN id DROP DEFAULT;
ALTER TABLE posts ALTER COLUMN id DROP DEFAULT;
ALTER TABLE responses ALTER COLUMN id DROP DEFAULT;
ALTER TABLE secret_comments ALTER COLUMN id DROP DEFAULT;
ALTER TABLE ship_comments ALTER COLUMN id DROP DEFAULT;
ALTER TABLE ships ALTER COLUMN id DROP DEFAULT;
ALTER TABLE theories ALTER COLUMN id DROP DEFAULT;
ALTER TABLE users ALTER COLUMN id DROP DEFAULT;
