// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package openai

import (
	"context"
	"time"
	"umineko_city_of_books/internal/config"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Complete provides a mock function for the type MockService
func (_mock *MockService) Complete(ctx context.Context, req CompletionRequest) (*CompletionResult, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 *CompletionResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CompletionRequest) (*CompletionResult, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CompletionRequest) *CompletionResult); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CompletionResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CompletionRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockService_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
//   - req CompletionRequest
func (_e *MockService_Expecter) Complete(ctx any, req any) *MockService_Complete_Call {
	return &MockService_Complete_Call{Call: _e.mock.On("Complete", ctx, req)}
}

func (_c *MockService_Complete_Call) Run(run func(ctx context.Context, req CompletionRequest)) *MockService_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CompletionRequest
		if args[1] != nil {
			arg1 = args[1].(CompletionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Complete_Call) Return(completionResult *CompletionResult, err error) *MockService_Complete_Call {
	_c.Call.Return(completionResult, err)
	return _c
}

func (_c *MockService_Complete_Call) RunAndReturn(run func(ctx context.Context, req CompletionRequest) (*CompletionResult, error)) *MockService_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// Costs provides a mock function for the type MockService
func (_mock *MockService) Costs(ctx context.Context, since time.Time) (*CostsResult, error) {
	ret := _mock.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for Costs")
	}

	var r0 *CostsResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) (*CostsResult, error)); ok {
		return returnFunc(ctx, since)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) *CostsResult); ok {
		r0 = returnFunc(ctx, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CostsResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, since)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Costs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Costs'
type MockService_Costs_Call struct {
	*mock.Call
}

// Costs is a helper method to define mock.On call
//   - ctx context.Context
//   - since time.Time
func (_e *MockService_Expecter) Costs(ctx any, since any) *MockService_Costs_Call {
	return &MockService_Costs_Call{Call: _e.mock.On("Costs", ctx, since)}
}

func (_c *MockService_Costs_Call) Run(run func(ctx context.Context, since time.Time)) *MockService_Costs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Costs_Call) Return(costsResult *CostsResult, err error) *MockService_Costs_Call {
	_c.Call.Return(costsResult, err)
	return _c
}

func (_c *MockService_Costs_Call) RunAndReturn(run func(ctx context.Context, since time.Time) (*CostsResult, error)) *MockService_Costs_Call {
	_c.Call.Return(run)
	return _c
}

// Enabled provides a mock function for the type MockService
func (_mock *MockService) Enabled() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Enabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockService_Enabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enabled'
type MockService_Enabled_Call struct {
	*mock.Call
}

// Enabled is a helper method to define mock.On call
func (_e *MockService_Expecter) Enabled() *MockService_Enabled_Call {
	return &MockService_Enabled_Call{Call: _e.mock.On("Enabled")}
}

func (_c *MockService_Enabled_Call) Run(run func()) *MockService_Enabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Enabled_Call) Return(b bool) *MockService_Enabled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockService_Enabled_Call) RunAndReturn(run func() bool) *MockService_Enabled_Call {
	_c.Call.Return(run)
	return _c
}

// Models provides a mock function for the type MockService
func (_mock *MockService) Models(ctx context.Context) ([]string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Models")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Models_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Models'
type MockService_Models_Call struct {
	*mock.Call
}

// Models is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Models(ctx any) *MockService_Models_Call {
	return &MockService_Models_Call{Call: _e.mock.On("Models", ctx)}
}

func (_c *MockService_Models_Call) Run(run func(ctx context.Context)) *MockService_Models_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Models_Call) Return(strings []string, err error) *MockService_Models_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockService_Models_Call) RunAndReturn(run func(ctx context.Context) ([]string, error)) *MockService_Models_Call {
	_c.Call.Return(run)
	return _c
}

// OnSettingsBatchChanged provides a mock function for the type MockService
func (_mock *MockService) OnSettingsBatchChanged(keys []config.SiteSettingKey) {
	_mock.Called(keys)
	return
}

// MockService_OnSettingsBatchChanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnSettingsBatchChanged'
type MockService_OnSettingsBatchChanged_Call struct {
	*mock.Call
}

// OnSettingsBatchChanged is a helper method to define mock.On call
//   - keys []config.SiteSettingKey
func (_e *MockService_Expecter) OnSettingsBatchChanged(keys any) *MockService_OnSettingsBatchChanged_Call {
	return &MockService_OnSettingsBatchChanged_Call{Call: _e.mock.On("OnSettingsBatchChanged", keys)}
}

func (_c *MockService_OnSettingsBatchChanged_Call) Run(run func(keys []config.SiteSettingKey)) *MockService_OnSettingsBatchChanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []config.SiteSettingKey
		if args[0] != nil {
			arg0 = args[0].([]config.SiteSettingKey)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_OnSettingsBatchChanged_Call) Return() *MockService_OnSettingsBatchChanged_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_OnSettingsBatchChanged_Call) RunAndReturn(run func(keys []config.SiteSettingKey)) *MockService_OnSettingsBatchChanged_Call {
	_c.Run(run)
	return _c
}
