// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stored_file.sql

package sqlcgen

import (
	"context"

	"github.com/lib/pq"
)

const backfillStoredFiles = `-- name: BackfillStoredFiles :execrows
INSERT INTO stored_files (key, backend, location, size)
SELECT unnest($1::text[]), $2::storage_backend, unnest($3::text[]), unnest($4::bigint[])
ON CONFLICT (key) DO NOTHING
`

type BackfillStoredFilesParams struct {
	Keys      []string
	Backend   StorageBackend
	Locations []string
	Sizes     []int64
}

func (q *Queries) BackfillStoredFiles(ctx context.Context, arg BackfillStoredFilesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, backfillStoredFiles,
		pq.Array(arg.Keys),
		arg.Backend,
		pq.Array(arg.Locations),
		pq.Array(arg.Sizes),
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countStoredFilesByBackend = `-- name: CountStoredFilesByBackend :one
SELECT count(*) FROM stored_files WHERE backend = $1
`

func (q *Queries) CountStoredFilesByBackend(ctx context.Context, backend StorageBackend) (int64, error) {
	row := q.db.QueryRowContext(ctx, countStoredFilesByBackend, backend)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteStoredFiles = `-- name: DeleteStoredFiles :exec
DELETE FROM stored_files WHERE key = ANY($1::text[])
`

func (q *Queries) DeleteStoredFiles(ctx context.Context, keys []string) error {
	_, err := q.db.ExecContext(ctx, deleteStoredFiles, pq.Array(keys))
	return err
}

const getStoredFile = `-- name: GetStoredFile :one
SELECT key, backend, location, size, created_at FROM stored_files WHERE key = $1
`

func (q *Queries) GetStoredFile(ctx context.Context, key string) (StoredFile, error) {
	row := q.db.QueryRowContext(ctx, getStoredFile, key)
	var i StoredFile
	err := row.Scan(
		&i.Key,
		&i.Backend,
		&i.Location,
		&i.Size,
		&i.CreatedAt,
	)
	return i, err
}

const listStoredFilesByKeys = `-- name: ListStoredFilesByKeys :many
SELECT key, backend, location, size, created_at FROM stored_files WHERE key = ANY($1::text[])
`

func (q *Queries) ListStoredFilesByKeys(ctx context.Context, keys []string) ([]StoredFile, error) {
	rows, err := q.db.QueryContext(ctx, listStoredFilesByKeys, pq.Array(keys))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoredFile{}
	for rows.Next() {
		var i StoredFile
		if err := rows.Scan(
			&i.Key,
			&i.Backend,
			&i.Location,
			&i.Size,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoredFilesByPrefix = `-- name: ListStoredFilesByPrefix :many
SELECT key, backend, location, size, created_at FROM stored_files
WHERE starts_with(key, $1::text)
ORDER BY key
`

func (q *Queries) ListStoredFilesByPrefix(ctx context.Context, prefix string) ([]StoredFile, error) {
	rows, err := q.db.QueryContext(ctx, listStoredFilesByPrefix, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoredFile{}
	for rows.Next() {
		var i StoredFile
		if err := rows.Scan(
			&i.Key,
			&i.Backend,
			&i.Location,
			&i.Size,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStoredFile = `-- name: UpsertStoredFile :exec
INSERT INTO stored_files (key, backend, location, size) VALUES ($1, $2, $3, $4)
ON CONFLICT (key) DO UPDATE SET backend = EXCLUDED.backend, location = EXCLUDED.location, size = EXCLUDED.size, created_at = now()
`

type UpsertStoredFileParams struct {
	Key      string
	Backend  StorageBackend
	Location string
	Size     int64
}

func (q *Queries) UpsertStoredFile(ctx context.Context, arg UpsertStoredFileParams) error {
	_, err := q.db.ExecContext(ctx, upsertStoredFile,
		arg.Key,
		arg.Backend,
		arg.Location,
		arg.Size,
	)
	return err
}
