// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package search

import (
	"context"
	"umineko_city_of_books/internal/repository"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// ChildEntityTypes provides a mock function for the type MockService
func (_mock *MockService) ChildEntityTypes() []repository.SearchEntityType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ChildEntityTypes")
	}

	var r0 []repository.SearchEntityType
	if returnFunc, ok := ret.Get(0).(func() []repository.SearchEntityType); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.SearchEntityType)
		}
	}
	return r0
}

// MockService_ChildEntityTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChildEntityTypes'
type MockService_ChildEntityTypes_Call struct {
	*mock.Call
}

// ChildEntityTypes is a helper method to define mock.On call
func (_e *MockService_Expecter) ChildEntityTypes() *MockService_ChildEntityTypes_Call {
	return &MockService_ChildEntityTypes_Call{Call: _e.mock.On("ChildEntityTypes")}
}

func (_c *MockService_ChildEntityTypes_Call) Run(run func()) *MockService_ChildEntityTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_ChildEntityTypes_Call) Return(searchEntityTypes []repository.SearchEntityType) *MockService_ChildEntityTypes_Call {
	_c.Call.Return(searchEntityTypes)
	return _c
}

func (_c *MockService_ChildEntityTypes_Call) RunAndReturn(run func() []repository.SearchEntityType) *MockService_ChildEntityTypes_Call {
	_c.Call.Return(run)
	return _c
}

// ParseTypes provides a mock function for the type MockService
func (_mock *MockService) ParseTypes(raw string) []repository.SearchEntityType {
	ret := _mock.Called(raw)

	if len(ret) == 0 {
		panic("no return value specified for ParseTypes")
	}

	var r0 []repository.SearchEntityType
	if returnFunc, ok := ret.Get(0).(func(string) []repository.SearchEntityType); ok {
		r0 = returnFunc(raw)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.SearchEntityType)
		}
	}
	return r0
}

// MockService_ParseTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseTypes'
type MockService_ParseTypes_Call struct {
	*mock.Call
}

// ParseTypes is a helper method to define mock.On call
//   - raw string
func (_e *MockService_Expecter) ParseTypes(raw interface{}) *MockService_ParseTypes_Call {
	return &MockService_ParseTypes_Call{Call: _e.mock.On("ParseTypes", raw)}
}

func (_c *MockService_ParseTypes_Call) Run(run func(raw string)) *MockService_ParseTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_ParseTypes_Call) Return(searchEntityTypes []repository.SearchEntityType) *MockService_ParseTypes_Call {
	_c.Call.Return(searchEntityTypes)
	return _c
}

func (_c *MockService_ParseTypes_Call) RunAndReturn(run func(raw string) []repository.SearchEntityType) *MockService_ParseTypes_Call {
	_c.Call.Return(run)
	return _c
}

// QuickSearch provides a mock function for the type MockService
func (_mock *MockService) QuickSearch(ctx context.Context, query string, perTypeLimit int) ([]Result, error) {
	ret := _mock.Called(ctx, query, perTypeLimit)

	if len(ret) == 0 {
		panic("no return value specified for QuickSearch")
	}

	var r0 []Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) ([]Result, error)); ok {
		return returnFunc(ctx, query, perTypeLimit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) []Result); ok {
		r0 = returnFunc(ctx, query, perTypeLimit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, query, perTypeLimit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_QuickSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QuickSearch'
type MockService_QuickSearch_Call struct {
	*mock.Call
}

// QuickSearch is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - perTypeLimit int
func (_e *MockService_Expecter) QuickSearch(ctx interface{}, query interface{}, perTypeLimit interface{}) *MockService_QuickSearch_Call {
	return &MockService_QuickSearch_Call{Call: _e.mock.On("QuickSearch", ctx, query, perTypeLimit)}
}

func (_c *MockService_QuickSearch_Call) Run(run func(ctx context.Context, query string, perTypeLimit int)) *MockService_QuickSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_QuickSearch_Call) Return(results []Result, err error) *MockService_QuickSearch_Call {
	_c.Call.Return(results, err)
	return _c
}

func (_c *MockService_QuickSearch_Call) RunAndReturn(run func(ctx context.Context, query string, perTypeLimit int) ([]Result, error)) *MockService_QuickSearch_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockService
func (_mock *MockService) Search(ctx context.Context, query string, types []repository.SearchEntityType, limit int, offset int) ([]Result, int, error) {
	ret := _mock.Called(ctx, query, types, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []Result
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []repository.SearchEntityType, int, int) ([]Result, int, error)); ok {
		return returnFunc(ctx, query, types, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []repository.SearchEntityType, int, int) []Result); ok {
		r0 = returnFunc(ctx, query, types, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []repository.SearchEntityType, int, int) int); ok {
		r1 = returnFunc(ctx, query, types, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, []repository.SearchEntityType, int, int) error); ok {
		r2 = returnFunc(ctx, query, types, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockService_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - types []repository.SearchEntityType
//   - limit int
//   - offset int
func (_e *MockService_Expecter) Search(ctx interface{}, query interface{}, types interface{}, limit interface{}, offset interface{}) *MockService_Search_Call {
	return &MockService_Search_Call{Call: _e.mock.On("Search", ctx, query, types, limit, offset)}
}

func (_c *MockService_Search_Call) Run(run func(ctx context.Context, query string, types []repository.SearchEntityType, limit int, offset int)) *MockService_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []repository.SearchEntityType
		if args[2] != nil {
			arg2 = args[2].([]repository.SearchEntityType)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockService_Search_Call) Return(results []Result, n int, err error) *MockService_Search_Call {
	_c.Call.Return(results, n, err)
	return _c
}

func (_c *MockService_Search_Call) RunAndReturn(run func(ctx context.Context, query string, types []repository.SearchEntityType, limit int, offset int) ([]Result, int, error)) *MockService_Search_Call {
	_c.Call.Return(run)
	return _c
}
